### PR TITLE
fix(levm): add suport for `stCreate2`

### LINKED ISSUE #1941: LEVM: Add support for the `stCreate2` test suite
After adding the [`LegacyTest`](https://github.com/ethereum/legacytests/tree/b2e6c9e43ede7eec9c5b2997c14a892e7eb2f124), new folders containing tests for Pre-Cancun forks were added.
Currently the state of folder `stCreate2` is:
`stCreate2: 126/148 (85.14%)`.
We want to make it 100%

### PR DESCRIPTION
**Pull request by tomip01**
**Motivation**

In this PR we add increase the test passed in the `stCreate2` test suite

**Description**

* We add the correct values for the `ecadd`, `ecmul` and `ecpairing` precompiles to pre Istanbul forks. This is stated [here](https://eips.ethereum.org/EIPS/eip-1108)
* We invalidate transactions with the opcode `create2` on forks previous to Constantinople, see [here](https://eips.ethereum.org/EIPS/eip-1014)

Closes #1941

### CODE REVIEW

File: crates/vm/levm/src/gas_cost.rs [hunk 1]
```diff
@@ -1066,14 +1070,23 @@ fn precompile(data_size: usize, static_cost: u64, dynamic_base: u64) -> Result<u
...
+            ECPAIRING_GROUP_COST_PRE_ISTANBUL,
+            ECPAIRING_GROUP_COST_PRE_ISTANBUL,
+        )
+    } else {
+        (ECPAIRING_GROUP_COST, ECPAIRING_BASE_COST)
+    };
 
     let groups_cost = groups_number
-        .checked_mul(ECPAIRING_GROUP_COST)
+        .checked_mul(group_cost_scalar)
```
Comment (lima-limon-inc) [inline crates/vm/levm/src/gas_cost.rs:1086]: Love the name scalar!

;)

File: crates/vm/levm/src/opcode_handlers/system.rs [hunk 2]
```diff
@@ -426,6 +426,10 @@ impl VM {
         &mut self,
         current_call_frame: &mut CallFrame,
     ) -> Result<OpcodeResult, VMError> {
+        // https://eips.ethereum.org/EIPS/eip-1014
+        if self.env.config.fork < Fork::Constantinople {
+            return Err(VMError::InvalidOpcode);
+        }
```
Comment (lima-limon-inc) [inline crates/vm/levm/src/opcode_handlers/system.rs:432]: Nice!

**Review by lima-limon-inc — APPROVED** [review]
LGTM!

**Review by fborello-lambda — APPROVED** [review]

**Review by fkrause98 — APPROVED** [review]
