### PR TITLE
fix(l2,l1): add a default prover backend when compiling ethrex 

### LINKED ISSUE #2076: L2, L1: When compiling the project with the provided Makefile, compilation fails due to unspecified prover backend.
When compiling the project with

```
make build
```

You get the following error:
```
 --> crates/l2/prover/bench/src/main.rs:14:1
   |
14 | compile_error!("Choose prover backends (sp1, risc0).");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This is because the makefile does not set a specific prover backend.

### PR DESCRIPTION
**Pull request by lima-limon-inc**
**Motivation**

 When compiling the project with the provided Makefile, compilation fails due to unspecified prover backend. 

**Description**

Add a default Makefile variable to the Makefile. If the variable is not present, it will default to sp1.
Also, expand the compilation error message when there is no prover backend specified.

Closes #2076

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -5,8 +5,10 @@
 help: ## 📚 Show help for each of the Makefile recipes
 	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
 
+
+PROVER_BACKEND ?= sp1
 build: ## 🔨 Build the client
-	cargo build --workspace
+	cargo build --workspace -F $(PROVER_BACKEND)
```
Comment (mpaulucci) [inline Makefile:11]: can't we have a default prover backend feature feature?

Comment (lima-limon-inc) [reply Makefile:11]: > can't we have a default prover backend feature feature?

Hmm, I'm not too familiar with cargo feature flags. If you specify a set of default flags, and the you run cargo with a explicit flag, are the default feature flags ignored?

Comment (xqft) [inline Makefile:11]: The origin of the error is in the `l2/prover/bench` crate, so it wouldn't be necessary to add a feature in the `Makefile` but just to add `sp1` as a default feature in that crate

Comment (lima-limon-inc) [reply Makefile]: Changed here: https://github.com/lambdaclass/ethrex/pull/2075/commits/f194fb13913667841c0b6d872a337b227ec464dd

File: crates/l2/prover/bench/src/main.rs [hunk 2]
```diff
@@ -11,7 +11,10 @@ use ethrex_vm::execution_db::ToExecDB;
 use zkvm_interface::io::ProgramInput;
 
 #[cfg(not(any(feature = "sp1", feature = "risc0")))]
-compile_error!("Choose prover backends (sp1, risc0).");
+compile_error!(
+    "Choose prover backends (sp1, risc0).
+- Pass a feature flag to cargo (--feature or -F) with the desired backed. e.g: cargo build --workspace -F sp1."
+);
```
Comment (xqft) [inline crates/l2/prover/bench/src/main.rs:17]: nit: and specify --no-default-features

Comment (lima-limon-inc) [reply crates/l2/prover/bench/src/main.rs]: Noted!! Great catch Tefo

Fixed here: https://github.com/lambdaclass/ethrex/pull/2075/commits/2d016cf183ed0d287e2c3a5601b28499da705106

WHat do you think?

**Review by mpaulucci — APPROVED** [review]
