### PR TITLE
fix(l2): seal a batch in a single DB transaction 

### LINKED ISSUE #3546: L2: rollup store should seal a batch in a single DB transaction
The function `seal_batch` in `crates/l2/storage/src/store.rs` performs multiple DB operations not in a single DB tx this can lead to a DB with a batch with an inconsistent state

Some logs that can be related to this problem

```
Jul 07 17:47:35 l2-gpu-2 ethrex[312274]: 2025-07-07T20:47:35.546937Z ERROR ethrex_l2::sequencer::block_producer: Block Producer Error: Block Producer failed because of a rollup store error: Limbo Query error: SQLite failure: `cannot start a transaction within a transaction`

```

The solution would be to move `seal_batch` to a function of the `StoreEngineRollup` trait so that every db implementation can begin and end the transaction inside it

### PR DESCRIPTION
**Pull request by LeanSerra**
**Motivation**

When deploying ethrex L2 some errors came up that are related to the seal_batch process not being done in a single DB transaction.

**Description**

- Move seal_batch to the `StoreEngineRollup` trait
- For sql rollup store engine
   - Wrap all the DB write functions from the trait with a <name>_in_tx that gets as an input an Option<Transaction> in case the transaction is Some then it uses the existing transaction, and does not commit. If its None it creates a new transaction and commits at the end of the function.
   - Modify the `SQLStore` struct to hold two instances of `Connection` one for reads and one for writes, the write connection is protected by a Mutex to enforce a maximum of 1 to prevent this error:
      ```
      failed because of a rollup store error: Limbo Query error: SQLite failure: `cannot start a transaction within a transaction`
      ``` 
   - Use `PRAGMA journal_mode=WAL` for [better concurrency](https://sqlite.org/wal.html#concurrency)
- For `libmdbx` , `redb` and `in-memory`
   - Implement the `seal_batch` function 
- Refactor: remove all the functions that were exposed by `store.rs` and were only part of seal_batch to prevent its usage outside of batch sealing.

Closes #3546

### CODE REVIEW

File: crates/l2/storage/src/store_db/libmdbx.rs [hunk 1]
```diff
@@ -381,6 +321,67 @@ impl StoreEngineRollup for Store {
         txn.commit().map_err(RollupStoreError::LibmdbxError)?;
         Ok(())
     }
+
+    async fn seal_batch(&self, batch: Batch) -> Result<(), RollupStoreError> {
+        let blocks: Vec<u64> = (batch.first_block..=batch.last_block).collect();
+        let db = self.db.clone();
+        tokio::task::spawn_blocking(move || {
```
Comment (fedacking) [inline crates/l2/storage/src/store_db/libmdbx.rs:328]: We should probably use spawned here, the RT module reexports spawn_blocking

File: crates/l2/storage/src/store_db/sql.rs [hunk 2]
```diff
@@ -42,20 +48,36 @@ impl SQLStore {
...
-            let conn = db.connect()?;
-            let store = SQLStore { conn };
+            let write_conn = db.connect()?;
+            // From libsql documentation:
+            // Newly created connections currently have a default busy timeout of
+            // 5000ms, but this may be subject to change.
+            write_conn.busy_timeout(Duration::from_millis(5000))?;
+            let store = SQLStore {
+                read_conn: db.connect()?,
+                write_conn: Arc::new(Mutex::new(db.connect()?)),
```
Comment (ManuelBilbao) [inline crates/l2/storage/src/store_db/sql.rs]: Shouldn't this be `Arc::new(Mutex::new(write_conn))`?

File: crates/l2/storage/src/store_db/sql.rs [hunk 3]
```diff
@@ -42,20 +48,36 @@ impl SQLStore {
     pub fn new(path: &str) -> Result<Self, RollupStoreError> {
         futures::executor::block_on(async {
             let db = Builder::new_local(path).build().await?;
-            let conn = db.connect()?;
-            let store = SQLStore { conn };
+            let write_conn = db.connect()?;
+            // From libsql documentation:
+            // Newly created connections currently have a default busy timeout of
+            // 5000ms, but this may be subject to change.
+            write_conn.busy_timeout(Duration::from_millis(5000))?;
```
Comment (ManuelBilbao) [inline crates/l2/storage/src/store_db/sql.rs:55]: Is this statement needed then?

File: crates/l2/storage/src/store_db/sql.rs (hunk 2 above)
Comment (LeanSerra) [reply crates/l2/storage/src/store_db/sql.rs]: Nice catch! [8308285](https://github.com/lambdaclass/ethrex/pull/3554/commits/830828541f32172919555e1ed00d02f8d35cd636)

File: crates/l2/storage/src/store_db/sql.rs (hunk 3 above)
Comment (LeanSerra) [reply crates/l2/storage/src/store_db/sql.rs:55]: Right now it isn't but I was doing some experiments with changing this value and it broke things. I don't want an update to the crate version to modify the default value and breaking things without us knowing why.

File: crates/l2/storage/src/store_db/libmdbx.rs (hunk 1 above)
Comment (LeanSerra) [reply crates/l2/storage/src/store_db/libmdbx.rs:328]: I think it's better if we open an issue to tackle all the occurrences of this in the whole repo as there are a bunch of them most of them in the `crates/storage/storage_db` module that is outside of the scope of this PR.

File: crates/l2/storage/src/store_db/sql.rs (hunk 3 above)
Comment (ManuelBilbao) [reply crates/l2/storage/src/store_db/sql.rs:55]: Makes sense

**Review by ManuelBilbao — APPROVED** [review]
