### PR TITLE
fix(l1): commit forkchoice update in a single db tx

### LINKED ISSUE #3887: L2: rare "nonce too low" error in integration tests
In rare occasions a transaction fails with
```
Error: SendRawTransactionError(RPCError("Invalid params: Nonce for account too low"))
```
In #3851 we fixed a gas limit error that occurred in some runs, here the flakyness had its origin on the variance of a transaction's gas use, and the estimation was too low in some runs causing a gas limit exceeded error. We noticed the nonce too low error in [this run](https://github.com/lambdaclass/ethrex/actions/runs/16581163685/job/46897338897) of that PR.

In that PR [I added asserts](https://github.com/lambdaclass/ethrex/pull/3851/commits/cf5ed74810de5f893a67919f8e244b78476e3c59) to check all transaction receipts' status to be true, and some failed. Maybe that would be related to this error.

### PR DESCRIPTION
**Pull request by avilagaston9**
**Motivation**

A bug was found in our L2 integration tests caused by a race condition during the forkchoice update. More context [here](https://github.com/lambdaclass/ethrex/issues/3887).

**Description**
- Creates `forkchoice_update` method in the L1 store to perform all canonical updates and block labeling in a single tx in the db.
- Removes the following `Store` methods:
    - `mark_chain_as_canonical`
    - `update_finalized_block_number`
    - `update_safe_block_number`
    - `update_latest_block_number`
    - `set_canonical_block`
    - `unset_canonical_block`
- Updates the calls to the removed methods to use the new one.

Closes #3887

### CODE REVIEW

File: cmd/ethrex/l2/command.rs [hunk 1]
```diff
@@ -364,7 +366,11 @@ impl Command {
                                 .await
                                 .expect("Error storing batch");
                         }
-                        store.update_latest_block_number(last_block_number).await?;
+                        let Some((last_number, last_hash)) = new_canonical_blocks.pop() else {
+                            info!("No blocks found in blobs directory");
```
Comment (mpaulucci) [inline cmd/ethrex/l2/command.rs]: this seems it could be everything but info: either error, warn, or debug.

Comment (avilagaston9) [reply cmd/ethrex/l2/command.rs]: Right. Changed to return an error [4b35882](https://github.com/lambdaclass/ethrex/pull/3927/commits/4b3588296444b2a3cd898f6fc4d43901591a2891).

**Review by Oppen — APPROVED** [review]

**Comment by avilagaston9** [comment]
In [32de495](https://github.com/lambdaclass/ethrex/pull/3927/commits/32de4954c0c8ce08afe8bc1cb1123092f0e9db22), the PR was updated to resolve conflicts with #3878. We now update the `latest_block_header` cache before performing the `forkchoice_update` in the database and enforce the other methods to check the cache before querying the database.

**Review by ilitteri — APPROVED** [review]
