### PR TITLE
fix(levm): add fork checks for account creation before spurious dragon

### LINKED ISSUE #1955: stStackTests

### PR DESCRIPTION
**Pull request by LeanSerra**
**Motivation**

Spurious Dragon's [EIP-161](https://eips.ethereum.org/EIPS/eip-161) introduced changes regarding account creation cost.

**Description**

This PR introduces the following changes:
- Nonce should be 0 before SpuriousDragon for tx create
- Before SpuriousDragon, don't check transfer value.

Closes #1955 

Co-authored-by: Tomas Fabrizio Orsi <tomas.orsi@lambdaclass.comr>

### CODE REVIEW

File: crates/vm/levm/src/vm.rs [hunk 1]
```diff
@@ -414,7 +414,12 @@ impl VM {
                 return self.handle_create_non_empty_account(&initial_call_frame);
             }
 
-            let created_contract = Account::new(balance, Bytes::new(), 1, HashMap::new());
+            // https://eips.ethereum.org/EIPS/eip-161
+            let created_contract = if self.env.config.fork < Fork::SpuriousDragon {
+                Account::new(balance, Bytes::new(), 0, HashMap::new())
+            } else {
+                Account::new(balance, Bytes::new(), 1, HashMap::new())
+            };
```
Comment (tomip01) [inline crates/vm/levm/src/vm.rs:422]: Lovely!

**Review by lima-limon-inc — APPROVED** [review]
LGTM!

**Comment by lima-limon-inc** [comment]
```let value_to_empty_account = if !(!address_is_empty || !fork < Fork::SpuriousDragon && value_to_transfer.is_zero())```

File: crates/vm/levm/src/gas_cost.rs [hunk 2]
```diff
@@ -849,11 +849,16 @@ pub fn call(
     } else {
         0
     };
-    let value_to_empty_account = if address_is_empty && !value_to_transfer.is_zero() {
+
+    #[allow(clippy::nonminimal_bool)]
```
Comment (lima-limon-inc) [inline crates/vm/levm/src/gas_cost.rs:853]: I introduced this allow here because clippy was suggesting the following:

```rust
let value_to_empty_account = if !(!address_is_empty || !fork < Fork::SpuriousDragon && value_to_transfer.is_zero())
```

I found that to be way harder to understand. If someone can think of a cleaner way, do let me know!!

Thanks in advance.

Comment (lima-limon-inc) [reply crates/vm/levm/src/gas_cost.rs:853]: Plus, its the closest thing (that I can think of) to a direct translation of the EIP.

File: crates/vm/levm/src/gas_cost.rs [hunk 3]
```diff
@@ -857,11 +857,16 @@ pub fn call(
...
+    let value_to_empty_account = if (address_is_empty && fork < Fork::SpuriousDragon)
+        || (address_is_empty && !value_to_transfer.is_zero())
```
Comment (fborello-lambda) [inline crates/vm/levm/src/gas_cost.rs:863]: I would leave the `#[allow(clippy::nonminimal_bool)]` it's more readable in this way

**Review by fborello-lambda — APPROVED** [review]

File: crates/vm/levm/src/gas_cost.rs (hunk 3 above)
Comment (lima-limon-inc) [reply crates/vm/levm/src/gas_cost.rs:863]: Thank you Fede!
