### PR TITLE
fix(l1): fixing transaction spammer delay and nonce error on estimation

### LINKED ISSUE #1080: L1: TXs submitted by the tx_spammer wait until the 90th block to be added
This issue is related to a low gas price when sending the transaction, its apparently caused by an error in the estimation of gas price, the effect is that we don't add the initial transactions generated by the tx_spammer until the 90th block (which are picked up immediatly by geth for example).

Here is an example: 
image

This happens because the default gas price is way lower than the base fee and it takes roughly to the 90th block for it to come down to the 5000 set in the gas price.

### LINKED ISSUE #1081: L1: After an initial correct transaction added by the tx_spammer, subsequent onces report a lower nonce than expected
After the first transactios are picked up by our node, the second batch almost always fail with the following:

```
Vm execution error: Invalid Transaction: nonce 0 too low, expected 1
```

This appears to be related to the pending transactions in the mempool and how right now both the `latest` and `pending` tag as block identifiers resume to the latest block. Previously pending indentifier blocks weren't taken into account, now they are defaulting to the latest. For the Transaction count RPC we need to return the pending transaction nonce when the `pending` tag is used, which implies checking the mempool. This is an assumption, the issue could be at another place altogether so it needs to be investigated and tested.

### LINKED ISSUE #1083: L1: when a correct transaction is added by the tx_spammer and the next one doesn't fail the spammer gets hang
Even when #1081 doesn't happen we still have issues for processing subsequent txs, after the initial addition and without a nonce error the node doesn't add the following ones when setting the spammer to generate more than one tx per block.

The error is the following:
```
Waiting for transactions to be mined failed: context deadline exceeded
```

This appears to be related to how the spammer waits on the transaction receipt, maybe we need to check difference with how geth manage this scenario.

### LINKED ISSUE #1116: L1: Check that the tx spammer could work with the default setting
Right now we were limmiting the tx spammer to less than 20 txs per block, we need to check how it work with the default (100~200txs per block) onces most of the issues are resolved.

Depend on #1080, #1081, #1083

### PR DESCRIPTION
**Pull request by rodrigo-o**
**Motivation**

This PR solves all the issues discovered while starting the tx spammer pointing to our node in the kurtosis setup. Right now it even work with the default parameters (spamming 100~200 tx per block)

**Description**

There were a bunch of issues generating the tx to be both delayed and ultimately stop after the first one, they were the following:
- We didn't had into account the base fee when there were no txs in the blocks we proposed, as happens starting from genesis and being the only one targeted by the spammer. Now we default first to the base fee and then to the min gas limit. This was causing txs to wait until the 90th block to start being added.
- We were not taking into account pending transactions for nonce calculation when the pending tag was sent
  - This was making subsequent transactions for the same account to halt the spammer if some of them were still in the mempool.
- During the simulate tx of estimate gas we were defaulting the nonce to 0 if not provided. This was crashing the spammer on subsequent tx calls for the same account to estimate gas, now we have an Option for the nonce as part of the GenericTransaction.
 
Resolves #1080
Resolves #1081
Resolves #1083
Resolves #1116

### CODE REVIEW

**Comment by rodrigo-o** [comment]
Now the tx spammer is working past the first tx, and it continually send them through a long run as shown below:

image

File: crates/l2/utils/eth_client/mod.rs [hunk 1]
```diff
@@ -147,7 +147,7 @@ impl EthClient {
             "to": format!("{to:#x}"),
             "input": format!("{:#x}", transaction.input),
             "from": format!("{:#x}", transaction.from),
-            "nonce": format!("{:#x}", transaction.nonce),
+            "nonce": format!("{:#x}", transaction.nonce.unwrap_or_default()),
```
Comment (rodrigo-o) [inline crates/l2/utils/eth_client/mod.rs:150]: This needs to be set just if provided, I'll make the change.

Comment (rodrigo-o) [reply crates/l2/utils/eth_client/mod.rs:174]: Done!

File: test_data/el-stability-check.yml [hunk 2]
```diff
@@ -24,7 +24,7 @@ tasks:
 
 - name: run_task_matrix
   title: "Check block proposals from all client pairs"
-  timeout: 3m
+  timeout: 4m
```
Comment (rodrigo-o) [inline test_data/el-stability-check.yml:27]: I saw a couple of assertoor checks failing due to the 3m timeout (less than 2-3%). Just rerunning the job solves the issue, just in case I raised the timeout, it may be cause by another issues and it still happens will be worth checking it out.

File: test_data/network_params.yaml [hunk 3]
```diff
@@ -22,4 +22,4 @@ assertoor_params:
   tests:
     - 'https://raw.githubusercontent.com/lambdaclass/lambda_ethereum_rust/refs/heads/main/test_data/el-stability-check.yml'
 tx_spammer_params:
-  tx_spammer_extra_args: ["--accounts=10", --txcount=10]
+  tx_spammer_extra_args: [--accounts=7, --txcount=7]
```
Comment (fkrause98) [inline test_data/network_params.yaml:25]: Missing a new line here

File: crates/blockchain/mempool.rs [hunk 4]
```diff
@@ -103,6 +103,19 @@ pub fn remove_transaction(hash: &H256, store: &Store) -> Result<(), StoreError>
     store.remove_transaction_from_pool(hash)
 }
 
+pub fn get_nonce(address: &Address, store: &Store) -> Result<Option<u64>, MempoolError> {
+    let pending_filter = PendingTxFilter {
+        ..Default::default()
+    };
+
+    let pending_txs = filter_transactions(&pending_filter, store)?;
+    let empty_vec = vec![];
```
Comment (fkrause98) [inline crates/blockchain/mempool.rs:112]: Nit:
Here I think it would be better to avoid the vec allocation and do:
```rust
let nonce =  match pending_txs.get(address) { 
   Some(txs) => txs.last().map(|tx| tx.nonce() + 1),
   None => None
}
```

File: crates/networking/rpc/eth/transaction.rs [hunk 5]
```diff
@@ -436,15 +436,27 @@ impl RpcHandler for EstimateGasRequest {
             // Block not found
             _ => return Ok(Value::Null),
         };
+
+        let transaction = if self.transaction.nonce.is_none() {
```
Comment (fkrause98) [inline crates/networking/rpc/eth/transaction.rs:440]: Nit: It's more idiomatic to use a match, but there's nothing wrong with this if.

**Review by fkrause98 — APPROVED** [review]

File: crates/blockchain/mempool.rs (hunk 4 above)
Comment (rodrigo-o) [reply crates/blockchain/mempool.rs:112]: Totally agree!

File: crates/networking/rpc/eth/transaction.rs (hunk 5 above)
Comment (rodrigo-o) [reply crates/networking/rpc/eth/transaction.rs:440]: Which makes sense, I'll stick to the more idiomatic way!

File: crates/blockchain/mempool.rs [hunk 6]
```diff
@@ -103,6 +103,19 @@ pub fn remove_transaction(hash: &H256, store: &Store) -> Result<(), StoreError>
     store.remove_transaction_from_pool(hash)
 }
 
+pub fn get_nonce(address: &Address, store: &Store) -> Result<Option<u64>, MempoolError> {
+    let pending_filter = PendingTxFilter {
+        ..Default::default()
```
[the remark this answers is not in the document]
Comment (rodrigo-o) [reply crates/blockchain/mempool.rs:108]: Sure! I'll set it explicitly!

[the remark this answers is not in the document]
Comment (rodrigo-o) [reply crates/blockchain/mempool.rs]: Done!

File: test_data/network_params.yaml (hunk 3 above)
Comment (rodrigo-o) [reply test_data/network_params.yaml]: Added!

File: crates/blockchain/mempool.rs (hunk 4 above)
Comment (rodrigo-o) [reply crates/blockchain/mempool.rs]: Done!

File: crates/networking/rpc/eth/transaction.rs (hunk 5 above)
Comment (rodrigo-o) [reply crates/networking/rpc/eth/transaction.rs]: Done!

File: test_data/network_params.yaml (hunk 3 above)
[the remark this answers is not in the document]
Comment (rodrigo-o) [reply test_data/network_params.yaml]: I made a new test right now without any params (which defaults to 2 tx per 100 accounts per block) and it is working without issues. The instability I noticed before may be part of an initial test where the pending nonce weren't calculated correctly. I'll run some more test and remove this params altogether if they are not needed anymore.

[the remark this answers is not in the document]
Comment (rodrigo-o) [reply test_data/network_params.yaml]: Assertoor test ran without issues, I'll submit this changes.

**Comment by rodrigo-o** [comment]
Now the tx spammer works as expected by default with the 100tx per block:

image

File: crates/networking/rpc/eth/account.rs [hunk 7]
```diff
@@ -159,15 +160,32 @@ impl RpcHandler for GetTransactionCountRequest {
             self.address, self.block
         );
 
-        let Some(block_number) = self.block.resolve_block_number(&context.storage)? else {
-            return serde_json::to_value("0x0")
-                .map_err(|error| RpcErr::Internal(error.to_string()));
+        let has_pending_tag = matches!(
```
Comment (mpaulucci) [inline crates/networking/rpc/eth/account.rs:163]: I think you can do something like https://github.com/lambdaclass/lambda_ethereum_rust/blob/134bc9469ac5e5eda46c6c287e5a3d970044e766/crates/networking/rpc/types/block_identifier.rs#L109 because of https://github.com/lambdaclass/lambda_ethereum_rust/blob/134bc9469ac5e5eda46c6c287e5a3d970044e766/crates/networking/rpc/types/block_identifier.rs#L152-L159

Comment (rodrigo-o) [reply crates/networking/rpc/eth/account.rs:163]: I'll check it rn, great catch!
