### PR TITLE
fix(core): remove hardcoded max_fee_per_gas & max_priority_fee_per_gas

### LINKED ISSUE #2795: Remove hardcoded values when creating transactions
There are many parts of the codebase that have hardcoded `max_fee_per_gas` and `max_priority_fee_per_gas`. Hardcoded values should be replaced by estimated/calculated values

### PR DESCRIPTION
**Pull request by LeanSerra**
**Motivation**

This values should be set dinmically 

**Description**

- Add `get_max_priority_fee` to `EthClient` to call `eth_maxPriorityFeePerGas` endpoint
- When calling `build_xxxx_transaction` without `max_fee_per_gas` override
   - Set it to the result of calling `eth_gasPrice` endpoint
- When calling `build_xxxx_transaction` without `max_fee_per_gas` override
  - Set it to the result of calling `eth_maxPriorityFeePerGas`
     - Because `eth_maxPriorityFeePerGas` in Ethrex can return null if it does set it to the result of calling `eth_gasPrice`

Closes #2795

### CODE REVIEW

File: crates/networking/rpc/clients/eth/mod.rs [hunk 1]
```diff
@@ -787,16 +806,14 @@ impl EthClient {
...
-            } else {
-                get_gas_price = self.get_gas_price().await?.try_into().map_err(|_| {
-                    EthClientError::Custom("Failed at gas_price.try_into()".to_owned())
-                })?;
-
-                get_gas_price
-            },
-            max_priority_fee_per_gas: overrides.max_priority_fee_per_gas.unwrap_or(get_gas_price),
+            max_fee_per_gas: self
+                .get_fee_from_override_or_get_gas_price(overrides.max_priority_fee_per_gas)
```
Comment (tomip01) [inline crates/networking/rpc/clients/eth/mod.rs:810]: Shouldn't it be: `.get_fee_from_override_or_get_gas_price(overrides.max_fee_per_gas)
` ?

Comment (LeanSerra) [reply crates/networking/rpc/clients/eth/mod.rs]: Fixed [here](https://github.com/lambdaclass/ethrex/pull/2803/commits/3b5d8af46594bf79f383f32a2accd89b58194114)

**Review by tomip01 — APPROVED** [review]

**Review by ilitteri — APPROVED** [review]
