### PR TITLE
fix(levm): opcode SIGNEXTEND

### LINKED ISSUE #1386: fix(levm): opcode SIGEXTEND
- The function could early return if the byte size from the stack is ≥ to 31, the `try_into()` check for the `sign_bit_index` can be removed with this change.
- Unecessary `&` when the value is positive, maybe we should early return the original value when the sign bit is positive. The `U256::bit(idx)` function can panic, maybe add check to ensure we are inside the bounds of `U256`.

### PR DESCRIPTION
**Pull request by damiramirez**
**Motivation**

Do some refactoring and fixes to the `signextend` opcode.

**Description**

- Add early return in case `byte_size` is > 31. This means the value was too large to extend.
- Check that `sign_bit_index` cannot be >= 256. Avoid panic by using `U256::bit()`.
- When we remove the mask in `value_to_extend & sign_bit_mask`, it decreases to 17/19 in Arithmetic EF Tests.

Closes #1386

### CODE REVIEW

File: crates/vm/levm/src/opcode_handlers/arithmetic.rs [hunk 1]
```diff
@@ -220,45 +220,36 @@ impl VM {
         let byte_size = current_call_frame.stack.pop()?;
```
Comment (JereSalo) [inline crates/vm/levm/src/opcode_handlers/arithmetic.rs:220]: I know this is not from this PR but I'd change the `byte_size` name for a more accurate one, like `byte_size_minus_one` or something like that. Just to avoid misunderstandings, because someone may think that `byte_size` represents the size in bytes of the value sent as input when it is actually `byte size - 1`.

File: crates/vm/levm/src/opcode_handlers/arithmetic.rs [hunk 2]
```diff
@@ -220,45 +220,36 @@ impl VM {
...
         let value_to_extend = current_call_frame.stack.pop()?;
 
+        if byte_size >= U256::from(31) {
```
Comment (JereSalo) [inline crates/vm/levm/src/opcode_handlers/arithmetic.rs:223]:
```suggestion
        if byte_size > U256::from(31) {
```

File: crates/vm/levm/src/opcode_handlers/arithmetic.rs [hunk 3]
```diff
@@ -220,45 +220,36 @@ impl VM {
...
-                // this means the value_to_extend was too big to extend, so remains the same.
-                // Maybe this verification could be done before in this function
-                current_call_frame.stack.push(value_to_extend)?;
-                return Ok(OpcodeSuccess::Continue);
-            }
-        };
 
-        let is_negative = value_to_extend.bit(sign_bit_index);
+        let shifted_value = checked_shift_right(value_to_extend, sign_bit_index)?;
+        let is_negative = shifted_value & U256::one() == U256::one();
```
Comment (JereSalo) [inline crates/vm/levm/src/opcode_handlers/arithmetic.rs:239]:
```suggestion

```

File: crates/vm/levm/src/opcode_handlers/arithmetic.rs [hunk 4]
```diff
@@ -220,45 +220,36 @@ impl VM {
...
-            Err(_) => {
-                // this means the value_to_extend was too big to extend, so remains the same.
-                // Maybe this verification could be done before in this function
-                current_call_frame.stack.push(value_to_extend)?;
-                return Ok(OpcodeSuccess::Continue);
-            }
-        };
 
-        let is_negative = value_to_extend.bit(sign_bit_index);
+        let shifted_value = checked_shift_right(value_to_extend, sign_bit_index)?;
```
Comment (JereSalo) [inline crates/vm/levm/src/opcode_handlers/arithmetic.rs:238]:
```suggestion
        let sign_bit = checked_shift_right(value_to_extend, sign_bit_index)?;
```

File: crates/vm/levm/src/opcode_handlers/arithmetic.rs [hunk 5]
```diff
@@ -220,45 +220,36 @@ impl VM {
...
+        let is_negative = shifted_value & U256::one() == U256::one();
 
-        let sign_bit_mask = checked_shift_left(U256::one(), U256::from(sign_bit_index))?
+        if !is_negative {
+            current_call_frame.stack.push(value_to_extend)?;
+            return Ok(OpcodeSuccess::Continue);
+        };
```
Comment (JereSalo) [inline crates/vm/levm/src/opcode_handlers/arithmetic.rs:244]:
```suggestion
        if sign_bit.is_zero() {
            current_call_frame.stack.push(value_to_extend)?;
            return Ok(OpcodeSuccess::Continue);
        };
```

File: crates/vm/levm/src/opcode_handlers/arithmetic.rs (hunk 2 above)
Comment (JereSalo) [reply crates/vm/levm/src/opcode_handlers/arithmetic.rs:223]: This probably doesn't change much but I saw it differed from the [execution specs](https://ethereum.github.io/execution-specs/src/ethereum/cancun/vm/instructions/arithmetic.py.html)

Comment (damiramirez) [reply crates/vm/levm/src/opcode_handlers/arithmetic.rs]: [Done!](https://github.com/lambdaclass/ethrex/pull/1408/commits/c7bed6c3a2f7385e833a83a20038d7a7e4fe34ec) I didn't know that page, ty for that!

File: crates/vm/levm/src/opcode_handlers/arithmetic.rs (hunk 1 above)
Comment (damiramirez) [reply crates/vm/levm/src/opcode_handlers/arithmetic.rs]: [Done! ](https://github.com/lambdaclass/ethrex/pull/1408/commits/c7bed6c3a2f7385e833a83a20038d7a7e4fe34ec)

File: crates/vm/levm/src/opcode_handlers/arithmetic.rs (hunk 3 above)
Comment (damiramirez) [reply crates/vm/levm/src/opcode_handlers/arithmetic.rs]: [Removed](https://github.com/lambdaclass/ethrex/pull/1408/commits/c7bed6c3a2f7385e833a83a20038d7a7e4fe34ec)

File: crates/vm/levm/src/opcode_handlers/arithmetic.rs (hunk 4 above)
Comment (damiramirez) [reply crates/vm/levm/src/opcode_handlers/arithmetic.rs]: Sounds good, [changed!](https://github.com/lambdaclass/ethrex/pull/1408/commits/c7bed6c3a2f7385e833a83a20038d7a7e4fe34ec)

File: crates/vm/levm/src/opcode_handlers/arithmetic.rs (hunk 5 above)
Comment (damiramirez) [reply crates/vm/levm/src/opcode_handlers/arithmetic.rs]: Thx for the feedback! [Done](https://github.com/lambdaclass/ethrex/pull/1408/commits/c7bed6c3a2f7385e833a83a20038d7a7e4fe34ec).

**Review by JereSalo — CHANGES_REQUESTED** [review]

File: crates/vm/levm/src/opcode_handlers/arithmetic.rs [hunk 6]
```diff
@@ -224,43 +224,37 @@ impl VM {
...
-                current_call_frame.stack.push(value_to_extend)?;
-                return Ok(OpcodeSuccess::Continue);
-            }
-        };
 
-        let is_negative = value_to_extend.bit(sign_bit_index);
+        if sign_bit_index >= U256::from(256) {
+            current_call_frame.stack.push(value_to_extend)?;
+            return Ok(OpcodeSuccess::Continue);
+        }
```
[the remark this answers is not in the document]
Comment (damiramirez) [reply crates/vm/levm/src/opcode_handlers/arithmetic.rs:248]: Removed!

File: crates/vm/levm/src/opcode_handlers/arithmetic.rs [hunk 7]
```diff
@@ -224,43 +224,37 @@ impl VM {
...
 
-        let sign_bit_mask = checked_shift_left(U256::one(), U256::from(sign_bit_index))?
+        let is_negative = value_to_extend.bit(sign_bit_index.as_usize());
```
[the remark this answers is not in the document]
Comment (damiramirez) [reply crates/vm/levm/src/opcode_handlers/arithmetic.rs:250]: No problem Jere, you are right! I went back to the previous implementation and add `shifted_value & U256::one();`  I had forgotten to do that before and that is why the tests failed.
```rust
let shifted_value = checked_shift_right(value_to_extend, sign_bit_index)?;
let sign_bit = shifted_value & U256::one();
```
Then check if the bit value is 0 and apply the mask accordingly. What do you think about this change?

[the remark this answers is not in the document]
Comment (damiramirez) [reply crates/vm/levm/src/opcode_handlers/arithmetic.rs]: You can check the change here [3b41822](https://github.com/lambdaclass/ethrex/pull/1408/commits/3b41822c4be5b9885b31204e1f6a5b62e4016dd7)

**Review by JereSalo — APPROVED** [review]
LGTM
