### PR TITLE
fix(core): avoid runtime creation errors in storage test

### LINKED ISSUE #2820: L1: Thread Panics while running testing on Storage Crate
While running the `crates/storage` tests with `cargo test --features libmdbx -- --nocapture` some tests panic.

```
thread 'store::tests::test_in_memory_store' panicked at /Users/franciscogauna/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.44.2/src/runtime/scheduler/multi_thread/mod.rs:86:9:
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test store::tests::test_in_memory_store ... ok
thread 'store::tests::test_libmdbx_store' panicked at /Users/franciscogauna/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.44.2/src/runtime/scheduler/multi_thread/mod.rs:86:9:
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
```

### PR DESCRIPTION
**Pull request by fmoletta**
**Motivation**
As reported by #2820, when running `cargo test --features libmdbx -- --nocapture` on the storage crate, all tests pass, but a panic message is shown indicating that runtime creation failed (`Cannot start a runtime from within a runtime`). This is due to the test checking that initializing the store with a different genesis panics using `catch_unwind` to catch the panic. This worked fine when the `store` api was sync, but when it was moved to async in order to call the async method a new runtime has to be created in order to `block_on` it during catch_unwind call. This resulted in a runtime being created inside the `tokio::test` runtime, leading to the resulting panic.
This PR removes this runtime, instead relying on `tokio::spawn` and its resulting `JoinError` to check for panics. As the `JoinError` will record panics, we can not only check that the call panicked, but also make assertions on the panic message itself. Unluckily, we cannot prevent the panic message from also being shown via stderr when running with `nocapture`,  like this:
Captura de pantalla 2025-06-02 a la(s) 17 27 41
Even if the panic message is shown, this doesn't stop the test and its later assertion (you can check for yourself that changing the expected panic message results in the test failing)

This PR also fixes the Tokio dev dependency import that was changed by #2981 

**Description**
* Remove Tokio runtime creation from `test_genesis_block`
* Check the panic message returned in `test_genesis_block`
* Fix Tokio dev dependency in storage crate
* (Misc) Use a constant for the panic message when importing a different genesis

Closes #2820

### CODE REVIEW

File: crates/storage/store.rs [hunk 1]
```diff
@@ -470,7 +472,7 @@ impl Store {
                 info!("Received genesis file matching a previously stored one, nothing to do");
                 return Ok(());
             } else {
-                panic!("Tried to run genesis twice with different blocks. Try again after clearing the database. If you're running ethrex as an Ethereum client, run cargo run --release --bin ethrex -- removedb; if you're running ethrex as an L2 run make rm-db-l1 rm-db-l2");
+                panic!("{}", GENESIS_DIFF_PANIC_MESSAGE);
```
Comment (fedacking) [inline crates/storage/store.rs]: Mini suggestion
```suggestion
                panic!("{GENESIS_DIFF_PANIC_MESSAGE}");
```

File: crates/storage/store.rs [hunk 2]
```diff
@@ -470,7 +472,7 @@ impl Store {
                 info!("Received genesis file matching a previously stored one, nothing to do");
                 return Ok(());
             } else {
-                panic!("Tried to run genesis twice with different blocks. Try again after clearing the database. If you're running ethrex as an Ethereum client, run cargo run --release --bin ethrex -- removedb; if you're running ethrex as an L2 run make rm-db-l1 rm-db-l2");
+                panic!("{GENESIS_DIFF_PANIC_MESSAGE}");
```
Comment (MegaRedHand) [inline crates/storage/store.rs:475]: What's the reason for panicking instead of returning an error?

**Review by MegaRedHand — APPROVED** [review]
