### PR TITLE
chore(l1): fix contract deployment tests from EIP-7002

### LINKED ISSUE #2598: LEVM: Fix prague/eip7002_el_triggerable_withdrawals/contract_deployment
**Context**

After updating the execution spec tests to version 4.3.0, new tests failed.

**Description**

Fix the tests from `prague/eip7002_el_triggerable_withdrawals/contract_deployment/system_contract_deplyment.json` that are currently being skipped

### PR DESCRIPTION
**Pull request by DiegoCivi**
**Motivation**

On #2586 new tests were added and some of them failed on LEVM and REVM.

**Description**

8 new tests are now working and dont need to be skipped in each of the VMs. The tests were failing because we were not checking if the bytecode of the system contracts that the EIPs ([7002](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7002.md#empty-code-failure) and [7251](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7251.md)) define were empty or not. And also because the we were not handling the case were the system calls revert, leading to an invalidate block.

Closes #2598

### CODE REVIEW

File: crates/vm/backends/levm/mod.rs [hunk 1]
```diff
@@ -322,6 +323,22 @@ impl LEVM {
         )
         .ok()?;
 
+        // According to EIP-7002 we need to check if the WITHDRAWAL_REQUEST_PREDEPLOY_ADDRESS
+        // has any code after being deployed. If not, the whole block becomes invalid.
+        let acc = db
```
Comment (JereSalo) [inline crates/vm/backends/levm/mod.rs:328]: I know this is usually in the cache but I'd use `db.get_account()` or `db.get_account_info()` (whichever exists, after #2629 it will be `db.get_account()`) instead just to be more careful.

File: crates/vm/backends/levm/mod.rs [hunk 2]
```diff
@@ -322,6 +323,22 @@ impl LEVM {
...
+            .cache
+            .get(&*WITHDRAWAL_REQUEST_PREDEPLOY_ADDRESS)
+            .unwrap();
+        if code_hash(&acc.info.bytecode) == EMPTY_CODE_HASH {
+            return Some(ExecutionReport {
```
Comment (JereSalo) [inline crates/vm/backends/levm/mod.rs:333]: This is a little bit hacky. It's best to just return an `EvmError` rather than making up an `ExecutionReport`

File: crates/vm/backends/levm/mod.rs [hunk 3]
```diff
@@ -340,6 +357,22 @@ impl LEVM {
...
+                result: TxResult::Revert(VMError::FatalError),
+                gas_used: 0,
+                gas_refunded: 0,
+                output: Bytes::new(),
+                logs: vec![],
+            });
+        }
```
Comment (JereSalo) [inline crates/vm/backends/levm/mod.rs:374]: ditto for these changes

**Review by JereSalo — CHANGES_REQUESTED** [review]
Good job identifying this!
I wanted to suggest a change if possible:
- I'd actually make `read_withdrawal_requests()` and `dequeue_consolidation_requests()` return a `Result<Option<ExecutionReport>, EvmError>`, so that when calling them you can use `?` for propagating the errors. I think all the code will look cleaner.

File: crates/vm/backends/levm/mod.rs (hunk 3 above)
Comment (DiegoCivi) [reply crates/vm/backends/levm/mod.rs]: Done!

**Review by JereSalo — CHANGES_REQUESTED** [review]
Nice! It's looking better now.

I think there may be a mistake with `ExecutionReport` handling though.

The case in which `read_withdrawals_requests` or `dequeue_consolidation_requests` return an `ExecutionReport` with a transaction that reverts doesn't exist in this code, because the `match report.result` in those functions makes sure to return `None` if Tx reverted.
I would personally remove that `match` and return a `Result<ExecutionReport, EvmError>` instead of `Result<Option<ExecutionReport>, EvmError>`.

Then, we have to investigate what the correct behavior is when those kinds of transactions revert. Do we leave the data empty or do we return an error? Which one is correct? Are there any tests that test that behavior?

**Comment by DiegoCivi** [comment]
You are right!

Regarding what should we do if the transaction reverts, the [EIP-7002](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7002.md#system-call-failure) says:

> Although the likelihood of a failed system call to WITHDRAWAL_REQUEST_PREDEPLOY_ADDRESS is extremely low, the behavior in such cases is well-defined: the block is marked as invalid. However, if the failure results from processing a transaction within the block, the public mempool may still retain the transaction even after the block is invalidated. This can result in the offending transaction being included again, potentially causing one or more subsequent slots to go without valid blocks. To mitigate this, we recommend that the block producer implementation shuffle their transaction set to increase the chances of producing a valid block, without the offending transaction(s). The block producer implementation and/or the mempool should be aware of system call failure scenarios to enable this behavior.

[EIP-7251](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7251.md#system-call-failure) handles this the same way for the `CONSOLIDATION_REQUEST_PREDEPLOY_ADDRESS`.
So I guess that if the transaction fails, we should return an error. However, should I also implement the transaction shuffle? Or is it out of this PRs scope? (Maybe it is already implemented, but I could not find it)

About the tests, there is one that to my understanding tests a revert when using the system contract (`tests/prague/eip7002_el_triggerable_withdrawals/test_modified_withdrawal_contract.py::test_system_contract_errors[fork_Prague-blockchain_test-system_contract_reverts-system_contract_0x00000961ef480eb55e80d19ad83579a64c007002]`) and it expects a [BlockException](https://eest.ethereum.org/main/library/ethereum_test_exceptions/#ethereum_test_exceptions.BlockException) which indicates that the block should be invalid.

**Comment by DiegoCivi** [comment]
In the meantime i was debugging some more tests, and what was talked about before solves them. By changing the  `Result<Option<ExecutionReport>, EvmError>` to a `Result<ExecutionReport, EvmError>` and returning an error when we have a transaction revert the block execution fails and 4 new tests get fixed.

File: crates/vm/backends/levm/mod.rs [hunk 4]
```diff
@@ -300,37 +301,53 @@ impl LEVM {
...
             *SYSTEM_ADDRESS,
-        )
-        .ok()?;
+        )?;
+
+        // According to EIP-7002 we need to check if the WITHDRAWAL_REQUEST_PREDEPLOY_ADDRESS
+        // has any code after being deployed. If not, the whole block becomes invalid.
+        // https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7002.md
+        let account = db.get_account(*WITHDRAWAL_REQUEST_PREDEPLOY_ADDRESS)?;
+        if account.info.code_hash == EMPTY_CODE_HASH {
```
Comment (JereSalo) [inline crates/vm/backends/levm/mod.rs:317]:
```suggestion
        if !account.has_code() {
```

File: crates/vm/backends/levm/mod.rs [hunk 5]
```diff
@@ -300,37 +301,53 @@ impl LEVM {
...
+            return Err(EvmError::Custom("BlockException.SYSTEM_CONTRACT_EMPTY: WITHDRAWAL_REQUEST_PREDEPLOY_ADDRESS has no code after deployment".to_string()));
+        }
 
         match report.result {
-            TxResult::Success => Some(report),
-            _ => None,
+            TxResult::Success => Ok(report),
+            // EIP-7002 specifies that a failed system call invalidates the entire block.
+            TxResult::Revert(vm_error) => Err(EvmError::from(vm_error)),
```
Comment (JereSalo) [inline crates/vm/backends/levm/mod.rs:324]:
```suggestion
            TxResult::Revert(vm_error) => Err(EvmError::Custom(format!(
                "Read withdrawals request shouldn't revert. VM Error: {}",
                vm_error
            ))),
```
This is just a suggestion of a possible change in the return of the error. The reason behind it is that I think that it may not be enough information just to return the `vm_error` without any explanation around it.
I would just add a little bit of context saying what actually happened, that a system call shouldn't revert or something like that.
Let me know what you think and feel free to change it for what you think is best or keep it as it is if you think is more correct

File: crates/vm/backends/levm/mod.rs [hunk 6]
```diff
@@ -300,37 +301,53 @@ impl LEVM {
...
             *SYSTEM_ADDRESS,
-        )
-        .ok()?;
+        )?;
+
+        // According to EIP-7251 we need to check if the CONSOLIDATION_REQUEST_PREDEPLOY_ADDRESS
+        // has any code after being deployed. If not, the whole block becomes invalid.
+        // https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7251.md
+        let acc = db.get_account(*CONSOLIDATION_REQUEST_PREDEPLOY_ADDRESS)?;
+        if acc.info.code_hash == EMPTY_CODE_HASH {
```
Comment (JereSalo) [inline crates/vm/backends/levm/mod.rs:343]:
```suggestion
        if !acc.has_code() {
```

File: crates/vm/backends/levm/mod.rs [hunk 7]
```diff
@@ -300,37 +301,53 @@ impl LEVM {
...
+            return Err(EvmError::Custom("BlockException.SYSTEM_CONTRACT_EMPTY: CONSOLIDATION_REQUEST_PREDEPLOY_ADDRESS has no code after deployment".to_string()));
+        }
 
         match report.result {
-            TxResult::Success => Some(report),
-            _ => None,
+            TxResult::Success => Ok(report),
+            // EIP-7251 specifies that a failed system call invalidates the entire block.
+            TxResult::Revert(vm_error) => Err(EvmError::from(vm_error)),
```
Comment (JereSalo) [inline crates/vm/backends/levm/mod.rs:350]: ditto

File: crates/vm/backends/revm/mod.rs [hunk 8]
```diff
@@ -185,42 +186,104 @@ impl REVM {
...
+            EvmState::Store(db) => {
+                let mut evm = Evm::builder().with_db(db).build();
+                let evm_db = evm.db_mut();
+                evm_db.basic(revm_addr)?
+            }
+            EvmState::Execution(cache_db) => {
+                let mut evm = Evm::builder().with_db(cache_db).build();
+                let evm_cache_db = evm.db_mut();
+                evm_cache_db.basic(revm_addr)?
+            }
```
Comment (JereSalo) [inline crates/vm/backends/revm/mod.rs:204]: Quick question on this. Why was it necessary to build the evm to get data from the db? Wasn't it possible to just do `db.basic(revm_addr)`?
If it is not possible I'd add a simple comment explaining why because this may generate confusion

**Review by JereSalo — COMMENTED** [review]
This is looking very good. Left some simple comments but nothing too important.

File: cmd/ef_tests/blockchain/tests/prague.rs [hunk 9]
```diff
@@ -76,6 +60,10 @@ const SKIPPED_TESTS_LEVM: [&str; 46] = [
 //"tests/prague/eip7702_set_code_tx/test_set_code_txs.py::test_set_code_max_depth_call_stack[fork_Prague-blockchain_test]",
 //"tests/prague/eip7702_set_code_tx/test_set_code_txs_2.py::test_pointer_contract_pointer_loop[fork_Prague-blockchain_test]",
 
+// NOTE: The following test fails because of an OutOfGas error. This happens because it tests a system call to a contract that has a
+// code with a cost of +29 million gas that when is being sumed to the 21k base intrinsic gas it goes over the 30 million limit.
```
[the remark this answers is not in the document]
Comment (DiegoCivi) [reply cmd/ef_tests/blockchain/tests/prague.rs]: Done! [`00d57b5`](https://github.com/lambdaclass/ethrex/pull/2630/commits/00d57b5a3da8f74315c047972538f5b0bcd4fe1c)

File: crates/vm/backends/levm/mod.rs (hunk 4 above)
Comment (DiegoCivi) [reply crates/vm/backends/levm/mod.rs]: I like that, done! [`86bcf0c`](https://github.com/lambdaclass/ethrex/pull/2630/commits/86bcf0c35c4c3ea912b548948b55e7bc0481fc3c)

File: crates/vm/backends/levm/mod.rs (hunk 6 above)
Comment (DiegoCivi) [reply crates/vm/backends/levm/mod.rs]: Done! [`8ef2f95`](https://github.com/lambdaclass/ethrex/pull/2630/commits/8ef2f95ca93150291e66cfc462d7e5d3d9755615)

File: crates/vm/backends/revm/mod.rs (hunk 8 above)
Comment (DiegoCivi) [reply crates/vm/backends/revm/mod.rs]: It was not necessary. Already changed it [`8a09546`](https://github.com/lambdaclass/ethrex/pull/2630/commits/8a0954681710108e3baefb198c0166e99957ebdb)

File: crates/vm/backends/levm/mod.rs (hunk 5 above)
Comment (DiegoCivi) [reply crates/vm/backends/levm/mod.rs]: True, the error should give more context. I changed it here [`2025181`](https://github.com/lambdaclass/ethrex/pull/2630/commits/20251818070e7cb2947df335e6a9f1b5a24b2df8). Let me know what you think about it!

File: crates/vm/backends/levm/mod.rs (hunk 7 above)
Comment (DiegoCivi) [reply crates/vm/backends/levm/mod.rs]: Done!

File: crates/vm/backends/revm/mod.rs (hunk 8 above)
Comment (JereSalo) [reply crates/vm/backends/revm/mod.rs]: nice

File: crates/vm/backends/levm/mod.rs (hunk 5 above)
Comment (JereSalo) [reply crates/vm/backends/levm/mod.rs]: It's perfect

**Review by JereSalo — APPROVED** [review]
nice job!

**Review by mpaulucci — APPROVED** [review]
