### PR TITLE
fix(l1): invalidTXs hive test

### LINKED ISSUE #2726: tests: continue investigating failing hive devp2p eth test `InvalidTxs`
Disclaimer: The main purpose of this issue is not to provide an immediate task but to serve as a reference of what we know until now

The test consists of sending a bunch of invalid transactions to ethrex via `Transactions` rlpx message and making sure our node does not propagate them. We currently invalidate all transactions except for the first once, which should be invalidated due to having a lower nonce. The problem is that the test suite uses current nonce -1 as transaction nonce, which becomes u64::MAX in the transaction (this wrap-around happens in the test code, and not on our side) which is a valid nonce that is higher than the account's nonce and therefore we propagate the transactions.
When comparing the test results to other implementations we got either connection errors or the same error as our implementation. The only implementation I found that passed the hive test was erigon, but upon removing the other invalid transactions from the test the test failed (aka it propagated the invalid nonce transaction).
Some useful links:
DevP2P Spec: https://github.com/ethereum/devp2p/blob/5713591d0366da78a913a811c7502d9ca91d29a8/caps/eth.md?plain=1#L112
Test Code: https://github.com/ethereum/go-ethereum/blob/0db99f4e409b05c109cffac26c15dd641757a3ab/cmd/devp2p/internal/ethtest/suite.go#L531

### PR DESCRIPTION
**Pull request by Mechanix97**
**Motivation**

The InvalidTxs test in hive was failing

**Description**

Changes introduced
- Added more validations to incoming TXs. 128Kb for non contratct creation data limit (not really a spec, but [recommended](https://github.com/ethereum/devp2p/blob/bc76b9809a30e6dc5c8dcda996273f0f9bcf7108/caps/eth.md?plain=1#L180) to avoid ddos). Added cap to the nonce value (shoudn't reach u64::max). Now we check the mempool for getting the pending TXs nonces.
- Fixed ping/pong decoding when empty string received (still valid)
- Avoid broadcasting TXs when there are not valid TXs
- Added the test to the CI again

Closes #2726 & #1139

### CODE REVIEW

File: crates/blockchain/mempool.rs [hunk 1]
```diff
@@ -231,6 +231,20 @@ impl Mempool {
...
+            .transaction_pool
+            .read()
+            .map_err(|error| StoreError::MempoolReadLock(error.to_string()))?;
+
+        let count = pooled_transactions
+            .iter()
+            .filter(|(_, tx)| tx.nonce() == nonce && tx.sender() == sender)
+            .count();
+
+        Ok(count != 0)
```
Comment (ilitteri) [inline crates/blockchain/mempool.rs]: This is a minor detail given that `count` is an unsigned integer, but still, the count must be greater than 0.
```suggestion
        Ok(count > 0)
```

File: crates/blockchain/blockchain.rs [hunk 2]
```diff
@@ -424,6 +425,10 @@ impl Blockchain {
             return Err(MempoolError::TxMaxInitCodeSizeError);
         }
 
+        if !tx.is_contract_creation() && tx.data().len() >= MAX_TRANSACTION_DATA_SIZE {
+            return Err(MempoolError::TxMaxInitCodeSizeError);
```
Comment (ilitteri) [inline crates/blockchain/blockchain.rs]: I don't think this is the right error if the transaction is not a contract creation.

Comment (Mechanix97) [reply crates/blockchain/blockchain.rs]: Done [adfadde](https://github.com/lambdaclass/ethrex/pull/3031/commits/adfadde4b60ce0fdc7ae5069d096b4439080e572)

**Review by ilitteri — APPROVED** [review]

**Review by SDartayet — APPROVED** [review]
LGTM!
