### PR TITLE
fix(l1): when in the VM db, get the block hash using the ancestors

### LINKED ISSUE #2951: Get block (by number) inside vm should return ancestor, not canonical block
See this function: https://github.com/lambdaclass/ethrex/blob/84509b69343181c447065c70c057c8488b606bac/crates/blockchain/vm.rs#L34

In storage, when querying a block by number, we return the `canonical` block. Whereas in the vm, when executing transactions, when we query a block, we want the ancestor of the block which we initialize the vm with https://github.com/lambdaclass/ethrex/blob/84509b69343181c447065c70c057c8488b606bac/crates/blockchain/vm.rs#L16

Normally this isn't a problem, but it might be if the ancestor block is not canonical.

An example of the issue is: https://github.com/lambdaclass/ethrex/issues/2935

Here, since we're using `import` command, we don't set the chain as canoncial until we execute all blocks.

Way to reproduce:
- Export the first 2000 Hoodi blocks to rlp using Geth for example
- Import the 2000 blocks to Ethrex. Block 1579 will fail

### PR DESCRIPTION
**Pull request by Arkenan**
Instead of using the canonical block, look for the ancestor. This might be a costly operation. This solves the issue. The first 11k hoodi blocks are processed correctly in about 15 minutes.

Closes #2951

### CODE REVIEW

File: crates/blockchain/vm.rs [hunk 1]
```diff
@@ -32,13 +33,23 @@ impl VmDatabase for StoreVmDatabase {
...
+                    return Err(EvmError::DB(format!(
+                    "[VM DB] Block number requested {} is higher than the current block number {}",
+                    block_number, ancestor.number
+                )))
+                }
+            }
         }
+
+        Err(EvmError::DB(format!(
+            "[VM DB] Block hash not found for block number {block_number}"
```
[the remark this answers is not in the document]
Comment (Arkenan) [reply crates/blockchain/vm.rs]: Done

File: crates/blockchain/vm.rs [hunk 2]
```diff
@@ -32,13 +33,23 @@ impl VmDatabase for StoreVmDatabase {
     }
 
     fn get_block_hash(&self, block_number: u64) -> Result<H256, EvmError> {
```
Comment (fmoletta) [inline crates/blockchain/vm.rs:35]: Most of the time we will be executing blocks that belong to the canonical chain (aka the ones we get from `forkChoiceUpdate`, `newPayload` & syncing). Wouldn't it be better to first check if the block hash we have is canonical, and if it is then we can use  `get_canonical_block_hash` as the ancestor block will also be canonical. This will save us from having to go through all ancestors on our most relevant use cases

Comment (Arkenan) [reply crates/blockchain/vm.rs:35]: As discussed offline, created an issue for this as there's an async API requirement that needs more discussion: #2990
