### PR TITLE
fix(levm): `codecopy` memory allocation

### LINKED ISSUE #1325: [SECURITY] Non-Compliance : Improper Memory Allocation in CODECOPY
Our team at [FuzzingLabs](https://github.com/FuzzingLabs) has identified a non-compliance issue in the implementation of the [CODECOPY](https://github.com/lambdaclass/ethrex/blob/main/crates/vm/levm/src/opcode_handlers/environment.rs#L212) opcode in `levm`. The issue lies in how `levm` calculates memory allocation during the execution of the opcode. Specifically, the implementation incorrectly bases memory allocation on the length of the bytecode available rather than strictly adhering to the `size` argument provided in the opcode. This results in incorrect behavior for operations like `MSIZE`, which relies on accurate memory allocation.

## Root cause

```rust
// CODECOPY operation
    pub fn op_codecopy(
        &mut self,
        current_call_frame: &mut CallFrame,
    ) -> Result<OpcodeSuccess, VMError> {
        let dest_offset: usize = current_call_frame
            .stack
            .pop()?
            .try_into()
            .map_err(|_| VMError::VeryLargeNumber)?;
        let offset: usize = current_call_frame
            .stack
            .pop()?
            .try_into()
            .map_err(|_| VMError::VeryLargeNumber)?;
        let size: usize = current_call_frame
            .stack
            .pop()?
            .try_into()
            .map_err(|_| VMError::VeryLargeNumber)?;

        let gas_cost =
            gas_cost::codecopy(current_call_frame, size, dest_offset).map_err(VMError::OutOfGas)?;

        self.increase_consumed_gas(current_call_frame, gas_cost)?;

        if size == 0 {
            return Ok(OpcodeSuccess::Continue);
        }

        let bytecode_len = current_call_frame.bytecode.len();
        let code = if offset < bytecode_len {
            current_call_frame.bytecode.slice(
                offset
                    ..(offset.checked_add(size).ok_or(VMError::Internal(
                        InternalError::ArithmeticOperationOverflow,
                    ))?)
                    .min(bytecode_len),
            )
        } else {
            vec![0u8; size].into()
        };

        current_call_frame.memory.store_bytes(dest_offset, &code)?;

        Ok(OpcodeSuccess::Continue)
    }
```

The root cause of the issue lies in the following section of the `op_codecopy` function:

```rust
let bytecode_len = current_call_frame.bytecode.len();
let code = if offset < bytecode_len {
    current_call_frame.bytecode.slice(
        offset
            ..(offset.checked_add(size).ok_or(VMError::Internal(
                InternalError::ArithmeticOperationOverflow,
            ))?)
            .min(bytecode_len),
    )
} else {
    vec![0u8; size].into()
};

current_call_frame.memory.store_bytes(dest_offset, &code)?;
```

Here, the `.min(bytecode_len)` operation limits the range of data copied to the length of the bytecode. While this ensures no out-of-bounds access, it also leads to the wrong memory allocation size. The memory allocation is implicitly tied to the length of the bytecode, not the `size` argument, which violates EVM specifications. As a result, memory resizing only reflects the available bytecode, resulting in misaligned `MSIZE`.

## Detailed Yellow Paper Analysis

The EVM specifications outlined in the Yellow Paper provide the following rules for `CODECOPY`:

- Copy code running in current environment to memory.
    
    $$
    \forall i \in \{0 \ldots \mu_s[2] - 1\} : \mu'_m[\mu_s[0] + i] \equiv
    \begin{cases}
    I_b[\mu_s[1] + i] & \text{if } \mu_s[1] + i < \|I_b\| \\
    \text{STOP} & \text{otherwise}
    \end{cases}
    $$
    
    $$
    \mu'_i \equiv M(\mu_i, \mu_s[0], \mu_s[2])
    $$
    
    **Breakdown**:
    
    1. **Iteration Range**: The operation iterates over all indices from 0 to μs[2]−1 (determined by the `size` parameter).
    2. **Condition**:
        - If the source index (μs[1]+i) is within the bytecode length (∥Ib∥), the byte is copied from the bytecode.
        - Otherwise, a zero is written to the destination memory.
    3. **Memory Alignment**: The memory allocation must align with the total `size` specified, even if part of the copied data is out of the bytecode bounds.

## Step to reproduce

**Payload**

```rust
[97, 56, 57, 0x5f, 0x5f, 57, 89]

PUSH2 0x3839  // size = 14393
PUSH0         // offset = 0
PUSH0         // dest_offset = 0
CODECOPY
MSIZE
STOP
```

Add to [test](https://github.com/lambdaclass/ethrex/blob/main/crates/vm/levm/tests/edge_case_tests.rs) :

```rust

fn test_non_compliance_codecopy_memory_resize() {
    let mut vm = new_vm_with_bytecode(Bytes::copy_from_slice(&[97, 56, 57, 0x5f, 0x5f, 57, 89]
    ))
    .unwrap();
    let mut current_call_frame = vm.call_frames.pop().unwrap();
    vm.execute(&mut current_call_frame);
    assert_eq!(current_call_frame.stack.stack[0], U256::from(14400));
}
```

## Backtrace

```rust
thread 'test_non_compliance_codecopy_memory_resize' panicked at crates/vm/levm/tests/edge_case_tests.rs:18:5:
assertion `left == right` failed
  left: 32
 right: 14400
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c/library/core/src/panicking.rs:76:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /home/mhoste/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:373:5
   4: edge_case_tests::test_non_compliance_codecopy_memory_resize
             at ./tests/edge_case_tests.rs:18:5
   5: edge_case_tests::test_non_compliance_codecopy_memory_resize::{{closure}}
             at ./tests/edge_case_tests.rs:12:48
   6: core::ops::function::FnOnce::call_once
             at /home/mhoste/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

failures:
    test_non_compliance_codecopy_memory_resize

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 24 filtered out; finished in 0.10s
```

### PR DESCRIPTION
**Pull request by ilitteri**
Resolves #1325

### CODE REVIEW

File: crates/vm/levm/src/opcode_handlers/environment.rs [hunk 1]
```diff
@@ -230,29 +230,52 @@ impl VM {
...
+        let current_memory_size = current_call_frame.memory.data.len();
+
+        if current_memory_size < new_memory_size {
+            current_call_frame
+                .memory
+                .data
+                .try_reserve(new_memory_size)
+                .map_err(|_err| VMError::MemorySizeOverflow)?;
+            current_call_frame.memory.data.resize(new_memory_size, 0);
+        }
```
Comment (JereSalo) [inline crates/vm/levm/src/opcode_handlers/environment.rs:260]: What do you think about this replacement:
```suggestion
        current_call_frame.memory.resize(
            destination_offset
                .checked_add(size)
                .ok_or(VMError::VeryLargeNumber)?,
        )?;
```
We have to make Memory's `resize` function public though.

If I'm not mistaken it looks like it has the same behavior

**Review by JereSalo — APPROVED** [review]
Looks good to me. It would be great if we could use `Memory::resize` for resizing behavior

**Comment by ilitteri** [comment]
> Looks good to me. It would be great if we could use `Memory::resize` for resizing behavior

I agree. We'll do a general refactor soon.
