### PR TITLE
fix(l1): using Codec to stream RLPxMessages from/to TcpStream

### LINKED ISSUE #1550: Refactor peer listen-loop to detach socket listening.
Currently each peer listen-loop is awaiting on several possible events, and one of them is the [incoming messages from a socket](https://github.com/lambdaclass/ethrex/blob/main/crates/networking/p2p/rlpx/connection.rs#L279).
Since this `await` is inside a `select!` macro, and it is not cancel-safe, it can get cancelled in the middle of a messages being received and the message will be lost. 

We should detach this process of message reading from the main listen-loop and instead have a process that reads the socket and pushes a message into a cancel-safe channel for the peer listen-loop to handle it.

### PR DESCRIPTION
**Pull request by ElFantasma**
**Motivation**

RLPxConnection logic needs to be simplified and the main peer-loop relies on a `select!` that needs each branch to be cancel-safe

**Description**

This PR:
- Creates a `RLPxCodec` that Encodes and Decodes a `rlpx::Message` into and from the TcpStream, making its interaction cancel-safe
- Simplifies the State Machine required to build the Connection inner state (actually eliminates the State Machine and pushes the state into the codec)
- Separates most of the logic related to TcpStream encoding from the Connection logic (only handshake encoding is still present in `connection.rs` as it is a different encoding from the established connection one. I think it can be moved away in a future PR)

Closes #1550

### CODE REVIEW

File: crates/networking/p2p/rlpx/connection.rs [hunk 1]
```diff
@@ -506,168 +492,131 @@ impl<S: AsyncWrite + AsyncRead + std::marker::Unpin> RLPxConnection<S> {
...
+        let ack = decode_ack_message(&secret_key, msg, size_data)?;
+        let remote_ephemeral_key = ack
+            .get_ephemeral_pubkey()
+            .ok_or(RLPxError::NotFound("Remote ephemeral key".to_string()))?;
+
+        // keccak256(nonce || initiator-nonce)
+        // Local node is initator
+        let hashed_nonces = Keccak256::digest([ack.nonce.0, local_state.nonce.0].concat()).into();
+
+        self.framed.codec_mut().update_secrets(
```
Comment (Arkenan) [inline crates/networking/p2p/rlpx/connection.rs:576]: nit: maybe we can make `receive_ack` return remote state, create local state in the handshake and then just have update secrets receive both states instead of all this arguments? It also decouples the ack/auth messaging from the secrets which is more of a "handshake just finished" thing.

File: crates/networking/p2p/rlpx/frame.rs [hunk 2]
```diff
@@ -1,36 +1,248 @@
...
+
+        let padded_size = frame_size.next_multiple_of(16);
+
+        // Check that the size is not too large to avoid a denial of
+        // service attack where the server runs out of memory.
+        if padded_size > MAX_MESSAGE_SIZE {
+            return Err(RLPxError::InvalidMessageLength());
+        }
+
+        if src.len() < 32 + padded_size + 16 {
```
Comment (Arkenan) [inline crates/networking/p2p/rlpx/frame.rs:150]: nit: maybe `let total_message_size = 32 + padded_size + 16`? We use it some times and it looks arbitrary at first sight.

File: crates/networking/p2p/rlpx/frame.rs [hunk 3]
```diff
@@ -1,36 +1,248 @@
...
+            let mut seed = mac_digest.into();
+            mac_aes_cipher.encrypt_block(&mut seed);
+            (H128(seed.into()) ^ H128(mac_digest)).0
+        };
+        self.ingress_mac.update(frame_mac_seed);
+        let expected_frame_mac: [u8; 16] = self.ingress_mac.clone().finalize()[..16]
+            .try_into()
+            .map_err(|_| RLPxError::CryptographyError("Invalid frame mac".to_owned()))?;
+
+        assert_eq!(frame_mac, expected_frame_mac);
```
Comment (Arkenan) [inline crates/networking/p2p/rlpx/frame.rs:188]: Not for this PR, but should we remove this and return and error? Can we have a TODO for this?

**Review by Arkenan — APPROVED** [review]
Amazing PR! Only left a couple of nit comments, but feel free to merge as-is. They are mostly nits.

The only important thing that is for a different PR is the `assert_eq!`

File: crates/networking/p2p/rlpx/connection.rs [hunk 4]
```diff
@@ -275,49 +274,44 @@ impl<S: AsyncWrite + AsyncRead + std::marker::Unpin> RLPxConnection<S> {
...
-            debug!("Started peer main loop");
-            // Wait for eth status message or timeout.
-            let mut broadcaster_receive = {
-                if self.capabilities.contains(&CAP_ETH) {
-                    Some(self.connection_broadcast_send.subscribe())
-                } else {
-                    None
+        self.init_peer_conn().await?;
+        debug!("Started peer main loop");
+        // Wait for eth status message or timeout.
```
Comment (avilagaston9) [inline crates/networking/p2p/rlpx/connection.rs:279]: nit: shouldn't be?
```Rust
    // Wait for eth status message or timeout.
    self.init_peer_conn().await?;
    debug!("Started peer main loop");

```

File: crates/networking/p2p/rlpx/connection.rs [hunk 5]
```diff
@@ -275,49 +274,44 @@ impl<S: AsyncWrite + AsyncRead + std::marker::Unpin> RLPxConnection<S> {
...
+        let mut broadcaster_receive = {
+            if self.capabilities.contains(&CAP_ETH) {
+                Some(self.connection_broadcast_send.subscribe())
+            } else {
+                None
+            }
+        };
+
+        // Status message received, start listening for connections,
+        // and subscribe this connection to the broadcasting.
```
Comment (avilagaston9) [inline crates/networking/p2p/rlpx/connection.rs:289]: Same here, shouldn't it be?
```Rust
// Status message received, start listening for connections,
// and subscribe this connection to the broadcasting.
let mut broadcaster_receive = {
    if self.capabilities.contains(&CAP_ETH) {
        Some(self.connection_broadcast_send.subscribe())
    } else {
        None
    }
};
```

File: crates/networking/p2p/rlpx/connection.rs [hunk 6]
```diff
@@ -506,168 +492,131 @@ impl<S: AsyncWrite + AsyncRead + std::marker::Unpin> RLPxConnection<S> {
...
+        let secret_key: SecretKey = self.signer.clone().into();
+        let peer_pk = id2pubkey(self.remote_node_id).ok_or(RLPxError::InvalidPeerId())?;
 
-            let msg = encode_auth_message(
-                &secret_key,
-                previous_state.nonce,
-                &peer_pk,
-                &previous_state.ephemeral_key,
-            )?;
+        let local_nonce = H256::random_using(&mut rand::thread_rng());
```
[the remark this answers is not in the document]
Comment (ElFantasma) [reply crates/networking/p2p/rlpx/connection.rs:499]: Nice find, but `rand 0.9.0` is still beta:
```
error: failed to select a version for the requirement `rand = "^0.9.0"`
candidate versions found which didn't match: 0.9.0-beta.3, 0.9.0-beta.1, 0.9.0-beta.0, ...
```
I think we better stay away from beta libaries, right?

File: crates/networking/p2p/rlpx/connection.rs (hunk 1 above)
Comment (ElFantasma) [reply crates/networking/p2p/rlpx/connection.rs:576]: I like this a lot!

File: crates/networking/p2p/rlpx/connection.rs (hunk 4 above)
Comment (ElFantasma) [reply crates/networking/p2p/rlpx/connection.rs:292]: Actually that comment is previous to a refactor and it is misplaced (it should go in the `init_peer_conn()` function.

Correcting it

File: crates/networking/p2p/rlpx/connection.rs (hunk 5 above)
Comment (ElFantasma) [reply crates/networking/p2p/rlpx/connection.rs]: Yes, outdated comment, nice catch
