### PR TITLE
fix(l1): hive invalid ancestor

### LINKED ISSUE #982: Fix the get_latest_valid_hash starting from a hash/header
Right now we get the latest canonical hash, but for the responses we actually want to return the latest valid hash from the branch that ends in a certain hash or header. If it's a dangling header with no branch to be found, None should be returned (null in the RPC response).

### PR DESCRIPTION
**Pull request by MarcosNicolau**
**Motivation**
Fixes hive invalid ancestor tests under `engine-cancun` with the pattern `engine-cancun/Invalid Missing .* .*CanonicalReOrg=False`.

**Description**
The following was implemented to fix the tests:
- Because `forkchoice_update` and `new_payload` require us to send the latest valid hash, we now cache the last valid hash of the chain corresponding to bad blocks, these are the `invalid_ancestors`.
- The bad blocks are cached when:
   1. When failing to add a block during syncing
   2.  When the block execution of `new_payload` fails.
- The latest valid hash was fixed on `new_payload`; this was a known issue see #982.
- Finally, when syncing, if we have a pending block from a `new_payload` request, we attach it if the parent hash of the block corresponds to the last header parent hash.

Closes #982
Advances on #1285

### CODE REVIEW

File: cmd/ef_tests/blockchain/test_runner.rs [hunk 1]
```diff
@@ -50,7 +50,7 @@ pub fn run_ef_test(test_key: &str, test: &TestUnit) {
                     test_key,
                     block_fixture.expect_exception.clone().unwrap()
                 );
-                apply_fork_choice(&store, hash, hash, hash).unwrap();
+                apply_fork_choice(&store, HashMap::new(), hash, hash, hash).unwrap();
```
Comment (mpaulucci) [inline cmd/ef_tests/blockchain/test_runner.rs:53]: I don't like that we have to pass invalid ancestors to the fork choice, can't we have it in store or inside the syncer?

File: crates/blockchain/fork_choice.rs [hunk 2]
```diff
@@ -28,8 +31,10 @@ pub fn apply_fork_choice(
         return Err(InvalidForkChoice::InvalidHeadHash);
     }
 
-    // We get the block bodies even if we only use headers them so we check that they are
-    // stored too.
+    // Check if the block has already been invalidated
+    if let Some(latest_valid_hash) = invalid_ancestors.get(&head_hash) {
+        return Err(InvalidForkChoice::InvalidAncestor(*latest_valid_hash));
```
Comment (mpaulucci) [inline crates/blockchain/fork_choice.rs:36]: why is it called ancestor if the validation is down on the head block?

File: cmd/ef_tests/blockchain/test_runner.rs (hunk 1 above)
Comment (MarcosNicolau) [reply cmd/ef_tests/blockchain/test_runner.rs:53]: Tbh, I am not a fan either. The invalid ancestors hashmap is indeed stored on the syncer struct, but `apply_fork_choice` can't access it unless we are willing to pass the whole syncer struct. 

The alternative would be to remove the check from `apply_fork_choice` and do it in the rpc functions, where the `RpcApiContext` (thus the syncer) is accessible.

File: crates/blockchain/fork_choice.rs (hunk 2 above)
Comment (MarcosNicolau) [reply crates/blockchain/fork_choice.rs:36]: `InvalidAncestor` indicates that the block (in this case the head being considered for fork choice) has an invalid ancestor. This means it couldn't be successfully added to the tip of the chain, likely due to a missing or incorrect parent block. I could add a comment explaining this.

File: cmd/ef_tests/blockchain/test_runner.rs (hunk 1 above)
Comment (MarcosNicolau) [reply cmd/ef_tests/blockchain/test_runner.rs]: I've opted out to move this out to the rpc function, it looks much better now! See [408b5e6](https://github.com/lambdaclass/ethrex/pull/1926/commits/408b5e61cb80cf2cd3d2593e20492e0c8e70acd9).

File: crates/networking/p2p/sync.rs [hunk 3]
```diff
@@ -310,7 +347,9 @@ async fn download_and_run_blocks(
     mut block_hashes: Vec<BlockHash>,
```
Comment (mpaulucci) [inline crates/networking/p2p/sync.rs:347]: nit: maybe this should be a method inside the SyncManager

**Review by mpaulucci — APPROVED** [review]
🚀

File: crates/networking/p2p/sync.rs (hunk 3 above)
Comment (MarcosNicolau) [reply crates/networking/p2p/sync.rs:347]: I agree, though this behavior is inherited from before. #1962 is changing the full syncing logic.
