### PR TITLE
fix(l1): peers tcp connections

### LINKED ISSUE #1811: bug(l1): Delete peer from kademlia table on failure when establishing tcp connection.
When we fail during handshake or during connection, we do [update the kademlia table to reflect the peer disconnection](https://github.com/lambdaclass/ethrex/blob/dfc382b6f3b640e110eb3d5d46d834f31393e0f9/crates/networking/p2p/rlpx/connection.rs#L223), but we don't do that when we [fail to establish the tcp connection with peer](https://github.com/lambdaclass/ethrex/blob/dfc382b6f3b640e110eb3d5d46d834f31393e0f9/crates/networking/p2p/net.rs#L828-L832). Or when we [fail to decode the initial message](https://github.com/lambdaclass/ethrex/blob/dfc382b6f3b640e110eb3d5d46d834f31393e0f9/crates/networking/p2p/net.rs#L841-L844). 

We should do the same, but that code is commented out as it makes a [test](https://github.com/lambdaclass/ethrex/blob/dfc382b6f3b640e110eb3d5d46d834f31393e0f9/crates/networking/p2p/net.rs#L1109) to fail.

We should comment out the test or find another way to test that scenario to enable the kademlia update on failure.

(Note this code is undergoing some refactor, so this ticket may be outdated. But the issue may still be present in some other form)

### PR DESCRIPTION
**Pull request by MarcosNicolau**
**Motivation**
We observed that our peer count was significantly lower compared to other execution clients.

**Description**
This PR refines the exploratory work done in #1875. While debugging, we developed tools to track individual peer traces (see [here](https://github.com/MarcosNicolau/eth-el-clients-debugging) if interested). Through this, we discovered that although we were exchanging messages with many peers, they were not appearing in the stats. This indicated that they were not being inserted into the `KademliaTable`.

The root cause was that the Bucket was already full, which happens quickly since each bucket only holds 10 entries. Below is a list of changes that improved the peer situation:
- Peers were connected but not properly inserted into the table: We temporarily fixed this by forcing peer insertion, even if it exceeded the protocol’s allowed limit. An alternative solution could be maintaining a secondary table for P2P peers, but that would be better suited for the incoming refactor.
- Frame decoding verification was causing connection crashes: Specifically, an assertion on `header-data` was failing. While the spec dictates that it should be RLP-encoded zero, some clients would not send the encoded values. Additionally, we found that no other clients seem to enforce verification on this field.
-  Added logging for message exchanges between peers.
- Refactored functions that were over-locking the KademliaTable: This became particularly noticeable when a high number of peers were discovered.

**Other Findings**
- Incorrect capability exchange logic: We attempt to connect to peers with the snap capability without first verifying if they support our eth protocol version. This leads to failed connections. A separate PR will address this, this is the cause of the observed error message related to capability exchange failures due to mismatched eth and snap protocols.
- Most disconnections occur because peers have already reached their connection limit (sending us `Too many peers` as the reason).
- A future improvement could be implementing a reconnection mechanism.
- The majority of our connections are incoming.

Closes #1811

### CODE REVIEW

**Comment by Oppen** [comment]
Will you make a PR with the tooling? I think it would be a good thing to have in the repo.

File: crates/networking/p2p/discv4/server.rs [hunk 1]
```diff
@@ -693,7 +694,7 @@ pub(super) mod tests {
             broadcast,
         };
 
-        let discv4 = Discv4Server::try_new(ctx).await?;
+        let discv4 = Discv4Server::try_new(ctx.clone()).await?;
```
Comment (Oppen) [inline crates/networking/p2p/discv4/server.rs:697]: Why do we need this clone? How does `storage` behave wrt to clones?

Comment (Oppen) [inline crates/networking/p2p/discv4/server.rs:697]: Is `ctx` safe to clone? How does `storage` behave?

File: crates/networking/p2p/kademlia.rs [hunk 2]
```diff
@@ -67,7 +67,19 @@ impl KademliaTable {
         let node_id = node.node_id;
         let bucket_idx = bucket_number(node_id, self.local_node_id);
 
-        self.insert_node_inner(node, bucket_idx)
+        self.insert_node_inner(node, bucket_idx, false)
+    }
+
+    /// Inserts a node into the table, even if the bucket is filled.
```
Comment (Oppen) [inline crates/networking/p2p/kademlia.rs:73]:
```suggestion
    /// Inserts a node into the table, even if the bucket is full.
```

File: crates/networking/p2p/kademlia.rs [hunk 3]
```diff
@@ -67,7 +67,19 @@ impl KademliaTable {
...
+    /// # Returns
+    /// A tuple containing:
+    ///     1. PeerData: none if the peer was already in the table or as a potential replacement
```
Comment (Oppen) [inline crates/networking/p2p/kademlia.rs:76]: I would expect the opposite here, that is, if it was in the table I may want to check the old value. How is it currently used?

**Comment by Oppen** [comment]
I have a few high level questions:
1. How do we determine the bucket for a given node?
2. Is the bucket getting full or the whole table?
3. If it's just the bucket, did you consider it might be a distribution problem (that is, we might have too many collisions), and that maybe we need to change how we determine the bucker? Or is that an untouchable part of the protocol?

File: crates/networking/p2p/net.rs [hunk 4]
```diff
@@ -180,10 +176,24 @@ pub fn node_id_from_signing_key(signer: &SigningKey) -> H512 {
 
 /// Shows the amount of connected peers, active peers, and peers suitable for snap sync on a set interval
 pub async fn periodically_show_peer_stats(peer_table: Arc<Mutex<KademliaTable>>) {
-    const INTERVAL_DURATION: tokio::time::Duration = tokio::time::Duration::from_secs(120);
+    const INTERVAL_DURATION: tokio::time::Duration = tokio::time::Duration::from_secs(30);
     let mut interval = tokio::time::interval(INTERVAL_DURATION);
     loop {
-        peer_table.lock().await.show_peer_stats();
+        let peers: Vec<kademlia::PeerData> =
+            peer_table.lock().await.iter_peers().cloned().collect();
```
Comment (Oppen) [inline crates/networking/p2p/net.rs:183]: I understand this is done this way to keep the lock short. It would be a good idea to add a comment for the future.

File: crates/networking/p2p/rlpx/connection.rs [hunk 5]
```diff
@@ -122,7 +122,7 @@ impl<S: AsyncWrite + AsyncRead + std::marker::Unpin> RLPxConnection<S> {
             // NOTE: if the peer came from the discovery server it will already be inserted in the table
             // but that might not always be the case, so we try to add it to the table
             // Note: we don't ping the node we let the validation service do its job
-            table.lock().await.insert_node(self.node);
+            table.lock().await.insert_node_forced(self.node);
             table.lock().await.init_backend_communication(
```
Comment (Oppen) [inline crates/networking/p2p/rlpx/connection.rs:126]: We may want to take the lock once for both operations here.

File: crates/networking/p2p/rlpx/frame.rs [hunk 6]
```diff
@@ -122,10 +122,6 @@ impl Decoder for RLPxCodec {
         let mut temp_ingress_aes = self.ingress_aes.clone();
         temp_ingress_aes.apply_keystream(header_text);
 
-        // header-data = [capability-id, context-id]
-        // Both are unused, and always zero
-        assert_eq!(&header_text[3..6], &(0_u8, 0_u8).encode_to_vec());
```
Comment (Oppen) [inline crates/networking/p2p/rlpx/frame.rs:127]: Was this check a bug?

File: crates/networking/p2p/discv4/server.rs (hunk 1 above)
Comment (MarcosNicolau) [reply crates/networking/p2p/discv4/server.rs:697]: Yes, it is safe! You can see the `Store` struct [here](https://github.com/lambdaclass/ethrex/blob/main/crates/storage/store/storage.rs#L29-L35), cloning is just incrementing the reference count.

File: crates/networking/p2p/rlpx/frame.rs (hunk 6 above)
Comment (MarcosNicolau) [reply crates/networking/p2p/rlpx/frame.rs:127]: This check is ok, and it aligns with the spec (see [here](https://github.com/ethereum/devp2p/blob/master/rlpx.md#framing)), but: 
1. The fields are not being used anywhere in the protocol now.
2. Via the logs, I noticed that some clients may send a different value, but the connection would still be correct. 
3. Additionally, I found that the rest of the execution clients (at least geth, besu, and nethermind) don't enforce this header to be RLP Encoded 0, so I preferred to remove it simply.

File: crates/networking/p2p/kademlia.rs (hunk 3 above)
Comment (MarcosNicolau) [reply crates/networking/p2p/kademlia.rs:76]: I agree with you. That would be the expected and usual behaviour. But this is a copy of a previous function (see [here](https://github.com/lambdaclass/ethrex/blob/fix/peers-tcp-connections/crates/networking/p2p/kademlia.rs#L61-L71) and [here](https://github.com/lambdaclass/ethrex/blob/fix/peers-tcp-connections/crates/networking/p2p/discv4/server.rs#L513-L533) for a usage example). I wouldn't change this behaviour now as the future networking refactor is probably going to do this already.

**Comment by MarcosNicolau** [comment]
> I have a few high level questions:
> 
> 1. How do we determine the bucket for a given node?
> 2. Is the bucket getting full or the whole table?
> 3. If it's just the bucket, did you consider it might be a distribution problem (that is, we might have too many collisions), and that maybe we need to change how we determine the bucker? Or is that an untouchable part of the protocol?


1. The bucket is defined as the `XOR` between the keecak256 of the node public key and our local node public key.
2. The bucket is getting filled, not the whole table; the temporary fix is to bypass the spec max size when we know the peer TCP connection was successful.
3. I suspect that the issue might lie in the way we are discarding peers. I am actually debugging that, but for the time being, I would leave this solution to fix the peer situation asap.

Most of it can be read on the spec [here](https://github.com/ethereum/devp2p/blob/master/discv4.md#kademlia-table).

File: crates/networking/p2p/net.rs (hunk 4 above)
Comment (MarcosNicolau) [reply crates/networking/p2p/net.rs:184]: Solved in [1750680](https://github.com/lambdaclass/ethrex/pull/1885/commits/175068048d99993300917d4bcea102e4676aae4a).

File: crates/networking/p2p/kademlia.rs (hunk 2 above)
Comment (MarcosNicolau) [reply crates/networking/p2p/kademlia.rs]: Solved in [1750680](https://github.com/lambdaclass/ethrex/pull/1885/commits/175068048d99993300917d4bcea102e4676aae4a).

File: crates/networking/p2p/kademlia.rs [hunk 7]
```diff
@@ -312,19 +331,6 @@ impl KademliaTable {
         self.get_random_peer_with_filter(&filter)
             .and_then(|peer| peer.channels.clone())
     }
-
-    /// Outputs total amount of peers, active peers, and active peers supporting the Snap Capability to the command line
-    pub fn show_peer_stats(&self) {
```
Comment (mpaulucci) [inline crates/networking/p2p/kademlia.rs:317]: why did you remove this?

**Review by mpaulucci — APPROVED** [review]
