### PR TITLE
test(l1): fix hive ReOrg tests by requesting headers from newToOld

### LINKED ISSUE #4577: Fix Shanghai "Block Re-Org, Sync" hive tests
Some tests in the `engine-withdrawals` hive test suite are failing:

- Withdrawals Fork on Block 1 - 8 Block Re-Org, Sync (Paris) (ethrex)
- Withdrawals Fork on Block 8 - 10 Block Re-Org Sync (Paris) (ethrex)
- Withdrawals Fork on Canonical Block 8 / Side Block 7 - 10 Block Re-Org Sync (Paris) (ethrex)
- Withdrawals Fork on Canonical Block 8 / Side Block 9 - 10 Block Re-Org Sync (Paris) (ethrex)

These have two clients running, while the CL sends blocks to the two clients. At some point, it sends a side-chain to one of the two clients and sets that chain as canonical. That client keeps trying to ask the other one for headers until it times out.

### PR DESCRIPTION
**Pull request by cdiielsi**
**Motivation**

The following tests in the `engine-withdrawals` hive test suite:

- Withdrawals Fork on Block 1 - 8 Block Re-Org, Sync (Paris) (ethrex)
- Withdrawals Fork on Block 8 - 10 Block Re-Org Sync (Paris) (ethrex)
- Withdrawals Fork on Canonical Block 8 / Side Block 7 - 10 Block Re-Org Sync (Paris) (ethrex)
- Withdrawals Fork on Canonical Block 8 / Side Block 9 - 10 Block Re-Org Sync (Paris) (ethrex)

failed because when syncing we always request the block headers from our `current_head` on (OldToNew), but in these tests the request goes to a node that's on a sidechain that didn't have our `current_head` so the request returned no headers and syncing never finished.

**Description**

In this pr I tackle the case described by having a first request of headers from NewToOld from the `sync_head`, and then trying to sync, this is all covered in a new function `synced_new_to_old`. If syncing fails because we have no common ancestor within the obtained headers we go back to request headers as we did before, from OldToNew from our `current_head` and then try to sync as usual.

Closes #4577 and partially solves #2126 as a provisional solution until #4717 is solved.

### CODE REVIEW

File: crates/networking/p2p/sync.rs [hunk 1]
```diff
@@ -336,96 +336,160 @@ impl Syncer {
...
-            else {
-                warn!("Sync failed to find target block header, aborting");
-                debug!("Sync Log 8: Sync failed to find target block header, aborting");
-                return Ok(());
+        let requested_header =
+            if let Some(sync_head_block) = store.get_pending_block(sync_head).await? {
+                sync_head_block.header.parent_hash
+            } else {
+                sync_head
             };
```
Comment (MegaRedHand) [inline crates/networking/p2p/sync.rs]: Can we do a `while` here?

File: crates/networking/p2p/sync.rs [hunk 2]
```diff
@@ -336,96 +336,160 @@ impl Syncer {
...
+                .process_incoming_headers(
+                    block_headers,
+                    sync_head,
+                    true, // sync_head_found is true because of the NewToOld headers request
+                    self.blockchain.clone(),
+                    self.peers.clone(),
+                    self.cancel_token.clone(),
+                )
+                .await?;
+            Ok(())
```
Comment (MegaRedHand) [inline crates/networking/p2p/sync.rs]: Let's do an early return here.

File: crates/networking/p2p/sync.rs [hunk 3]
```diff
@@ -336,96 +336,160 @@ impl Syncer {
...
-            debug!("Sync Log 1: In Full Sync");
-            debug!(
-                "Sync Log 3: State current headers len {}",
-                block_sync_state.current_headers.len()
-            );
-            debug!(
-                "Sync Log 4: State current blocks len {}",
-                block_sync_state.current_blocks.len()
-            );
+        info!("Sync Log 1: In Full Sync");
```
Comment (MegaRedHand) [inline crates/networking/p2p/sync.rs]: Let's move all of the new code to another function, to keep this one small.
Also, above the call to that function, let's add a comment with the reasoning behind the call and a ref to this PR.

File: crates/networking/p2p/sync.rs [hunk 4]
```diff
@@ -336,96 +336,160 @@ impl Syncer {
...
+                    self.peers.clone(),
+                    self.cancel_token.clone(),
+                )
+                .await?;
+            Ok(())
+        } else {
+            // if found_common_ancestor is false that means we are more than 1024 blocks behind so, for now, we go back to syncing as it follows.
+            // TODO: Have full syncing always be from NewToOld
+            loop {
+                info!("Sync Log 1: In Full Sync");
```
Comment (MegaRedHand) [inline crates/networking/p2p/sync.rs]: This should still be `debug!`

File: crates/networking/p2p/sync.rs (hunk 1 above)
Comment (cdiielsi) [reply crates/networking/p2p/sync.rs]: You mean to replace the original loop with a while? Sure! I'd replace it with `while(!sync_head_found)`

File: .github/workflows/pr-main_l1.yaml [hunk 5]
```diff
@@ -191,7 +191,7 @@ jobs:
...
+            test_pattern: "engine-withdrawals/Corrupted Block Hash Payload|Empty Withdrawals|engine-withdrawals test loader|GetPayloadBodies|GetPayloadV2 Block Value|Max Initcode Size|Sync after 2 blocks - Withdrawals on Genesis|Withdraw many accounts|Withdraw to a single account|Withdraw to two accounts|Withdraw zero amount|Withdraw many accounts|Withdrawals Fork on Block 1 - 1 Block Re-Org|Withdrawals Fork on Block 1 - 8 Block Re-Org |Withdrawals Fork on Block 2|Withdrawals Fork on Block 3|Withdrawals Fork on Block 8 - 10 Block Re-Org |Withdrawals Fork on Canonical Block 8 / Side Block 7 - 10 Block Re-Org |Withdrawals Fork on Canonical Block 8 / Side Block 9 - 10 Block Re-Org"
```
Comment (mpaulucci) [inline .github/workflows/pr-main_l1.yaml]: If you fix all the tests, you should be able to remove this completely since you will be passing all tests

File: crates/networking/p2p/sync.rs (hunk 1 above)
Comment (MegaRedHand) [reply crates/networking/p2p/sync.rs]: No. I mean to continue fetching the `sync_head` parent with `get_pending_block` until we don't find it in the DB

File: crates/networking/p2p/sync.rs [hunk 6]
```diff
@@ -336,96 +336,184 @@ impl Syncer {
...
-                block_sync_state.current_headers.len()
-            );
-            debug!(
-                "Sync Log 4: State current blocks len {}",
-                block_sync_state.current_blocks.len()
-            );
+        if !self
+            .synced_new_to_old(&mut block_sync_state, sync_head, store)
+            .await?
+        {
```
Comment (MegaRedHand) [inline crates/networking/p2p/sync.rs]: Let's do an early return here.

File: crates/networking/p2p/sync.rs [hunk 7]
```diff
@@ -336,96 +336,184 @@ impl Syncer {
...
-                current_head = first_block_parent_hash;
-                continue;
-            }
+                // TODO(#2126): This is just a temporary solution to avoid a bug where the sync would get stuck
+                // on a loop when the target head is not found, i.e. on a reorg with a side-chain.
+                if first_block_hash == last_block_hash
+                    && first_block_hash == current_head
+                    && current_head != sync_head
+                {
+                    // There is no path to the sync head this goes back until it find a common ancerstor
```
Comment (MegaRedHand) [inline crates/networking/p2p/sync.rs]: Let's try removing this `if`, since it tries to solve the same issue as this PR.

File: crates/networking/p2p/sync.rs [hunk 8]
```diff
@@ -620,16 +708,28 @@ impl FullBlockSyncState {
...
+        // Then we add it in current_blocks for execution.
+        let mut pending_block_to_sync = vec![];
+        let mut last_header_to_sync = sync_head;
+        while let Some(block) = self.store.get_pending_block(last_header_to_sync).await? {
+            let block_parent = block.header.parent_hash;
+            if self
+                .current_blocks
+                .last()
+                .is_some_and(|block| block.hash() == block_parent)
+                && !self.current_blocks.contains(&block)
```
Comment (MegaRedHand) [inline crates/networking/p2p/sync.rs]: This line isn't needed. If the last block is `block`'s parent, none of the rest of the blocks can be `block`, otherwise we'd have a loop.

```suggestion
```

File: crates/networking/p2p/sync.rs [hunk 9]
```diff
@@ -620,16 +708,28 @@ impl FullBlockSyncState {
...
-            if let Some(last_block) = self.current_blocks.last() {
-                if last_block.hash() == block.header.parent_hash {
-                    self.current_blocks.push(block);
-                    sync_head_found = true;
-                }
+        // We check if we have pending blocks we didn't request that are needed for syncing
+        // Then we add it in current_blocks for execution.
+        let mut pending_block_to_sync = vec![];
+        let mut last_header_to_sync = sync_head;
+        while let Some(block) = self.store.get_pending_block(last_header_to_sync).await? {
```
Comment (MegaRedHand) [inline crates/networking/p2p/sync.rs:725]: This can potentially slow down the processing of blocks if we have a large chain of pending blocks. If we are syncing from genesis, it might take a while until this chain connects, but this loop will happen each time we process a batch of blocks. We should implement some in-memory structure to make this check easy, but for now, let's just limit this check to 32 blocks with a comment explaining this.

File: crates/networking/p2p/sync.rs (hunk 7 above)
Comment (cdiielsi) [reply crates/networking/p2p/sync.rs]: Ok! This pr only fixes this issue if we are less than 1024 blocks behind though, otherwise I think this bug might still happen, should I remove it anyway?

File: crates/networking/p2p/sync.rs (hunk 8 above)
Comment (cdiielsi) [reply crates/networking/p2p/sync.rs]: Sorry! I probably added it while debugging, I'm taking it away!

File: crates/networking/p2p/sync.rs (hunk 7 above)
Comment (MegaRedHand) [reply crates/networking/p2p/sync.rs]: Actually, let's keep it, since this _could_ fix some edge cases.

**Review by MegaRedHand — APPROVED** [review]
