### PR TITLE
fix(l1): add deposit request layout validations + return invalid deposit request error

### LINKED ISSUE #2132: Fix Sepolia deposit contract issue
There was an issue when the clients hardforked to Pectra in Sepolia related to the contract address and the logs that are emmited.

This is the change to the EIP: https://github.com/ethereum/EIPs/pull/9453

This is the fix on Geth: https://github.com/ethereum/go-ethereum/pull/31317

This test should pass: https://github.com/ethereum/execution-spec-tests/commit/9084db04ba223f7d0a78d17365220c7b7ea457cd#diff-423832c4eebde83349472ade321b211f34bd8659b6a677207da2ae0b78b462e9R22

This is a blog post explaining the issue: https://mariusvanderwijden.github.io/blog/2025/03/08/Sepolia/

### PR DESCRIPTION
**Pull request by fmoletta**
**Motivation**
Currently, when we fail to parse a deposit request we simply ignore it and keep the rest of the deposits, relying on the request hash check afterwards to notice the missing deposit request. This PR handles the error earlier and returns the appropriate `InvalidDepositRequest Error`. This will provide better debugging information and also more accurate testing via tools such as `execution-spec-tests` which rely on specific error returns.
We also were not correctly validating the layout according to the [EIP](https://eips.ethereum.org/EIPS/eip-6110), as we were only checking the total size and not the size and offset of each request field

**Description**
* Check that the full layout of deposit requests is valid (aka the internal sizes and offsets of the encoded data)
* Handle errors when parsing deposit requests
* Check log topic matches deposit topic before parsing a request as a deposit request

Allows us to address review comment  made on execution-specs-test PR https://github.com/ethereum/execution-spec-tests/pull/1607 + also closes #2132

### CODE REVIEW

File: crates/common/types/requests.rs [hunk 1]
```diff
@@ -17,6 +20,11 @@ const DEPOSIT_TYPE: u8 = 0x00;
 const WITHDRAWAL_TYPE: u8 = 0x01;
 const CONSOLIDATION_TYPE: u8 = 0x02;
 
+lazy_static! {
+    static ref DEPOSIT_TOPIC: H256 =
+        H256::from_str("649bbc62d0e31342afea4e5cd82d4049e7e1ee912fc0889aa790803be39038c5").unwrap();
```
Comment (mpaulucci) [inline crates/common/types/requests.rs:25]: Do we want to have these constants in a centralized place like https://github.com/lambdaclass/ethrex/blob/main/crates/common/constants.rs ?

**Review by mpaulucci — APPROVED** [review]

File: crates/common/types/requests.rs (hunk 1 above)
Comment (fmoletta) [reply crates/common/types/requests.rs:25]: It is something specific to requests so I don't think we will be using it anywhere else to warrant it being centralized

**Review by JereSalo — APPROVED** [review]
