### PR TITLE
fix(l1): fcu not triggering sync if snap is enabled + re-enable snap sync hive test

### LINKED ISSUE #2521: Snap test is flaky
The outcome of this ticket is that the test should be fixed and not be flaky.

See https://github.com/lambdaclass/ethrex/pull/2520

As part of the debugging, we could run many times with --debug flag until we see the output of the failing tests

### PR DESCRIPTION
**Pull request by fmoletta**
**Motivation**
PR #2426 changed how fork choice & new payload interact with the syncer and also introduced a bug. If snap sync is enabled, then fork choice update will never attempt to trigger a sync, so the sync process never gets started.
This PR fixes the bug and also refactors the sync manager api to better suit the new use cases

* Combine commonly used together `SyncManager` methods `set_head` & `start_sync` into `sync_to_head`
* Remove unused `SyncManager` method `status` and associated struct
* Make sure sync is triggered during fcu  when needed even if snap sync is enabled
* Re-enable snap sync hive test suite
**Description**

Closes #2521

### CODE REVIEW

**Review by mpaulucci — APPROVED** [review]
nice catch!

File: crates/networking/rpc/engine/fork_choice.rs [hunk 1]
```diff
@@ -312,8 +314,9 @@ async fn handle_forkchoice(
                         .update_sync_status(false)
                         .await
                         .map_err(|e| RpcErr::Internal(e.to_string()))?;
-                    context.syncer.set_head(fork_choice_state.head_block_hash);
-                    context.syncer.start_sync();
+                    context
+                        .syncer
+                        .sync_to_head(fork_choice_state.head_block_hash);
```
Comment (rodrigo-o) [inline crates/networking/rpc/engine/fork_choice.rs:319]: Great that now the syncer decides to start the sync!

**Review by rodrigo-o — APPROVED** [review]
