### PR TITLE
fix(l1): dont fail when importing a block that is already stored

### LINKED ISSUE #2936: Fix some `import` issues.
The `import` command has a couple of issues:

- When sending a predefined network like `hoodi` via `network` param, it was not able to recognize that it's a public network and the genesis file is stored.
- When running something like `ethrex import hoodi-blocks-first-thousand.rlp` it was not able to recognize that it should search for the file in the current directory. I had to run it like `ethrex import ./hoodi-blocks-first-thousand.rlp`
- When passing a rlp file including the block number 0 (the genesis block), it said it was not able to find the parent block and failed. Whenever blocks are imported that are already present in the db, it should skip them and continue.

### PR DESCRIPTION
**Pull request by santiago-MV**
**Motivation**

The import commands has some issues

**Description**

The first issue was that the network flag wouldn't recognize public networks
Ex.: When running `-- network hoodi` it failed
The function `get_genesis_path` solve this issue by matching the inputed value `hoodi` with the path to its `genesis.json` file, using the values defined in `network.rs`

When trying to add the block 0 to the blockchain it would fail because the parent block couldn't be found. This was solved by ensuring that blocks that are already in the blockchain don't get added again (The genesis block is added when the `Store` is initialized)
The `try_block_add` method of `Blockchain` implements this logic

Closes #2936

### CODE REVIEW

File: cmd/ethrex/utils.rs [hunk 1]
```diff
@@ -82,9 +82,20 @@ pub fn read_block_file(block_file_path: &str) -> Block {
 }
 
 pub fn read_genesis_file(genesis_file_path: &str) -> Genesis {
-    let genesis_file = std::fs::File::open(genesis_file_path).expect("Failed to open genesis file");
+    let path = get_genesis_path(genesis_file_path);
+    let genesis_file = std::fs::File::open(path).expect("Failed to open genesis file");
     decode::genesis_file(genesis_file).expect("Failed to decode genesis file")
 }
+// If genesis_file_path is one of the public networks return the path to its genesis.json file, if not return the inputed path
+fn get_genesis_path(genesis_file_path: &str) -> &str {
```
Comment (mpaulucci) [inline cmd/ethrex/utils.rs:90]: nit: argument you probably be `network` to make it clear it is not necesary a path. Also I would not call this function from inside `read_genesis_file `. Instead I would do something like:

let genesis_path = get_genesis_path(network);
let genesis = read_genesis_file(genesis_path);

Also, Instead of `genesis_file_path ` receiving a string, it should receive a `Path`.

Also,  maybe `network` cli param receive a custom type, that is like an enum that can be a PublicNetwork, or (Genesis) Path.

File: cmd/ethrex/cli.rs [hunk 2]
```diff
@@ -371,6 +371,7 @@ pub async fn import_blocks(path: &str, data_dir: &str, network: &str, evm: EvmEn
 }
 
 pub fn compute_state_root(genesis_path: &str) {
+    let genesis_path = utils::get_genesis_path(genesis_path);
```
Comment (mpaulucci) [inline cmd/ethrex/cli.rs:374]: why do you need this here? seems like a no-op

Comment (santiago-MV) [reply cmd/ethrex/cli.rs:374]: Its needed for the `read_genesis_file` call in line 375

File: cmd/ethrex/utils.rs (hunk 1 above)
Comment (mpaulucci) [reply cmd/ethrex/utils.rs]: I think this would be great. nit: instead of path `GenesisPath(Path)`

File: cmd/ethrex/bench/import_blocks_benchmark.rs [hunk 3]
```diff
@@ -14,7 +15,7 @@ fn block_import() {
 
     let evm_engine = EvmEngine::default();
 
-    let network = "../../test_data/genesis-perf-ci.json";
+    let network = Networks::from("../../test_data/genesis-perf-ci.json");
```
Comment (mpaulucci) [inline cmd/ethrex/bench/import_blocks_benchmark.rs:18]: nit: why Networks and not Network

File: cmd/ethrex/cli.rs [hunk 4]
```diff
@@ -316,10 +318,10 @@ pub fn remove_db(datadir: &str, force: bool) {
     }
 }
 
-pub async fn import_blocks(path: &str, data_dir: &str, network: &str, evm: EvmEngine) {
+pub async fn import_blocks(path: &str, data_dir: &str, network: Networks, evm: EvmEngine) {
```
Comment (mpaulucci) [inline cmd/ethrex/cli.rs:321]: review if all these functions need to receive a Network or a genesis_path: Path, or a Genesis

File: cmd/ethrex/cli.rs [hunk 5]
```diff
@@ -272,15 +273,16 @@ impl Subcommand {
...
                     .network
                     .as_ref()
                     .expect("--network is required and it was not provided");
-
+                let network = Networks::from(network_string.as_str());
                 import_blocks(&path, &opts.datadir, network, opts.evm).await;
             }
             Subcommand::ComputeStateRoot { genesis_path } => {
-                compute_state_root(genesis_path.to_str().expect("Invalid genesis path"));
+                let network = Networks::from(genesis_path);
```
[the remark this answers is not in the document]
Comment (santiago-MV) [reply cmd/ethrex/cli.rs:284]: Changed it

File: cmd/ethrex/initializers.rs [hunk 6]
```diff
@@ -64,7 +64,7 @@ pub fn init_metrics(opts: &Options, tracker: TaskTracker) {
     tracker.spawn(metrics_api);
 }
 
-pub async fn init_store(data_dir: &str, network: &str) -> Store {
+pub async fn init_store(data_dir: &str, network: &Networks) -> Store {
```
[the remark this answers is not in the document]
Comment (santiago-MV) [reply cmd/ethrex/initializers.rs:67]: Done

File: cmd/ethrex/bench/import_blocks_benchmark.rs (hunk 3 above)
Comment (santiago-MV) [reply cmd/ethrex/bench/import_blocks_benchmark.rs:18]: Changed it to Network

File: crates/blockchain/blockchain.rs [hunk 7]
```diff
@@ -155,6 +155,20 @@ impl Blockchain {
             .map_err(ChainError::StoreError)
     }
 
+    pub async fn try_add_block(&self, block: &Block) -> Result<(), ChainError> {
```
[the remark this answers is not in the document]
Comment (santiago-MV) [reply crates/blockchain/blockchain.rs:158]: To check if the block is part of the blockchain we need to access the `storage` which is a private field of the `blockchain`. To move this logic into `import` a new function that checks if a block is or not present in the chain will be needed.
I suggest to make the change if there is another reason apart of not adding a function into `blockchain` (which as I see, will be needed in both cases)

File: cmd/ethrex/networks.rs [hunk 8]
```diff
@@ -31,3 +33,45 @@ lazy_static! {
     )
     .expect("Failed to parse mainnet bootnodes file");
 }
+#[derive(Debug, Clone)]
+pub enum Network {
+    PublicNetwork(PublicNetworkType),
+    GenesisPath(PathBuf),
+}
+#[derive(Debug, Clone)]
+pub enum PublicNetworkType {
```
Comment (mechanix97) [inline cmd/ethrex/networks.rs:42]: nit change the enum to PublicNetwork, i see the `type` redundant

File: hoodi-blocks-first-thousand.rlp
Comment (mechanix97) [inline hoodi-blocks-first-thousand.rlp:1]: This shouldn't be here

File: crates/blockchain/blockchain.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (mechanix97) [reply crates/blockchain/blockchain.rs:158]: You can access the information from the store variable directly, they share the db underneath

[the remark this answers is not in the document]
Comment (mechanix97) [reply crates/blockchain/blockchain.rs:158]: something like this
`match &store.get_block_number(block.hash()).await {
            Ok(Some(_)) => {
                info!("Block {} is already in the blockchain", block.hash());
                continue;
            }
            Ok(None) => blockchain.add_block(block).await.unwrap(),
            Err(_) => {}
        }`

**Review by mechanix97 — CHANGES_REQUESTED** [review]

File: cmd/ethrex/networks.rs (hunk 8 above)
Comment (santi-morales) [reply cmd/ethrex/networks.rs]: Good suggestion done!

File: crates/blockchain/blockchain.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (santi-morales) [reply crates/blockchain/blockchain.rs]: Good catch, done!

**Review by mechanix97 — APPROVED** [review]
LGTM!

File: cmd/ethrex/cli.rs [hunk 9]
```diff
@@ -37,9 +38,10 @@ pub struct Options {
         help = "Receives a `Genesis` struct in json format. This is the only argument which is required. You can look at some example genesis files at `test_data/genesis*`.",
         long_help = "Alternatively, the name of a known network can be provided instead to use its preset genesis file and include its preset bootnodes. The networks currently supported include holesky, sepolia, hoodi and mainnet.",
         help_heading = "Node options",
-        env = "ETHREX_NETWORK"
+        env = "ETHREX_NETWORK",
+        value_parser = clap::value_parser!(Network),
     )]
-    pub network: Option<String>,
+    pub network: Option<Network>,
```
Comment (mpaulucci) [inline cmd/ethrex/cli.rs]: nit: instead of an `Option`, it would be nice to have a default (same as we have with `evm` arg). The default should be mainnet

File: cmd/ethrex/cli.rs [hunk 10]
```diff
@@ -350,13 +352,25 @@ pub async fn import_blocks(path: &str, data_dir: &str, network: &str, evm: EvmEn
...
+            Ok(None) => {
+                if let Err(error) = blockchain.add_block(block).await {
+                    warn!(
+                        "Failed to add block {} with hash {:#x}: {}.",
+                        block.header.number, hash, error
+                    );
+                    return;
+                }
+            }
+            Err(_) => {
```
Comment (mpaulucci) [inline cmd/ethrex/cli.rs:371]: maybe `import_blocks` should return a Result and here you should return an Error

File: cmd/ethrex/cli.rs [hunk 11]
```diff
@@ -316,10 +317,11 @@ pub fn remove_db(datadir: &str, force: bool) {
     }
 }
 
-pub async fn import_blocks(path: &str, data_dir: &str, network: &str, evm: EvmEngine) {
+pub async fn import_blocks(path: &str, data_dir: &str, genesis_path: &Path, evm: EvmEngine) {
```
Comment (mpaulucci) [inline cmd/ethrex/cli.rs]: maybe instead of functions receiving `genesis_path`, they could receive `Genesis`.

And we could have a function inside `Network` that reads it. Like: `network.get_genesis()`

thoughts?

File: cmd/ethrex/cli.rs [hunk 12]
```diff
@@ -370,7 +384,7 @@ pub async fn import_blocks(path: &str, data_dir: &str, network: &str, evm: EvmEn
     info!("Added {size} blocks to blockchain");
 }
 
-pub fn compute_state_root(genesis_path: &str) {
```
Comment (mpaulucci) [inline cmd/ethrex/cli.rs:373]: if we have `network.get_genesis()`, we can remove this function.

File: cmd/ethrex/cli.rs (hunk 9 above)
Comment (santi-morales) [reply cmd/ethrex/cli.rs]: Done!

File: cmd/ethrex/cli.rs (hunk 10 above)
Comment (santi-morales) [reply cmd/ethrex/cli.rs:371]: Done! Now `import_blocks` returns `Result<(),ChainErrors>` which is the same that `add_block` returns.
Decided to still print the warning message inside `import_blocks` if add_block produced an error, and then return that same error.

File: cmd/ethrex/cli.rs (hunk 11 above)
Comment (santi-morales) [reply cmd/ethrex/cli.rs]: Good suggestion! done

File: cmd/ethrex/cli.rs (hunk 12 above)
Comment (santi-morales) [reply cmd/ethrex/cli.rs:373]: Implemented `get_genesis` and removed this function, now a new Network is created with the arg path and the new method is used.

File: cmd/ethrex/cli.rs [hunk 13]
```diff
@@ -33,13 +35,15 @@ pub struct CLI {
 pub struct Options {
     #[arg(
         long = "network",
+        default_value = "mainnet",
```
Comment (mpaulucci) [inline cmd/ethrex/cli.rs]: See how evm does it: default_value_t = EvmEngine::default(),

File: cmd/ethrex/bench/import_blocks_benchmark.rs [hunk 14]
```diff
@@ -14,13 +15,13 @@ fn block_import() {
 
     let evm_engine = EvmEngine::default();
 
-    let network = "../../test_data/genesis-perf-ci.json";
+    let network = Network::from("../../test_data/genesis-perf-ci.json");
 
     let rt = tokio::runtime::Runtime::new().unwrap();
-    rt.block_on(import_blocks(
+    let _ = rt.block_on(import_blocks(
```
Comment (mpaulucci) [inline cmd/ethrex/bench/import_blocks_benchmark.rs]: you need to panic here. For example adding an `expect`

File: cmd/ethrex/ethrex.rs [hunk 15]
```diff
@@ -57,7 +57,8 @@ async fn main() -> eyre::Result<()> {
 
     let network = get_network(&opts);
 
-    let store = init_store(&data_dir, &network).await;
+    let genesis = read_genesis_file(network.get_genesis_path());
```
Comment (mpaulucci) [inline cmd/ethrex/ethrex.rs]: the idea is to use `network.get_genesis()` ...

File: cmd/ethrex/cli.rs (hunk 13 above)
Comment (santi-morales) [reply cmd/ethrex/cli.rs]: Done!

File: cmd/ethrex/ethrex.rs (hunk 15 above)
Comment (santi-morales) [reply cmd/ethrex/ethrex.rs]: missed it, done!

File: cmd/ethrex/bench/import_blocks_benchmark.rs (hunk 14 above)
Comment (santi-morales) [reply cmd/ethrex/bench/import_blocks_benchmark.rs]: done!

**Review by mpaulucci — APPROVED** [review]
