### PR TITLE
fix(l2): check if `AccountUpdate`'s `AccountInfo` is `None` in l1 committer.

### LINKED ISSUE #2093: L1,L2: Commiter Error
When running some intensive I/O benchmarks this error popped up:
```
2025-02-26T19:48:47.319068Z ERROR ethrex_l2::proposer::l1_committer: L1 Committer Error: Committer failed retrieve data from storage
2025-02-26T19:52:21.118528Z  INFO ethrex_l2::proposer::l1_committer: Preparing state diff for block 47
2025-02-26T19:52:21.156108Z ERROR ethrex_l2::proposer::l1_committer: L1 Committer Error: Committer failed retrieve data from storage
2025-02-26T19:52:22.350683Z  INFO ethrex_l2::proposer::l1_committer: Preparing state diff for block 47
2025-02-26T19:52:22.383189Z ERROR ethrex_l2::proposer::l1_committer: L1 Committer Error: Committer failed retrieve data from storage
2025-02-26T19:52:23.433060Z  INFO ethrex_l2::proposer::l1_committer: Preparing state diff for block 47
2025-02-26T19:52:23.466063Z ERROR ethrex_l2::proposer::l1_committer: L1 Committer Error: Committer failed retrieve data from storage
2025-02-26T19:52:24.669902Z  INFO ethrex_l2::proposer::l1_committer: Preparing state diff for block 47
2025-02-26T19:52:24.704110Z ERROR ethrex_l2::proposer::l1_committer: L1 Committer Error: Committer failed retrieve data from storage
```
Which prevented further transactions to be included in blocks.

You can reproduce this **_by opening 3 terminals_** in ethrex's root folder and running the following commands on each one.
1. cd crates/l2 && make rm-db-l1 && make init-l1
2. cd crates/l2 && make rm-db-l2 && make deploy-l1 && make init-l2
3. make load-test-io

### PR DESCRIPTION
**Pull request by lima-limon-inc**
**Motivation**

When running the L2 load test (`make load-test-io`), you would get the following error in the L2: `ERROR ethrex_l2::proposer::l1_committer: L1 Committer Error: Committer failed retrieve data from storage`.

This PR fixes this error in the L2's committer. 

**Description**

In the `l1_committer.rs` file, `AccountStateDiff`s were constructed from `AccountUpdates`. More specifically, it used the `AccountUpdates`'s `nonce`.
The problem was that `AccountUpdates` sometimes didn't contain `nonce`  as a value, and the whole `AccountInfo` struct (which holds the `nonce`) evaluated to `None`. 

Therefore, if the computed `AccountUpdates`'s had a `None` for `AccountInfo`, it means that there was no change in `nonce`. Therefore, the new nonce is equal to the nonce of the previous block. 

Closes #2093

### CODE REVIEW

File: crates/l2/proposer/l1_committer.rs [hunk 1]
```diff
@@ -276,16 +276,20 @@ impl Committer {
                 None => 0,
             };
 
+            let new_nonce = if account_update.info.is_none() {
+                prev_nonce
+            } else {
+                account_update
+                    .info
+                    .clone()
```
Comment (jrchatruc) [inline crates/l2/proposer/l1_committer.rs:284]: You can replace this `clone()` with an `as_ref()` to avoid cloning the AccountInfo

**Review by jrchatruc — APPROVED** [review]

File: crates/l2/proposer/l1_committer.rs (hunk 1 above)
Comment (lima-limon-inc) [reply crates/l2/proposer/l1_committer.rs]: Great point Javi! Changed here: https://github.com/lambdaclass/ethrex/pull/2133/commits/27c3358941d57710d8e576da042ef66146ebedea

File: crates/l2/proposer/l1_committer.rs [hunk 2]
```diff
@@ -276,16 +276,20 @@ impl Committer {
...
                 account_update.address,
                 AccountStateDiff {
                     new_balance: account_update.info.clone().map(|info| info.balance),
-                    nonce_diff: (account_update
-                        .info
-                        .clone()
-                        .ok_or(CommitterError::FailedToRetrieveDataFromStorage)?
-                        .nonce
-                        - prev_nonce)
+                    nonce_diff: (new_nonce - prev_nonce)
```
Comment (fkrause98) [inline crates/l2/proposer/l1_committer.rs:292]: It should never happen, but we should check for overflow here.

For that, I suggest using [overflowing_sub](https://doc.rust-lang.org/std/primitive.u64.html#method.overflowing_sub) and maybe log a warning.

**Review by fkrause98 — CHANGES_REQUESTED** [review]

File: crates/l2/proposer/l1_committer.rs [hunk 3]
```diff
@@ -276,16 +276,20 @@ impl Committer {
...
 
+            let new_nonce = if account_update.info.is_none() {
+                prev_nonce
+            } else {
+                account_update
+                    .info
+                    .as_ref()
+                    .ok_or(CommitterError::FailedToRetrieveDataFromStorage)?
+                    .nonce
+            };
```
Comment (xqft) [inline crates/l2/proposer/l1_committer.rs:287]: Nit: it shouldn't be necessary to throw an error as you can match the `Option<AccountInfo>`:

```suggestion
            let nonce_diff = if let Some(info) = account_update.info {
                info.nonce - prev_nonce
            } else {
                0
            };
```

Comment (xqft) [reply crates/l2/proposer/l1_committer.rs:287]: or
```rust
let new_nonce = account_update.info.map(|info| info.nonce - prev_nonce).unwrap_or(0);
```
if you like oneliners

**Review by xqft — APPROVED** [review]

File: crates/l2/proposer/l1_committer.rs (hunk 3 above)
Comment (fkrause98) [reply crates/l2/proposer/l1_committer.rs:287]: I don't think defaulting to 0 is the right approach here.

Comment (xqft) [reply crates/l2/proposer/l1_committer.rs:287]: although if you address Fran's comment, the first approach should be easier for throwing an overflow error (it's possible doing it the functional way but it gets messy)

Comment (lima-limon-inc) [reply crates/l2/proposer/l1_committer.rs:287]: > although if you address Fran's comment, the first approach should be easier for throwing an overflow error (it's possible doing it the functional way but it gets messy)

I personally found the oneliner a bit harder to read. I think I liked the first approach a bit better.

**Review by JereSalo — APPROVED** [review]
I think the fix is fine but (even though it is out of scope) I watched the code around the changes to understand the context and saw some stuff worth mentioning:

- I see we are not contemplating the case in which `removed = true` in `AccountUpdates`. It is very likely that it won’t have an impact but I just noticed that.
- Why is `bytecode_hash` set to `None`?
- I would change names of the fields `AccountStateDiff` . Shouldn’t nonce diff be `u64`? Is `modified_storage` a better name for `storage`? Just to clarify which fields are diffs and which ones are not. (Maybe that’s a personal preference)
- I may be wrong on this one but we are accessing the previous block by doing `block.header.number - 1` and I just wondered if that would be right in the case of a reorg.  I would have accessed the previous block by hash usgin `block.header.parent_hash` but assuming blocks are ALWAYS ordered by number despite a reorg then it’s indifferent. (I don’t know much about reorgs so that’s just a thing to investigate)

File: crates/l2/proposer/l1_committer.rs (hunk 2 above)
Comment (lima-limon-inc) [reply crates/l2/proposer/l1_committer.rs]: What do you think of this approach Fran? https://github.com/lambdaclass/ethrex/pull/2133/commits/638f29bacc54af204c4018119ab67ed26bf7daa4

I went for `checked_sub` instead because we use more often in the codebase, plus something about `overflowing_sub` seems fishy to me. 
Isn't it better to raise an error rather than commit an invalid/erroneous nonce?

File: crates/l2/proposer/l1_committer.rs (hunk 3 above)
Comment (lima-limon-inc) [reply crates/l2/proposer/l1_committer.rs]: @xqft Hey Tefo, what about this? https://github.com/lambdaclass/ethrex/pull/2133/commits/1f10efc2e96ac8591b7ac1f5e7146d90ee6fd362
It's a bit of an in-between. I liked the if let version better; but I maintained the substraction inside the construction of the Struct.

Comment (xqft) [reply crates/l2/proposer/l1_committer.rs]: @fkrause98 sorry just saw your response, why do you think that? I thought a `None` account info in an account update meant no change in account info by definition, therefore no change in nonce, therefore `nonce_diff = 0`

Comment (xqft) [reply crates/l2/proposer/l1_committer.rs]: @lima-limon-inc looks good!!

**Review by xqft — APPROVED** [review]

File: crates/l2/proposer/l1_committer.rs (hunk 2 above)
Comment (fkrause98) [reply crates/l2/proposer/l1_committer.rs]: My bad, I got the mixed up. `checked_sub` is the correct one to use.

File: crates/l2/proposer/l1_committer.rs (hunk 3 above)
Comment (lima-limon-inc) [reply crates/l2/proposer/l1_committer.rs]: > @fkrause98 sorry just saw your response, why do you think that? I thought a None account info in an account update meant no change in account info by definition, therefore no change in nonce, therefore nonce_diff = 0

I believe that the problem with defaulting to 0 is that it hides the cases where, for some reason, the nonce is negative. I think raising an error, were that to happen, is valuable.
