### PR TITLE
fix(levm): add suport for `stDelegatecallTestHomestead` test suite

### LINKED ISSUE #1886: LEVM: Add support for the stDelegatecallTestHomestead test suite
After adding the [`LegacyTest`](https://github.com/ethereum/legacytests/tree/b2e6c9e43ede7eec9c5b2997c14a892e7eb2f124), new folders containing tests for Pre-Cancun forks were added.
Currently the state of folder `stDelegatecallTestHomestead` is:
`stDelegatecallTestHomestead: 40/120 (33.33%)`.
We want to make it 100%

### PR DESCRIPTION
**Pull request by tomip01**
**Motivation**

In this PR we increase the test passed in the `stDelegatecallTestHomestead` test suite.

**Description**

* We add the pre tangerine gas costs for `sload`, `selfdestruct` and `extcodecopy`.
* We now don't apply the "all but one 64th" introduced in the [eip-150](https://eips.ethereum.org/EIPS/eip-150).
* We invalidate the transaction if we use a `delegatecall` opcode introduced in [eip-7](https://eips.ethereum.org/EIPS/eip-7) for previous forks to Homestead.
* We add on previous fork to Spurious Dragon to set the nonce to 0 instead of 1. This is due to [eip-161](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-161.md).

Closes #1886

### CODE REVIEW

File: crates/vm/levm/src/gas_cost.rs [hunk 1]
```diff
@@ -1237,19 +1239,24 @@ fn calculate_cost_and_gas_limit_call(
...
-    let gas: u64 = gas_from_stack
-        .min(max_gas_for_call.into())
-        .try_into()
-        .map_err(|_err| OutOfGasError::MaxGasLimitExceeded)?;
+    let gas: u64 = if fork < Fork::Tangerine {
+        gas_from_stack
+    } else {
+        // EIP 150, https://eips.ethereum.org/EIPS/eip-150
+        let max_gas_for_call = gas_left
+            .checked_sub(gas_left / 64)
```
Comment (fborello-lambda) [inline crates/vm/levm/src/gas_cost.rs:1254]: Maybe we could use `checked_div(64)` before `checked_sub()`?

**Review by fborello-lambda — COMMENTED** [review]
Looks good, left a comment

**Review by fborello-lambda — APPROVED** [review]
