### PR TITLE
fix(levm): prevent inefficient memory allocation in extcodecopy

### LINKED ISSUE #1245: [SECURITY] Non-Compliance : Inefficient Memory Allocation in EXTCODECOPY
Our team at [FuzzingLabs](https://github.com/FuzzingLabs) discovered a non-compliant behavior was observed in the [EXTCODECOPY](https://github.com/lambdaclass/ethrex/blob/main/crates/vm/levm/src/opcode_handlers/environment.rs#L213) opcode implementation. Specifically, LEVM allocates memory even when the `size` parameter is `0`, leading to unnecessary resource usage. This behavior is inconsistent with reference implementations such as Geth and REVM, which do not perform memory allocation in such cases.

# Root cause

```rust
// EXTCODECOPY operation
pub fn op_extcodecopy(
    &mut self,
    current_call_frame: &mut CallFrame,
) -> Result<OpcodeSuccess, VMError> {
    let address = word_to_address(current_call_frame.stack.pop()?);
    let dest_offset: usize = current_call_frame
        .stack
        .pop()?
        .try_into()
        .map_err(|_| VMError::VeryLargeNumber)?;
    let offset: usize = current_call_frame
        .stack
        .pop()?
        .try_into()
        .map_err(|_| VMError::VeryLargeNumber)?;
    let size: usize = current_call_frame
        .stack
        .pop()?
        .try_into()
        .map_err(|_| VMError::VeryLargeNumber)?;
    let is_cached = self.cache.is_account_cached(&address);

    let gas_cost = gas_cost::extcodecopy(current_call_frame, size, dest_offset, is_cached)
        .map_err(VMError::OutOfGas)?;

    self.increase_consumed_gas(current_call_frame, gas_cost)?;

    if !is_cached {
        self.cache_from_db(&address);
    };

    let bytecode = self.get_account(&address).info.bytecode;
    let new_memory_size = dest_offset.checked_add(size).ok_or(VMError::Internal(
        InternalError::ArithmeticOperationOverflow,
    ))?;
    let current_memory_size = current_call_frame.memory.data.len();
    if current_memory_size < new_memory_size {
        current_call_frame.memory.data.resize(new_memory_size, 0);
    }

    for i in 0..size {
        if let Some(memory_byte) =
            current_call_frame
                .memory
                .data
                .get_mut(dest_offset.checked_add(i).ok_or(VMError::Internal(
                    InternalError::ArithmeticOperationOverflow,
                ))?)
        {
            *memory_byte = *bytecode
                .get(offset.checked_add(i).ok_or(VMError::Internal(
                    InternalError::ArithmeticOperationOverflow,
                ))?)
                .unwrap_or(&0u8);
        }
    }

    Ok(OpcodeSuccess::Continue)
}
```

When `size = 0`, the `resize` function is still called to expand the memory, even though no data is written.

```rust
let current_memory_size = current_call_frame.memory.data.len();
    if current_memory_size < new_memory_size {
        current_call_frame.memory.data.resize(new_memory_size, 0);
    }

```

This memory expansion is redundant since no operation needs to be performed for `size = 0`.

## Recommendations

To align LEVM with reference implementations and avoid redundant memory allocation, modify the`op_extcodecopy`implementation to check if`size = 0`before performing memory allocation. This will reduce resource consumption and ensure consistent behavior with other EVM implementations.

## Step to reproduce

**Payload**

```rust
[88, 88, 88, 89, 60, 89]
PC
PC
PC
MSIZE
EXTCODECOPY
MSIZE
```

Add to [test](https://github.com/lambdaclass/ethrex/blob/5bbe595ff9e3900b2d84f075d3b19672a10854b9/crates/vm/levm/tests/edge_case_tests.rs) :

```rust
#[test]
fn test_non_compliance_extcodecopy() {
    let mut vm = new_vm_with_bytecode(Bytes::copy_from_slice(&[88, 88, 88, 89, 60, 89]))
    .unwrap();
    let mut current_call_frame = vm.call_frames.pop().unwrap();
    vm.execute(&mut current_call_frame);
    assert_eq!(current_call_frame.stack.stack[0], U256::zero());
}
```

## Backtrace

```rust
hread 'test_non_compliance_extcodecopy' panicked at crates/vm/levm/tests/edge_case_tests.rs:16:5:
assertion `left == right` failed
  left: 2
 right: 0
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c/library/core/src/panicking.rs:76:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /home/mhoste/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:373:5
   4: edge_case_tests::test_non_compliance_extcodecopy
             at ./tests/edge_case_tests.rs:16:5
   5: edge_case_tests::test_non_compliance_extcodecopy::{{closure}}
             at ./tests/edge_case_tests.rs:11:37
   6: core::ops::function::FnOnce::call_once
             at /home/mhoste/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

failures:
    test_non_compliance_extcodecopy

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 15 filtered out; finished in 0.10s
```

### PR DESCRIPTION
**Pull request by maximopalopoli**
**Motivation**

Fixes an memory inefficiency found by [FuzzingLabs](https://github.com/FuzzingLabs) in extcodecopy opcode implementation.

**Description**

Before, there was memory allocation even if the size to copy was zero. Now, if that happens, returns.

Closes #1245

### CODE REVIEW

File: crates/vm/levm/tests/edge_case_tests.rs [hunk 1]
```diff
@@ -1,3 +1,6 @@
+#![allow(clippy::indexing_slicing)]
+#![allow(clippy::unwrap_used)]
```
Comment (ilitteri) [inline crates/vm/levm/tests/edge_case_tests.rs:2]: I don't think these are needed. Checkout the `clippy.toml` and what we can write to avoid this.

**Review by ilitteri — APPROVED** [review]
