### PR TITLE
fix(l1): validate received blocks from peers

### LINKED ISSUE #2766: Validate received blocks from peers
See this PR: https://github.com/lambdaclass/ethrex/pull/2658

We should ensure that incoming blocks from peers pass minimal validation. We should penalize peers if they don't.

### PR DESCRIPTION
**Pull request by JulianVentura**
**Motivation**

While syncing on Holesky, we noticed that some peers were providing us with empty block bodies. This made the syncing loop fail in different occasions, which ultimately lead to a stop in the syncing process. Instead of failing, we want to validate the received headers and bodies and discard the peer and retry if they are not valid.

**Description**

This PR makes the following changes:

* Add a new validation `validate_block_body` to check if a body is valid, agains the corresponding header
* Add a simple header validation to the peer handler request headers, to make sure that the received headers conform a chain from the current head
* Call the `validate_block_body` function from the peer handle validat and request block bodies, to check that the received block bodies are valid.
* Modify the `PeerChannel` API to return the `peer_id` on the `request_block_headers` and `request_block_bodies` functions.
* Modify the `PeerChannel` API to add a function `remove_peer` to remove a peer by its `peer_id`.
* Remove the peer that provided us with the headers or bodies on the syncing loop if they are invalid

Closes #2766

### CODE REVIEW

File: crates/blockchain/error.rs [hunk 1]
```diff
@@ -30,6 +32,8 @@ pub enum InvalidBlockError {
     ReceiptsRootMismatch,
     #[error("Invalid Header, validation failed pre-execution: {0}")]
     InvalidHeader(#[from] InvalidBlockHeaderError),
+    #[error("Invalid Header, validation failed pre-execution: {0}")]
```
Comment (fmoletta) [inline crates/blockchain/error.rs:35]: Shouldn't this display be "Invalid Block Body, etc"?

File: crates/networking/p2p/sync.rs [hunk 2]
```diff
@@ -224,6 +224,23 @@ impl Syncer {
...
+                .zip(block_hashes.iter())
+                .any(|(current_header, previous_hash)| {
+                    current_header.parent_hash != *previous_hash
+                });
+
+            if any_invalid {
+                warn!("Received invalid header chain from peer, discarding peer {peer_id} and retrying...");
+                self.peers.remove_peer(peer_id).await;
+                continue;
+            }
```
Comment (fmoletta) [inline crates/networking/p2p/sync.rs:242]: Could this validation be done inside the `request_block_headers` method? That way the syncer wouldn't have to interact with the peers directly. This breaks the purpose of the `PeerHandler` abstraction that is preventing peer management code to leak into sync code

File: crates/networking/p2p/sync.rs [hunk 3]
```diff
@@ -422,6 +439,15 @@ impl Syncer {
...
             };
+
+            if let Some(e) = blocks
+                .iter()
+                .find_map(|block| validate_block_body(block).err())
+            {
+                warn!("Invalid block body error {e}, discarding peer {peer_id}");
+                self.peers.remove_peer(peer_id).await;
+                continue; // Retry
+            }
```
Comment (fmoletta) [inline crates/networking/p2p/sync.rs:450]: Same here, maybe we could send the block headers for validation

File: crates/blockchain/error.rs (hunk 1 above)
Comment (rodrigo-o) [reply crates/blockchain/error.rs:35]: Yes!

File: crates/networking/p2p/sync.rs (hunk 2 above)
Comment (rodrigo-o) [reply crates/networking/p2p/sync.rs:242]: I'll take a look at it, but completely agree

File: crates/blockchain/error.rs (hunk 1 above)
Comment (rodrigo-o) [reply crates/blockchain/error.rs]: Done in: [Fix error messages](https://github.com/lambdaclass/ethrex/pull/2658/commits/cfae602eb9bbbd8ace57168d11015198387ce25c)

File: crates/networking/p2p/sync.rs (hunk 2 above)
Comment (rodrigo-o) [reply crates/networking/p2p/sync.rs]: Done here: [Move block headers validation to request headers](https://github.com/lambdaclass/ethrex/pull/2658/commits/3cd12232694a2933e1f94fde98e86e104a435033)

File: crates/networking/p2p/sync.rs (hunk 3 above)
Comment (rodrigo-o) [reply crates/networking/p2p/sync.rs:428]: This is unfortunately a bit more complex given that headers are processed by chunks, I'll take a look tomorrow to try to move the validation to the request_block_bodies as done with the headers.

Comment (rodrigo-o) [reply crates/networking/p2p/sync.rs]: Done by @SDartayet

File: crates/networking/p2p/kademlia.rs [hunk 4]
```diff
@@ -318,13 +318,16 @@ impl KademliaTable {
 
     /// Returns the channel ends to an active peer connection that supports the given capability
     /// The peer is selected randomly, and doesn't guarantee that the selected peer is not currently busy
-    pub fn get_peer_channels(&self, capability: Capability) -> Option<PeerChannels> {
+    pub fn get_peer_channels(&self, capability: Capability) -> Option<(H256, PeerChannels)> {
```
Comment (fmoletta) [inline crates/networking/p2p/kademlia.rs:321]: Could we mention in the method's doc that the hash returned is the node_id?

File: crates/networking/p2p/peer_handler.rs [hunk 5]
```diff
@@ -54,18 +54,27 @@ pub enum BlockRequestOrder {
...
         Self { peer_table }
     }
     /// Returns the channel ends to an active peer connection that supports the given capability
     /// The peer is selected randomly, and doesn't guarantee that the selected peer is not currently busy
     /// If no peer is found, this method will try again after 10 seconds
-    async fn get_peer_channel_with_retry(&self, capability: Capability) -> Option<PeerChannels> {
+    async fn get_peer_channel_with_retry(
+        &self,
+        capability: Capability,
+    ) -> Option<(H256, PeerChannels)> {
```
Comment (fmoletta) [inline crates/networking/p2p/peer_handler.rs:73]: Same for this one

File: crates/networking/p2p/peer_handler.rs [hunk 6]
```diff
@@ -94,32 +103,46 @@ impl PeerHandler {
...
+
+                            let any_invalid = PeerHandler::invalid_block_header_parents(&block_headers, &block_hashes);
+
+                            if any_invalid {
+                                warn!("Received invalid headers from peer, discarding peer {peer_id} and retrying...");
+                                self.remove_peer(peer_id).await;
+                                return None; // Retry request
+                            }
+
+                            // If the headers are valid, we can return them
```
Comment (fmoletta) [inline crates/networking/p2p/peer_handler.rs:131]: Please move this logic outside of the loop. The loop is on a timeout so we shouldn't add any extra logic on top of it

File: crates/networking/p2p/peer_handler.rs [hunk 7]
```diff
@@ -129,17 +152,20 @@ impl PeerHandler {
     /// Returns the block bodies or None if:
     /// - There are no available peers (the node just started up or was rejected by all other nodes)
     /// - No peer returned a valid response in the given time and retry limits
-    pub async fn request_block_bodies(&self, block_hashes: Vec<H256>) -> Option<Vec<BlockBody>> {
+    pub async fn request_block_bodies(
+        &self,
+        block_hashes: Vec<H256>,
+    ) -> Option<(Vec<BlockBody>, H256)> {
```
Comment (fmoletta) [inline crates/networking/p2p/peer_handler.rs:158]: We shouldn't leak the node_id here

File: crates/networking/p2p/peer_handler.rs [hunk 8]
```diff
@@ -164,12 +190,47 @@ impl PeerHandler {
...
+            let block = Block::new(header.clone(), body);
+            blocks.push(block);
+        }
+        if let Some(e) = blocks
+            .iter()
+            .find_map(|block| validate_block_body(block).err())
+        {
+            warn!("Invalid block body error {e}, discarding peer {peer_id}");
+            self.remove_peer(peer_id).await;
+            return Err(BodyRequestError::InvalidBlockBody); // Retry
```
Comment (fmoletta) [inline crates/networking/p2p/peer_handler.rs:229]: Where is the retry?

File: crates/networking/p2p/peer_handler.rs [hunk 9]
```diff
@@ -637,4 +698,20 @@ impl PeerHandler {
         }
         None
     }
+
+    /// Validates the block headers received from a peer by checking that the parent hash of each header
+    /// matches the hash of the previous one.
+    fn invalid_block_header_parents(block_headers: &[BlockHeader], block_hashes: &[H256]) -> bool {
```
Comment (fmoletta) [inline crates/networking/p2p/peer_handler.rs:704]: Could we move this to a separate function outside the `PeerHandler` imps block?

File: crates/networking/p2p/peer_handler.rs [hunk 10]
```diff
@@ -84,7 +93,7 @@ impl PeerHandler {
         &self,
         start: H256,
         order: BlockRequestOrder,
-    ) -> Option<Vec<BlockHeader>> {
+    ) -> Option<(Vec<BlockHeader>, Vec<H256>)> {
```
[the remark this answers is not in the document]
Comment (rodrigo-o) [reply crates/networking/p2p/peer_handler.rs:96]: Completely agreed I forgot to mentioning this in the sync but was something i had in mind while going though this PR.

File: crates/networking/p2p/kademlia.rs (hunk 4 above)
Comment (rodrigo-o) [reply crates/networking/p2p/kademlia.rs:321]: Done in [Added documentation](https://github.com/lambdaclass/ethrex/pull/2658/commits/fc98b8651e4c18900e4556362a75f36aa2b4d180)

File: crates/networking/p2p/peer_handler.rs (hunk 5 above)
Comment (rodrigo-o) [reply crates/networking/p2p/peer_handler.rs:73]: Done in [Added documentation](https://github.com/lambdaclass/ethrex/pull/2658/commits/fc98b8651e4c18900e4556362a75f36aa2b4d180)

File: crates/networking/p2p/peer_handler.rs (hunk 6 above)
Comment (rodrigo-o) [reply crates/networking/p2p/peer_handler.rs]: Moved here: [Extracted the validation of headers outside of the timeout](https://github.com/lambdaclass/ethrex/pull/2658/commits/9b0363d070ad4941a77ea93ab0615a0db781456d)

File: crates/networking/p2p/peer_handler.rs (hunk 7 above)
Comment (rodrigo-o) [reply crates/networking/p2p/peer_handler.rs:155]: The issue here is that the node_id is needed to penalize the peer in `validate_and_request_block_bodies` which is internal, but also used by `store_block_bodies` from `sync.rs`. I'll try to look at other alternatives.

File: crates/networking/p2p/peer_handler.rs (hunk 8 above)
Comment (rodrigo-o) [reply crates/networking/p2p/peer_handler.rs:226]: It's retried outside as you commented [here](https://github.com/lambdaclass/ethrex/pull/2658#discussion_r2096278909), this was an older comment.

File: crates/networking/p2p/sync.rs [hunk 11]
```diff
@@ -386,35 +383,39 @@ impl Syncer {
...
+                    blocks.extend(blcks);
+                }
+                Err(BodyRequestError::BodiesNotFound) => {
+                    return Err(SyncError::BodiesNotFound);
+                }
+                Err(BodyRequestError::BodiesReturnedEmpty) => {
+                    break;
+                }
+                Err(BodyRequestError::InvalidBlockBody) => {
+                    continue;
```
[the remark this answers is not in the document]
Comment (rodrigo-o) [reply crates/networking/p2p/sync.rs:407]: Agree, the issue was mainly that `validate_and_request_block_bodies` used the already existent `request_block_bodies` and it would add another layer of retries (It was reused instead of modified because sync.rs depended on it and didn't had the added complexity for validating headers without a bigger refactor). We might need to go with a different solution.

[the remark this answers is not in the document]
Comment (rodrigo-o) [reply crates/networking/p2p/sync.rs:407]: related to: https://github.com/lambdaclass/ethrex/pull/2658#discussion_r2096551927

File: crates/networking/p2p/peer_handler.rs (hunk 9 above)
Comment (rodrigo-o) [reply crates/networking/p2p/peer_handler.rs]: Done: [Move headers validation outside of PeerHandler impl block](https://github.com/lambdaclass/ethrex/pull/2658/commits/1ddae68ef4e3eaadaeb41838aeb5dd4b373c4df9)

File: crates/networking/p2p/sync.rs (hunk 11 above)
[the remark this answers is not in the document]
Comment (fmoletta) [reply crates/networking/p2p/sync.rs:407]: Maybe we can add an inner method `request_block_bodies_inner` without the retry and then two public methods `request_block_bodies` and `request_and_validate_block_bodies` which add the retry logic on top of it.
Though I have my questions regarding whether we should even allow fetching block bodies without validating them.

[the remark this answers is not in the document]
Comment (fmoletta) [reply crates/networking/p2p/sync.rs:407]: Maybe we should just leave one `request_block_bodies` with the validations so we don't risk saving invalid bodies in our state

**Review by mpaulucci — APPROVED** [review]

File: crates/networking/p2p/sync.rs (hunk 11 above)
[the remark this answers is not in the document]
Comment (rodrigo-o) [reply crates/networking/p2p/sync.rs:407]: Yes I was thinking the same (both with the inner and later with the request that always validate), this requires some refactors but I don't think there is an easier simpler way to do it.

File: crates/networking/p2p/peer_handler.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (fmoletta) [reply crates/networking/p2p/peer_handler.rs:96]: Update: It is now merged #2845 🚀

File: crates/networking/p2p/peer_handler.rs [hunk 12]
```diff
@@ -141,19 +157,22 @@ impl PeerHandler {
     /// Returns the block bodies or None if:
     /// - There are no available peers (the node just started up or was rejected by all other nodes)
     /// - No peer returned a valid response in the given time and retry limits
-    pub async fn request_block_bodies(&self, block_hashes: Vec<H256>) -> Option<Vec<BlockBody>> {
+    pub async fn request_block_bodies(
```
Comment (fmoletta) [inline crates/networking/p2p/peer_handler.rs:160]: I still think we should make this an internal method and move retry logic upstream. The way it works now we are leaking the node_id and also have flawed retry logic for validated block body requests (aka we don't retry if the first attempt yields invalid block bodies).
What I propose is something like this:
`request_block_bodies_inner` -> has no retry logic, performs only one request and leaks node id
`pub request_block_bodies` -> adds retry logic
`pub request_and_validate_block_bodies` -> adds retry logic + validation

Comment (rodrigo-o) [reply crates/networking/p2p/peer_handler.rs:160]: Yes I didn't had the time to fix it yet, but I fixed merge conflicts from main to be able to continue syncing from this branch with the performance updates of #2684 and the fixes of #2859. I'm going to convert it to draft until I'm able to tackle the changes

File: crates/networking/p2p/peer_handler.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (rodrigo-o) [reply crates/networking/p2p/peer_handler.rs:97]: We could address this when tackling: #2926!

File: crates/networking/p2p/peer_handler.rs (hunk 7 above)
Comment (rodrigo-o) [reply crates/networking/p2p/peer_handler.rs:157]: Now this function is private!

File: crates/networking/p2p/peer_handler.rs (hunk 12 above)
Comment (rodrigo-o) [reply crates/networking/p2p/peer_handler.rs]: Changes are in place now, I'm opening it for review again.

File: crates/networking/p2p/peer_handler.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (fmoletta) [reply crates/networking/p2p/peer_handler.rs:97]: Lets leave a comment in the code linking the issue

File: crates/networking/p2p/peer_handler.rs [hunk 13]
```diff
@@ -131,59 +131,137 @@ impl PeerHandler {
...
         }
         None
     }
 
-    /// Requests block bodies from any suitable peer given their block hashes
+    /// Internal method to request block bodies from any suitable peer given their block hashes
     /// Returns the block bodies or None if:
     /// - There are no available peers (the node just started up or was rejected by all other nodes)
     /// - No peer returned a valid response in the given time and retry limits
-    pub async fn request_block_bodies(&self, block_hashes: Vec<H256>) -> Option<Vec<BlockBody>> {
```
Comment (fmoletta) [inline crates/networking/p2p/peer_handler.rs:144]: The method's doc still reflects old method (it mentions retry limits) It should mention that it only performs one request from one peer

File: crates/networking/p2p/peer_handler.rs [hunk 14]
```diff
@@ -131,59 +131,137 @@ impl PeerHandler {
...
+            };
+
+            let mut blocks: Vec<Block> = vec![];
+            let block_bodies_len = block_bodies.len();
+
+            // Push blocks
+            for (_, body) in block_hashes.drain(..block_bodies_len).zip(block_bodies) {
+                let Some(header) = headers_iter.next() else {
+                    debug!("[SYNCING] Header not found for the block bodies received, skipping...");
+                    continue; // If we run out of headers, skip this response
```
Comment (fmoletta) [inline crates/networking/p2p/peer_handler.rs:243]: Shouldn't this be a `break`? there is no point in continuing the loop

File: crates/networking/p2p/peer_handler.rs [hunk 15]
```diff
@@ -131,59 +131,137 @@ impl PeerHandler {
...
         }
         None
     }
 
+    /// Requests block bodies from any suitable peer given their block hashes and validates them
+    /// Returns the block bodies or an error if:
+    /// - There are no available peers (the node just started up or was rejected by all other nodes)
+    /// - No peer returned a valid response in the given time and retry limits
+    /// - The block bodies are invalid given the block headers
+    pub async fn request_and_validate_block_bodies<'a>(
```
Comment (fmoletta) [inline crates/networking/p2p/peer_handler.rs:218]: This method returns full blocks, the doc should reflect it (I think we can leave the name as is as it would become unnecessarily long otherwise). 
Also is building the blocks here necessary?

File: crates/networking/p2p/peer_handler.rs (hunk 14 above)
Comment (rodrigo-o) [reply crates/networking/p2p/peer_handler.rs:243]: Great catch! It was a break indeed!

File: crates/networking/p2p/peer_handler.rs (hunk 15 above)
Comment (rodrigo-o) [reply crates/networking/p2p/peer_handler.rs:218]: We could avoid the creation of the blocks if `validate_block_body` received instead body + header. It will require a bit of refactor but it could be done. Its useful to return the blocks here given that it's the second part (after requesting headers) and it also recieve them as parameters so it make sens to be able to return the full block. But I understand it might break a bit the expected return of the function (which could be just block bodies). We can maintain it or make the changes to avoid building the blocks here and do it in the caller (in this case `sync.rs`) instead

File: crates/networking/p2p/peer_handler.rs (hunk 14 above)
Comment (rodrigo-o) [reply crates/networking/p2p/peer_handler.rs]: Solved here: [Fix retry for more than available consumed headers](https://github.com/lambdaclass/ethrex/pull/2658/commits/ddd2916501bf7f624d6e8065e13b6b88f0115885)

File: crates/networking/p2p/peer_handler.rs (hunk 15 above)
Comment (rodrigo-o) [reply crates/networking/p2p/peer_handler.rs]: Documentation updated here: [Updated function docs](https://github.com/lambdaclass/ethrex/pull/2658/commits/4d23b1333795a693b86ba48cc499cc343782134b)

Let me know if you think we might want to tackle the return of blocks. We can go either with that, an issue, or maintaining things as they are.

File: crates/networking/p2p/peer_handler.rs (hunk 14 above)
Comment (rodrigo-o) [reply crates/networking/p2p/peer_handler.rs]: Done: [Remove a check that wasn't needed and fixed a comment](https://github.com/lambdaclass/ethrex/pull/2658/commits/de280d1fb3de9cc738ab13fdaeb0dcb6282ee8dc)

File: crates/networking/p2p/peer_handler.rs (hunk 15 above)
Comment (rodrigo-o) [reply crates/networking/p2p/peer_handler.rs]: Done: [Remove a check that wasn't needed and fixed a comment](https://github.com/lambdaclass/ethrex/pull/2658/commits/de280d1fb3de9cc738ab13fdaeb0dcb6282ee8dc)
