### PR TITLE
fix(l1, levm): fix hive regression when using levm

### LINKED ISSUE #1777: LEVM: Fix regression on Hive tests
**Context**
After merging https://github.com/lambdaclass/ethrex/pull/1755 there's been a regression in the Hive tests results using LEVM as the backend EVM:
Image

**Description**
1. Find out if this is because of a non-compliance of LEVM or if #1755 introduced a flaw.
2. Fix (1) to fix the regression.

### PR DESCRIPTION
**Pull request by tomip01**
**Motivation**

This pull request introduces updates to the `blockchain` crate, primarily focusing on handling transactions and withdrawals when the `levm` feature is enabled. 

**Description**

##### Dependency Management:

* Added `ethrex-levm` as an optional dependency in `Cargo.toml` to support `levm` feature.
* Updated the `levm` feature to include `ethrex-levm` in `Cargo.toml`.

##### Function Modifications:

* Modified various functions in `payload.rs` to support `block_cache` when the `levm` feature is enabled:
  * `build_payload` now initializes and passes `block_cache` through the transaction processing pipeline.
  * `apply_withdrawals` returns a `block_cache` and updates state based on the `levm` feature.
  * `fill_transactions` and its helper functions (`apply_transaction`, `apply_blob_transaction`, `apply_plain_transaction`) now accept and update `block_cache`.
  * `finalize_payload` updates the state root and other headers using `block_cache` when the `levm` feature is enabled.

##### Code Organization:

* Added conditional imports for `levm` feature in `payload.rs` to ensure compatibility and proper functionality.

Closes #1777

### CODE REVIEW

File: crates/blockchain/payload.rs [hunk 1]
```diff
@@ -214,21 +237,57 @@ pub fn build_payload(
...
     let mut evm_state = evm_state(store.clone(), payload.header.parent_hash);
     let mut context = PayloadBuildContext::new(payload, &mut evm_state);
-    apply_withdrawals(&mut context)?;
-    fill_transactions(&mut context)?;
-    finalize_payload(&mut context)?;
+    let mut block_cache = apply_withdrawals(&mut context)?;
+    fill_transactions(&mut context, &mut block_cache)?;
+    finalize_payload(&mut context, &mut block_cache)?;
+
     Ok((context.blobs_bundle, context.block_value))
```
Comment (tomip01) [inline crates/blockchain/payload.rs:244]: Maybe it should be better to have separate functions when using levm or not levm, but we will have duplicated functions

File: crates/blockchain/payload.rs [hunk 2]
```diff
@@ -423,41 +487,148 @@ fn apply_blob_transaction(
...
+                        .get_account_code(acc_info.code_hash)?
+                        .unwrap_or_default();
+
+                    Account {
+                        info: AccountInfo {
+                            balance: acc_info.balance,
+                            bytecode: acc_code,
+                            nonce: acc_info.nonce,
+                        },
+                        storage: HashMap::new(), // this must be changed, get the storage from the DB
```
Comment (tomip01) [inline crates/blockchain/payload.rs:590]: This issue is addressed [here](https://github.com/lambdaclass/ethrex/issues/1853)

File: crates/blockchain/payload.rs (hunk 1 above)
Comment (fborello-lambda) [reply crates/blockchain/payload.rs:244]: in the near future we should have a better api to handle both evms.
I wouldn't bother now.

File: crates/blockchain/payload.rs [hunk 3]
```diff
@@ -214,21 +237,57 @@ pub fn build_payload(
...
+
+            block_cache.extend(new_state);
+        }
+        Ok(block_cache)
+    }
+    #[cfg(not(feature = "levm"))]
+    {
+        // Apply withdrawals & call beacon root contract, and obtain the new state root
+        let spec_id = spec_id(&context.chain_config()?, context.payload.header.timestamp);
+        if context.payload.header.parent_beacon_block_root.is_some() && spec_id == SpecId::CANCUN {
```
Comment (fborello-lambda) [inline crates/blockchain/payload.rs:286]: Here we have to take into account future forks:
```suggestion
        if context.payload.header.parent_beacon_block_root.is_some() && spec_id >= SpecId::CANCUN {
```

File: crates/blockchain/payload.rs [hunk 4]
```diff
@@ -214,21 +237,57 @@ pub fn build_payload(
     debug!("Building payload");
     let mut evm_state = evm_state(store.clone(), payload.header.parent_hash);
     let mut context = PayloadBuildContext::new(payload, &mut evm_state);
-    apply_withdrawals(&mut context)?;
-    fill_transactions(&mut context)?;
-    finalize_payload(&mut context)?;
+    let mut block_cache = apply_withdrawals(&mut context)?;
```
Comment (fborello-lambda) [inline crates/blockchain/payload.rs:240]: You are essentially creating a cache and sharing it across all the functions, so that in the `finalize_payload()` function you update it and then get the withdrawals right?

File: crates/blockchain/payload.rs [hunk 5]
```diff
@@ -214,21 +237,57 @@ pub fn build_payload(
...
-        beacon_root_contract_call(context.evm_state, &context.payload.header, spec_id)?;
+pub fn apply_withdrawals(
+    context: &mut PayloadBuildContext,
+) -> Result<HashMap<Address, Account>, EvmError> {
+    #[cfg(feature = "levm")]
+    {
+        let mut block_cache = HashMap::new();
+        // Apply withdrawals & call beacon root contract, and obtain the new state root
+        let spec_id = spec_id(&context.chain_config()?, context.payload.header.timestamp);
+        if context.payload.header.parent_beacon_block_root.is_some() && spec_id == SpecId::CANCUN {
```
Comment (fborello-lambda) [inline crates/blockchain/payload.rs]: Same as below
```suggestion
        if context.payload.header.parent_beacon_block_root.is_some() && spec_id >= SpecId::CANCUN {
```

**Review by fborello-lambda — COMMENTED** [review]
Left some comments

File: crates/blockchain/payload.rs (hunk 3 above)
Comment (fborello-lambda) [reply crates/blockchain/payload.rs:287]: well, you just updated it to `Fork`, but the idea is the same.

File: crates/blockchain/payload.rs (hunk 5 above)
Comment (fborello-lambda) [reply crates/blockchain/payload.rs]: well, you just updated it to `Fork`, but the idea is the same.

File: crates/blockchain/payload.rs (hunk 3 above)
Comment (tomip01) [reply crates/blockchain/payload.rs]: Nice!, done here [b3da929](https://github.com/lambdaclass/ethrex/pull/1817/commits/b3da929c4b605e33eb0989dd8ea7d6157bc9625f)

**Review by fborello-lambda — APPROVED** [review]
Looks good, i would merge it so we can continue with the cli's argument implementation instead of the feature flag

File: crates/blockchain/payload.rs [hunk 6]
```diff
@@ -228,21 +252,58 @@ pub fn build_payload(
...
 }
 
-pub fn apply_withdrawals(context: &mut PayloadBuildContext) -> Result<(), EvmError> {
-    // Apply withdrawals & call beacon root contract, and obtain the new state root
-    let spec_id = spec_id(&context.chain_config()?, context.payload.header.timestamp);
-    if context.payload.header.parent_beacon_block_root.is_some() && spec_id == SpecId::CANCUN {
-        beacon_root_contract_call(context.evm_state, &context.payload.header, spec_id)?;
+pub fn apply_withdrawals(
+    context: &mut PayloadBuildContext,
+) -> Result<HashMap<Address, Account>, EvmError> {
```
Comment (lima-limon-inc) [inline crates/blockchain/payload.rs:263]: How about
```suggestion
) -> Result<CacheDB, EvmError> {
```

This would need the following suggestion as well I believe.

Do you like it better or do you prefer to leave the Hash as is?

File: crates/blockchain/payload.rs [hunk 7]
```diff
@@ -8,17 +8,41 @@ use ethrex_core::{
...
         compute_transactions_root, compute_withdrawals_root, BlobsBundle, Block, BlockBody,
-        BlockHash, BlockHeader, BlockNumber, ChainConfig, MempoolTransaction, Receipt, Transaction,
-        Withdrawal, DEFAULT_OMMERS_HASH,
+        BlockHash, BlockHeader, BlockNumber, ChainConfig, Fork, MempoolTransaction, Receipt,
+        Transaction, Withdrawal, DEFAULT_OMMERS_HASH,
     },
     Address, Bloom, Bytes, H256, U256,
 };
+#[cfg(feature = "levm")]
+use ethrex_levm::AccountInfo;
```
Comment (lima-limon-inc) [inline crates/blockchain/payload.rs:17]:
```suggestion
use ethrex_levm::{db::CacheDB, AccountInfo};
```

File: crates/blockchain/payload.rs [hunk 8]
```diff
@@ -228,21 +252,58 @@ pub fn build_payload(
...
-    // Apply withdrawals & call beacon root contract, and obtain the new state root
-    let spec_id = spec_id(&context.chain_config()?, context.payload.header.timestamp);
-    if context.payload.header.parent_beacon_block_root.is_some() && spec_id == SpecId::CANCUN {
-        beacon_root_contract_call(context.evm_state, &context.payload.header, spec_id)?;
+pub fn apply_withdrawals(
+    context: &mut PayloadBuildContext,
+) -> Result<HashMap<Address, Account>, EvmError> {
+    #[cfg(feature = "levm")]
+    {
+        let mut block_cache = HashMap::new();
```
Comment (lima-limon-inc) [inline crates/blockchain/payload.rs:266]:
```suggestion
        let mut block_cache = CacheDB::new();
```

Comment (lima-limon-inc) [reply crates/blockchain/payload.rs:266]: Ditto

File: crates/blockchain/payload.rs [hunk 9]
```diff
@@ -283,7 +344,10 @@ fn fetch_mempool_transactions(
 
 /// Fills the payload with transactions taken from the mempool
 /// Returns the block value
-pub fn fill_transactions(context: &mut PayloadBuildContext) -> Result<(), ChainError> {
+pub fn fill_transactions(
+    context: &mut PayloadBuildContext,
+    block_cache: &mut HashMap<Address, Account>,
```
Comment (lima-limon-inc) [inline crates/blockchain/payload.rs:349]:
```suggestion
    block_cache: &mut CacheDB,
```

File: crates/blockchain/payload.rs [hunk 10]
```diff
@@ -396,17 +460,19 @@ pub fn fill_transactions(context: &mut PayloadBuildContext) -> Result<(), ChainE
...
+        Transaction::EIP4844Transaction(_) => apply_blob_transaction(head, context, block_cache),
+        _ => apply_plain_transaction(head, context, block_cache),
     }
 }
 
 /// Runs a blob transaction, updates the gas count & blob data and returns the receipt
 fn apply_blob_transaction(
     head: &HeadTransaction,
     context: &mut PayloadBuildContext,
+    block_cache: &mut HashMap<Address, Account>,
```
Comment (lima-limon-inc) [inline crates/blockchain/payload.rs:475]:
```suggestion
    block_cache: &mut CacheDB,
```

File: crates/blockchain/payload.rs [hunk 11]
```diff
@@ -444,41 +510,148 @@ fn apply_blob_transaction(
...
-        .apply_account_updates(context.parent_hash(), &account_updates)?
-        .unwrap_or_default();
-    context.payload.header.transactions_root =
-        compute_transactions_root(&context.payload.body.transactions);
-    context.payload.header.receipts_root = compute_receipts_root(&context.receipts);
-    context.payload.header.gas_used = context.payload.header.gas_limit - context.remaining_gas;
-    Ok(())
+fn finalize_payload(
+    context: &mut PayloadBuildContext,
+    block_cache: &mut HashMap<Address, Account>,
```
Comment (lima-limon-inc) [inline crates/blockchain/payload.rs:583]:
```suggestion
    block_cache: &mut CacheDB,
```

File: crates/blockchain/payload.rs [hunk 12]
```diff
@@ -444,41 +510,148 @@ fn apply_blob_transaction(
...
+) -> Result<(), StoreError> {
+    #[cfg(feature = "levm")]
+    {
+        if let Some(withdrawals) = &context.payload.body.withdrawals {
+            // For every withdrawal we increment the target account's balance
+            for (address, increment) in withdrawals
+                .iter()
+                .filter(|withdrawal| withdrawal.amount > 0)
+                .map(|w| (w.address, u128::from(w.amount) * u128::from(GWEI_TO_WEI)))
+            {
```
Comment (lima-limon-inc) [inline crates/blockchain/payload.rs:593]: Very nice!!

File: crates/blockchain/payload.rs [hunk 13]
```diff
@@ -444,41 +510,148 @@ fn apply_blob_transaction(
...
+                        .get_account_code(acc_info.code_hash)?
+                        .unwrap_or_default();
+
+                    Account {
+                        info: AccountInfo {
+                            balance: acc_info.balance,
+                            bytecode: acc_code,
+                            nonce: acc_info.nonce,
+                        },
+                        storage: HashMap::new(), // this must be changed, get the storage from the DB
```
Comment (lima-limon-inc) [inline crates/blockchain/payload.rs:613]: What do you think of this:
```suggestion
                        // TODO: this must be changed, get the storage from the DB.
                        // See: https://github.com/lambdaclass/ethrex/issues/1853
                        storage: HashMap::new(),
```

So others seeing the code can have a quick access to the issue?

**Review by lima-limon-inc — APPROVED** [review]
Very nice 😊! Left some small comments regarding the use of the CacheDB.

**Comment by tomip01** [comment]
I reverted changes suggested by @lima-limon-inc from changing `HashMap<Address, Account>` to `CacheDb` because with the feature flag "levm" not activated we don't use the levm crate, causing it to fail to compile

File: crates/blockchain/payload.rs [hunk 14]
```diff
@@ -8,17 +8,41 @@ use ethrex_core::{
...
+use ethrex_levm::Account;
+
+#[cfg(feature = "levm")]
+use ethrex_core::types::GWEI_TO_WEI;
+
+#[cfg(feature = "levm")]
+use std::sync::Arc;
+
+#[cfg(not(feature = "levm"))]
 use ethrex_vm::{
```
Comment (fmoletta) [inline crates/blockchain/payload.rs:36]: Nitpicking, but maybe we can use a single `use` statement for imports under each feature as to not have so many feature directives, something like:
```
#[cfg(feature = "levm")]
use {
  etc
}
#[cfg(not(feature = "levm"))]
use {
  etc
}
```

File: crates/blockchain/payload.rs [hunk 15]
```diff
@@ -444,41 +510,150 @@ fn apply_blob_transaction(
 fn apply_plain_transaction(
     head: &HeadTransaction,
     context: &mut PayloadBuildContext,
+    block_cache: &mut HashMap<Address, Account>,
```
Comment (fmoletta) [inline crates/blockchain/payload.rs:513]: The block_cache is what levm uses instead of the `EvmState` in revm right? Could we add it to the `PayloadBuildContext` in place of it? 
Something like:
```
pub struct PayloadBuildContext<'a> {
    pub payload: &'a mut Block,
    #[cfg(not(feature = "levm"))]
    pub evm_state: &'a mut EvmState,
    #[cfg(feature = "levm)]
    block_cache: &mut HashMap<Address, Account>,
    pub remaining_gas: u64,
    pub receipts: Vec<Receipt>,
    pub block_value: U256,
    base_fee_per_blob_gas: U256,
    pub blobs_bundle: BlobsBundle,
}
```
That way we can keep most logic between both features more similar

File: crates/blockchain/payload.rs [hunk 16]
```diff
@@ -444,41 +510,150 @@ fn apply_blob_transaction(
...
+            compute_transactions_root(&context.payload.body.transactions);
+        context.payload.header.receipts_root = compute_receipts_root(&context.receipts);
+        context.payload.header.gas_used = context.payload.header.gas_limit - context.remaining_gas;
+        Ok(())
+    }
+    #[cfg(not(feature = "levm"))]
+    {
+        let account_updates = get_state_transitions(context.evm_state);
+        // Note: This is commented because it is still being used in development.
+        // dbg!(&account_updates);
```
Comment (fmoletta) [inline crates/blockchain/payload.rs:645]: Please remove

File: crates/blockchain/payload.rs (hunk 14 above)
Comment (tomip01) [reply crates/blockchain/payload.rs]: Nice! done here [e9e2fc0](https://github.com/lambdaclass/ethrex/pull/1817/commits/e9e2fc01cd0bc61c0d77899989fdd472bd58c906)

File: crates/blockchain/payload.rs (hunk 16 above)
Comment (tomip01) [reply crates/blockchain/payload.rs]: Done, [7cef0db](https://github.com/lambdaclass/ethrex/pull/1817/commits/7cef0db7ff1e1e04e0d4ccee63bfde346756804e)

File: crates/blockchain/payload.rs (hunk 15 above)
Comment (tomip01) [reply crates/blockchain/payload.rs:507]: Currently in LEVM we use the state to get to the database, I think in the future it will change. 
I agree that adding the block_cache to the context is better

Comment (tomip01) [reply crates/blockchain/payload.rs]: Done here [0029844](https://github.com/lambdaclass/ethrex/pull/1817/commits/0029844c11a00112d86322fc82c590899327a1c7)

File: crates/blockchain/payload.rs (hunk 2 above)
Comment (tomip01) [reply crates/blockchain/payload.rs]: Solved, here [09f8403](https://github.com/lambdaclass/ethrex/pull/1817/commits/09f84033766104bd7240e5115a13961bfaa94f3e)

**Review by fmoletta — APPROVED** [review]
🚀

File: crates/blockchain/payload.rs [hunk 17]
```diff
@@ -445,40 +501,143 @@ fn apply_plain_transaction(
...
+            &head.tx,
+            &context.payload.header,
+            store_wrapper.clone(),
+            context.block_cache.clone(),
+            context
+                .chain_config()
+                .map_err(ChainError::from)?
+                .fork(context.payload.header.timestamp),
+        )
+        .map_err(|e| EvmError::Transaction(format!("Invalid Transaction: {:?}", e)))?;
```
Comment (ilitteri) [inline crates/blockchain/payload.rs:521]: Nit.
```suggestion
        .map_err(|e| EvmError::Transaction(format!("Invalid Transaction: {e:?}")))?;
```

**Review by ilitteri — APPROVED** [review]
