### PR TITLE
fix(l1): increase max_fee_per_gas to avoid blocks with 0 txs in load test

### LINKED ISSUE #2523: Why are there empty blocks in load tests?
When we execute load tests against ethrex we see that empty blocks are produced. Why does that happen? Is it because a block takes too much time to build? Is it a concurrency problem? Is there too much waiting for something that is locked behind a mutex?

### PR DESCRIPTION
**Pull request by edg-l**
**Motivation**

Due to feeding so many txs, the base fee keeps increasing so when it goes beyond the load test txs max fee per gas, the block will have 0 txs due to them all having the same max fee per gas.

This pr increasing the load test max fee per has to u64 MAX and lowers priority fee per gas to decreasing (realistically removing) the chance of 0 block txs in load tests

**Description**

Closes #2523

### CODE REVIEW

File: cmd/load_test/src/main.rs [hunk 1]
```diff
@@ -246,8 +246,8 @@ async fn load_test(
                             chain_id: Some(chain_id),
                             value,
                             nonce: Some(nonce + i),
-                            max_fee_per_gas: Some(3121115334),
-                            max_priority_fee_per_gas: Some(3000000000),
+                            max_fee_per_gas: Some(u64::MAX),
+                            max_priority_fee_per_gas: Some(10),
```
Comment (mpaulucci) [inline cmd/load_test/src/main.rs:250]: why 10?

Comment (edg-l) [reply cmd/load_test/src/main.rs:250]: i just lowered it to an arbitrary number, do you have a suggestion?

**Review by jrchatruc — APPROVED** [review]

**Review by ilitteri — APPROVED** [review]
