### PR TITLE
fix(l2): ignore deposits after state reconstruction

### LINKED ISSUE #1279: L2: improve and refactor `l1_watcher`
The `l1_watcher` requires some changes. 
When the `proposer` is restarted, the `l1_watcher` processes all the events, resulting in duplicated `deposit` transactions. 
This behavior was observed when depositing the same amount twice. It may be related just to Issue #1191, or perhaps additional logic is required.
 
TaskList:
- [x] #1191

### PR DESCRIPTION
**Pull request by avilagaston9**
**Motivation**

Currently, If we start our l2 node with a reconstructed state, the node will process all deposit logs from l1 and mint them again in l2. This is because, in a reconstructed store, we don't have the included transactions to determine whether a deposit was previously processed or not.

**Description**

- Fixes the reconstruct algorithm to start from batch_number=1.
- Fixes the `l2MintTxHash` emitted in the `CommonBridge` contract.
- Adds an additional check to the `integration_test` to wait for the deposit receipt on L2.
- Reuses the emitted `l2MintTxHash` instead of recalculating it in the watcher.
- Checks, in the `CommonBridge` contract, whether a deposit is pending or not before minting the transaction.
- Creates `DepositData` struct in `l1_watcher`

### How to test

Here we are going to run the integration test on a node with a reconstructed state.
You may want to lower the `commit_time_ms`.

1. Start the prover and network  with:

```
make init-prover
make init
```

2. Wait until batch 6 is verified and stop the l2 node with `ctrl + c`:

```
INFO ethrex_l2::sequencer::l1_proof_sender: Sent proof for batch 6...
ctrl + c
```

> [!NOTE]
> This is because we are going to use already created blobs with 6 batches and we need
> to advance the L1 until that point.

3. Clean db:

```
make rm-db-l2
```

4. Reconstruct the state choosing a `path_to_store`:
```
cargo run --release --manifest-path ../../cmd/ethrex_l2/Cargo.toml --bin ethrex_l2 -- stack reconstruct -g ../../test_data/genesis-l2.json -b ../../test_data/blobs/ -s path_to_store -c 0x0007a881CD95B1484fca47615B64803dad620C8d
```

5. Start the l2 node using `path_to_store`:

```
make init-l2 ethrex_L2_DEV_LIBMDBX=path_to_store
```

You should observe that all deposits are skipped now.

6. In a new terminal, run the integration test:

```
cd crates/l2
make test
```

> [!WARNING]
> Before running the integration test, wait for 20 blocks to be built in the L2.
> This is because the test currently uses [estimate_gas_tip](https://github.com/lambdaclass/ethrex/blob/aa3c41b8da043ff5cd1ad699ce882c41edefc460/crates/networking/rpc/eth/fee_calculator.rs#L30) that needs at least 20 blocks to estimate the gas price.

Closes #1279

### CODE REVIEW

File: cmd/ethrex_l2/src/commands/stack.rs [hunk 1]
```diff
@@ -202,7 +202,7 @@ impl Command {
                 .await?;
                 let rollup_store = StoreRollup::new(
                     store_path
-                        .join("../rollup_store")
+                        .join("./rollup_store")
```
Comment (ilitteri) [inline cmd/ethrex_l2/src/commands/stack.rs:205]: Create an issue to make this an `ethrex_l2 stack reconstruct` flag.

File: crates/l2/contracts/src/l1/CommonBridge.sol
Comment (ilitteri) [inline crates/l2/contracts/src/l1/CommonBridge.sol:1]: Remember to update all the default values for the CREATE2 address for this contract (nowadays we need to do this by hand, but there's an issue for addressing multiple default address definitions).

File: crates/l2/sequencer/l1_watcher.rs [hunk 2]
```diff
@@ -150,33 +150,28 @@ impl L1Watcher {
...
+        for log in logs {
+            let (
+                mint_value,
+                to_address,
+                deposit_id,
+                recipient,
+                from,
+                gas_limit,
+                calldata,
+                deposit_hash,
```
Comment (tomip01) [inline crates/l2/sequencer/l1_watcher.rs:168]: what do you think of using a struct for this elements?
Something like `DepositValues`

**Review by tomip01 — APPROVED** [review]

**Review by ilitteri — DISMISSED** [review]

File: cmd/ethrex_l2/src/commands/stack.rs (hunk 1 above)
Comment (avilagaston9) [reply cmd/ethrex_l2/src/commands/stack.rs:205]: Maybe we could rename `store_path` to `data_dir` and place both `store` and `rollup_store` under that directory?

File: crates/l2/contracts/src/l1/CommonBridge.sol
Comment (avilagaston9) [reply crates/l2/contracts/src/l1/CommonBridge.sol:1]: Updated in [75c2188](https://github.com/lambdaclass/ethrex/pull/2642/commits/75c21883b2421914384e717fefceb2fbeffe36e8)!

File: crates/l2/tests/tests.rs
Comment (ilitteri) [inline crates/l2/tests/tests.rs:1]: We should do `3.` in the other tests.

**Review by ilitteri — CHANGES_REQUESTED** [review]

File: crates/l2/sequencer/l1_watcher.rs [hunk 3]
```diff
@@ -150,33 +150,28 @@ impl L1Watcher {
...
-            let deposit_already_processed = store
-                .get_transaction_by_hash(deposit_hash)
-                .await
-                .map_err(L1WatcherError::FailedAccessingStore)?
-                .is_some();
+        // Get the pending deposits from the contract.
+        let pending_deposits = self
+            .eth_client
+            .get_pending_deposit_logs(self.address)
+            .await?;
```
[the remark this answers is not in the document]
Comment (avilagaston9) [reply crates/l2/sequencer/l1_watcher.rs]: Done in [c5512fe](https://github.com/lambdaclass/ethrex/pull/2642/commits/c5512feec38cbc6d3148c91df55b93a7864d2b67)!

File: cmd/ethrex_l2/src/commands/stack.rs (hunk 1 above)
Comment (ilitteri) [reply cmd/ethrex_l2/src/commands/stack.rs:205]: Works for me.

Comment (avilagaston9) [reply cmd/ethrex_l2/src/commands/stack.rs:205]: Created #2656

File: crates/l2/sequencer/l1_watcher.rs (hunk 2 above)
Comment (avilagaston9) [reply crates/l2/sequencer/l1_watcher.rs]: Created `DepositData` here [75e327e](https://github.com/lambdaclass/ethrex/pull/2642/commits/75e327eb52f1a619002f887826f9b66e6416ccc1)

File: crates/l2/tests/tests.rs
Comment (avilagaston9) [reply crates/l2/tests/tests.rs:1]: Addressed in [1201ab4](https://github.com/lambdaclass/ethrex/pull/2642/commits/1201ab43667388b687c287ea528476db878019da)!

**Review by ilitteri — APPROVED** [review]
