### PR TITLE
fix(levm): fix eip-150's balance & extcodesize

### LINKED ISSUE #1892: Add support for the `stEIP150singleCodeGasPrices` test suite
After adding the [LegacyTest](https://github.com/ethereum/legacytests/tree/b2e6c9e43ede7eec9c5b2997c14a892e7eb2f124), new folders containing tests for Pre-Cancun forks were added.
Currently the state of folder `stEIP150singleCodeGasPrices` is:
```
stEIP150singleCodeGasPrices: 56/161 (34.78%)
```
We want to make it 100%

Eip 150 states:

- [x] Increase the gas cost of EXTCODESIZE to 700 (from 20).
- [x] Increase the base gas cost of EXTCODECOPY to 700 (from 20).
- [x] Increase the gas cost of BALANCE to 400 (from 20).
- [x] Increase the gas cost of SLOAD to 200 (from 50).
- [ ] Increase the gas cost of CALL, DELEGATECALL, CALLCODE to 700 (from 40).
- [x] Increase the gas cost of SELFDESTRUCT to 5000 (from 0).
- [x] If SELFDESTRUCT hits a newly created account, it triggers an additional gas cost of 25000 (similar to CALLs).
- [ ] Increase the recommended gas limit target to 5.5 million.
- [x] Define “all but one 64th” of N as N - floor(N / 64).
- [ ] If a call asks for more gas than the maximum allowed amount (i.e. the total amount of gas remaining in the parent after subtracting the gas cost of the call and memory expansion), do not return an OOG error; instead, if a call asks for more gas than all but one 64th of the maximum allowed amount, call with all but one 64th of the maximum allowed amount of gas (this is equivalent to a version of EIP-901 plus EIP-1142). CREATE only provides all but one 64th of the parent gas to the child call.

### LINKED ISSUE #1906: Fix BALANCE and EXTCODESIZE instructions in Legacy Tests

### PR DESCRIPTION
**Pull request by lima-limon-inc**
**Motivation**

After adding the Legacy Tests, new folders containing tests for Pre-Cancun forks were added. This PR fixes some of the new EF-Tests.
  
**Description**
This incorporates _some_ of the changes incuded in eip-150. Notably: 
- [X] Increase the gas cost of EXTCODESIZE to 700 (from 20).
- [x] Increase the gas cost of BALANCE to 400 (from 20).

Closes #1906

### CODE REVIEW

File: crates/vm/levm/src/gas_cost.rs [hunk 1]
```diff
@@ -628,13 +630,19 @@ pub fn balance(address_was_cold: bool) -> Result<u64, VMError> {
...
+    } else if fork >= Fork::Tangerine && fork < Fork::Cancun {
+        Ok(EXTCODESIZE_TANGERINE)
+    } else {
+        address_access_cost(
+            address_was_cold,
+            EXTCODESIZE_STATIC,
+            EXTCODESIZE_COLD_DYNAMIC,
+            EXTCODESIZE_WARM_DYNAMIC,
+        )
+    }
```
Comment (fkrause98) [inline crates/vm/levm/src/gas_cost.rs:645]: Maybe here we can do something like:

```rust
match fork {
    f if f < Fork::Tangerine => Ok(EXTCODESIZE_PRE_TANGERINE),
    f if f >= Fork::Tangerine && f < Fork::Cancun => Ok(EXTCODESIZE_TANGERINE),
    _ => address_access_cost(
        address_was_cold,
        EXTCODESIZE_STATIC,
        EXTCODESIZE_COLD_DYNAMIC,
        EXTCODESIZE_WARM_DYNAMIC,
    ),
}
```

**Review by fkrause98 — APPROVED** [review]

**Review by tomip01 — APPROVED** [review]
LGTM

**Comment by lima-limon-inc** [comment]
I merged this since it fixed ~90 tests and in order to to get it in the main branch to avoid future conflicts
