### PR TITLE
test(l1): check if vm state reverts correctly on error

### LINKED ISSUE #2604: Check state is reverted on transaction failure
Per the instructions of the [ethereum state test docs](https://eest.ethereum.org/v3.0.0/consuming_tests/state_test/), we should be checking whether the state is equal to the pre-state when the execution throws an exception. We aren't doing so currently, and we probably really should.

### PR DESCRIPTION
**Pull request by cdiielsi**
**Motivation**

Per the instructions of the [ethereum state test docs](https://eest.ethereum.org/v3.0.0/consuming_tests/state_test/), we should be reverting to the pre-state when the execution throws an exception. Levm does this, but it's not asserted in the test runner in the case an exception is expected.

**Description**

This pr introduces a new error to check if the state was reverted correctly in the case an exception must occur, or throw error otherwise. To check if the state was correctly reverted I'm using the post state hash from the tests and comparing it with the hash of the account's latest state recorded in the db.

Closes #2604

### CODE REVIEW

File: cmd/ef_tests/state/runner/levm_runner.rs [hunk 1]
```diff
@@ -397,6 +400,23 @@ pub async fn ensure_post_state(
...
+                        .map_err(|_| {
+                            InternalError::Custom(
+                                "Error at LEVM::get_state_transitions in ensure_post_state()"
+                                    .to_owned(),
+                            )
+                        })?;
+                    let vector_post_value = test.post.vector_post_value(vector, *fork);
+
+                    // Compare the post-state root hash with the expected post-state root hash to ensure levm state is correct (was reverted)
+                    if vector_post_value.hash != post_state_root(&levm_account_updates, test).await
```
Comment (mpaulucci) [inline cmd/ef_tests/state/runner/levm_runner.rs:414]: we had this in revm but not in levm?? this is a basic check

File: cmd/ef_tests/state/runner/levm_runner.rs [hunk 2]
```diff
@@ -397,6 +400,23 @@ pub async fn ensure_post_state(
...
+                    {
+                        return Err(EFTestRunnerError::FailedToRevertLEVMState(
+                            "Failed to revert LEVM state".to_string(),
+                        ));
+                    }
```
Comment (SDartayet) [inline cmd/ef_tests/state/runner/levm_runner.rs:419]: Maybe a diff could be useful when the post state root doesn't match? Might be a bit out of scope for this PR, but I think we do it already when the post state root doesn't otherwise match, so it shouldn't be too difficult to implement. Feel free to open a separate issue if you think it'd be appropriate though.

**Review by SDartayet — APPROVED** [review]
Looks good! Just a small comment

File: cmd/ef_tests/state/runner/levm_runner.rs (hunk 1 above)
Comment (cdiielsi) [reply cmd/ef_tests/state/runner/levm_runner.rs:414]: This is not done in revm, neither in [ensure_post_state](https://github.com/lambdaclass/ethrex/blob/6f1bb69882588a4b55ed0e7aa4c20b5c5268f6fd/cmd/ef_tests/state/runner/revm_runner.rs#L374-L376)  when comparing levm vs revm results:
```
    match test.post.vector_post_value(vector, *fork).expect_exception {
        Some(_expected_exception) => {}
        // We only want to compare account updates when no exception is expected.
```
nor in [_ensure_post_state_revm](https://github.com/lambdaclass/ethrex/blob/6f1bb69882588a4b55ed0e7aa4c20b5c5268f6fd/cmd/ef_tests/state/runner/revm_runner.rs#L587-L591) when running only for revm on revm_runner.rs:
```
            match test.post.vector_post_value(vector, *fork).expect_exception {
                // Execution result was unsuccessful and an exception was expected.
                // TODO: See if we want to map revm exceptions to expected exceptions, probably not.
                Some(_expected_exception) => {}
```

File: cmd/ef_tests/state/runner/levm_runner.rs [hunk 3]
```diff
@@ -72,6 +72,9 @@ pub async fn run_ef_test(test: &EFTest) -> Result<EFTestReport, EFTestRunnerErro
                     ef_test_report_fork
                         .register_post_state_validation_error_mismatch(reason, *vector);
                 }
+                Err(EFTestRunnerError::FailedToRevertLEVMState(reason)) => {
+                    ef_test_report_fork.register_vm_initialization_failure(reason, *vector);
```
Comment (JereSalo) [inline cmd/ef_tests/state/runner/levm_runner.rs]: I suggest you change this. This is not a VM Initialization Failure. Look at the code of that function:
```rust
pub fn register_vm_initialization_failure(
        &mut self,
        reason: String,
        failed_vector: TestVector,
    ) {
        self.failed_vectors.insert(
            failed_vector,
            EFTestRunnerError::VMInitializationFailed(reason),
        );
    }
```
We should only use that if the initialization of the VM fails, but this is an execution problem.
You can create another function if you want to

File: cmd/ef_tests/state/runner/levm_runner.rs (hunk 2 above)
Comment (cdiielsi) [reply cmd/ef_tests/state/runner/levm_runner.rs:419]: That would be good! But I think it might go beyond the scope of this pr. Currently in the other cases when there's a root mismatch there's only a comparison between the keccak of logs with the test's expected logs hash. Then, If we run a comparison with revm, we have a diff between the two resulting states of the vms in case they are different. But we are not comparing against the tests.
The thing is, currently when parsing the tests' post state from the json files we are not parsing the account final state, only the hash. So to make a diff now I'll have to modify the deserializer, also taking into account that not all tests have the accounts state in the post state, some of the tests only have the post state hash.

File: cmd/ef_tests/state/runner/levm_runner.rs (hunk 3 above)
Comment (cdiielsi) [reply cmd/ef_tests/state/runner/levm_runner.rs]: Sorry! I used it earlier in the branch's first changes to have everything running and I forgot to fix it! I'm changing it now! I'll include a new function.

File: cmd/ef_tests/state/report.rs [hunk 4]
```diff
@@ -548,6 +548,17 @@ impl EFTestReportForkResult {
         );
     }
 
+    pub fn register_post_state_validation_error_state_root_mismatch(
```
Comment (fmoletta) [inline cmd/ef_tests/state/report.rs]: I find this naming confusing, how is state root mismatch related to a failure to revert the state?

Comment (cdiielsi) [reply cmd/ef_tests/state/report.rs]: I thought of it in the terms of another function's name but reading it again, I think I got mixed up with the grammar. There's this function: `register_post_state_validation_error_mismatch`, here you register the validation of a post state in which there's an error mismatch, and what I was thinking is that this function should register the validation of a post state in which there's a state root mismatch on an error. Should I change it for register_post_state_validation_state_root_mismatch_on_error ?

Comment (JereSalo) [inline cmd/ef_tests/state/report.rs]: See if you find a better name for this haha. Doesn't necessarily have to contain the state_root_mismatch part because that's an implementation detail. Just a name that indicates that we failed to revert the state when an exception occurred.

**Review by JereSalo — APPROVED** [review]
