### PR TITLE
fix(l1): p2p pooled transactions

### LINKED ISSUE #1986: Fix PooledTransactions handler to fetch transactions from the mempool instead of the block bodies table
Currently the handler for the `PooledTransactions` message calls `get_p2p_transaction`, which fetches transactions from block bodies instead of the transaction pool (a.k.a mempool)

### PR DESCRIPTION
**Pull request by MarcosNicolau**
**Motivation**
Fix pooled transaction Hive tests in the engine-cancun suite.

**Description**
The issue was caused by incorrect transaction exchange with peers. The following fixes were applied:
1. Upon p2p connection and when receiving `send_rawTransaction`, we were not sending `NewPooledTranasctions` as expected. Added a new periodic task to check the mempool for new txs that we didn't broadcast to a peer and send `NewPooledTransactionHashes` if a there is a new tx that we haven't broadcast before. To keep track of the txs we sent a HashSet is added to the peer struct `RLPxConnection`
2. When responding to GetPooledTransactions, we were mistakenly sending stored transactions from previous blocks instead of the mempool.
3. The assertoor tests where failing because we were not removing the txs from the mempool that we broadcasted to the peers when they were included in a block proposed by a peer. Now after we accept a forkchoiceupdated, we remove the txs from the mempool. Also with other peers now proposing blocks with txs we need to increment the amount of time we wait for our client to propose a block with 240 txs in the test
4. Locking the mempool for every peer every time we need to check if we have new transactions could lead to problems as we need to wait for the lock to be released for every peer, to avoid this the `Mutex` we used for the mempool in `Store` struct is replaced with a `RwLock` which allows for multiple read locks.

Considerations:
- We should track sent transactions within the peer connection to avoid resending the same ones.
- According to rust's documentation, the RwLock's policy is dependant on the operating system's implementation maybe we should use tokio's RwLock implementation that is fair or write-preferring to avoid the problem of the mempool not being able to add new transactions if we constantly hold read locks.

References:
1. Transaction exchange spec: https://github.com/ethereum/devp2p/blob/master/caps/eth.md#transaction-exchange
2. New Pooled transactions: https://github.com/ethereum/devp2p/blob/master/caps/eth.md#newpooledtransactionhashes-0x08
3. Rust RwLock https://doc.rust-lang.org/std/sync/struct.RwLock.html
4. Tokio RwLock https://docs.rs/tokio/latest/tokio/sync/struct.RwLock.html

Closes #1986 
Advances #285

### CODE REVIEW

File: crates/storage/store/store.rs [hunk 1]
```diff
@@ -608,6 +608,20 @@ impl Store {
         self.engine.get_transaction_by_hash(transaction_hash)
     }
 
+    pub fn get_transaction_by_hash_from_mempool(
```
Comment (rodrigo-o) [inline crates/storage/store/store.rs:611]: NP: for consistency it appears that we used pool instead of mempool for function names like: `add_transaction_to_pool` and `remove_transaction_from_pool`, so probably better `get_transaction_by_hash_from_pool`

File: crates/networking/p2p/rlpx/connection.rs [hunk 2]
```diff
@@ -329,6 +338,52 @@ impl<S: AsyncWrite + AsyncRead + std::marker::Unpin> RLPxConnection<S> {
...
+                        "Failed to lock mempool".to_string(),
+                    ))
+                })?
+                .iter()
+            {
+                if !self.broadcasted_txs.contains(hash) {
+                    hashes.push(*hash);
+                    txs.push((**mempool_tx).clone());
+                }
+            }
```
Comment (rodrigo-o) [inline crates/networking/p2p/rlpx/connection.rs:368]: This is the only occurrence of `mempool.read/write` outside of the storage, probably we want to encapsulate the locking there as already done with other add/remove/filter functions in the store, something like: `pub fn filter_pool_transactions(filter)`.

File: crates/networking/rpc/engine/fork_choice.rs [hunk 3]
```diff
@@ -200,12 +200,31 @@ fn handle_forkchoice(
...
-        Ok(head) => Ok((
-            Some(head),
-            ForkChoiceResponse::from(PayloadStatus::valid_with_hash(
-                fork_choice_state.head_block_hash,
-            )),
-        )),
+        Ok(head) => {
+            // Remove included transactions from the mempool after we accept the fork choice
+            // This implementation could be incomplete
+            // See https://github.com/lambdaclass/ethrex/issues/797
```
Comment (rodrigo-o) [inline crates/networking/rpc/engine/fork_choice.rs:206]: NP: We've been following the TODO(#NNNN) syntax which is useful for later lookup:

```rust
// TODO(#797): The remove of transactions from the mempool could be incomplete (i.e. REORGS)
```

File: crates/networking/rpc/engine/fork_choice.rs [hunk 4]
```diff
@@ -200,12 +200,31 @@ fn handle_forkchoice(
...
+            if let Ok(Some(block)) = context.storage.get_block_by_hash(head.compute_block_hash()) {
+                let mut mempool =
+                    context.storage.mempool.write().map_err(|err| {
+                        RpcErr::Internal(format!("Failed to lock mempool: {err}",))
+                    })?;
+                for tx in block.body.transactions {
+                    mempool.remove(&tx.compute_hash());
+                }
```
Comment (rodrigo-o) [inline crates/networking/rpc/engine/fork_choice.rs:214]: We might want to also encapsulate this in the store to avoid locking the mempool manually. We can go with `remove_transactions_from_pool(filter)` or something similar.

**Review by rodrigo-o — COMMENTED** [review]
I left a couple of comments specially related to the leak of the mempool lock outside of the store!

File: crates/networking/rpc/engine/fork_choice.rs (hunk 3 above)
Comment (LeanSerra) [reply crates/networking/rpc/engine/fork_choice.rs]: Done in [change comment to follow internal convention](https://github.com/lambdaclass/ethrex/pull/1990/commits/d8c8b6d67ceac323cfcd4c301afed92998b16b27)

File: crates/storage/store/store.rs (hunk 1 above)
Comment (LeanSerra) [reply crates/storage/store/store.rs]: Done in [change name of function](https://github.com/lambdaclass/ethrex/pull/1990/commits/2772f90d32eca9b8b82bffbebe04fa89186beb28)

File: crates/networking/rpc/engine/fork_choice.rs (hunk 4 above)
Comment (LeanSerra) [reply crates/networking/rpc/engine/fork_choice.rs]: Done [encapsulate removing transactions from pool](https://github.com/lambdaclass/ethrex/pull/1990/commits/a1db7d03c7151deabeb024719aee17183be9e74d)

Comment (LeanSerra) [reply crates/networking/rpc/engine/fork_choice.rs]: Also added errors relating to locking the mempool in [add errors to StoreError](https://github.com/lambdaclass/ethrex/pull/1990/commits/960acc6a95add4b04651152013fb28a51d832b63)

File: crates/networking/p2p/rlpx/connection.rs (hunk 2 above)
Comment (LeanSerra) [reply crates/networking/p2p/rlpx/connection.rs]: There was already a function that did something similar and was also named `filter_pool_transactions(filter)` so I decided to use that, the only drawback I see with using it is that we have to recalculate the hashes for every tx now.

This is the commit [use existing filter_pool_transactions](https://github.com/lambdaclass/ethrex/pull/1990/commits/6c99d96d8c64555d26f91dc49d24c3a3c6a99207)

Comment (rodrigo-o) [reply crates/networking/p2p/rlpx/connection.rs]: Good callout, we can go with this for now leaving a comment that we already have the hash and this could be improved if we have perf issues in the future.

File: crates/networking/rpc/engine/fork_choice.rs (hunk 4 above)
Comment (rodrigo-o) [reply crates/networking/rpc/engine/fork_choice.rs]: Awesome!

**Review by rodrigo-o — APPROVED** [review]
🚀

File: crates/networking/p2p/rlpx/connection.rs [hunk 5]
```diff
@@ -305,9 +315,11 @@ impl<S: AsyncWrite + AsyncRead + std::marker::Unpin> RLPxConnection<S> {
                     self.handle_broadcast(broadcasted_msg?).await?
                 }
                 // Allow an interruption to check periodic tasks
-                _ = sleep(PERIODIC_TASKS_CHECK_INTERVAL) => () // noop
+                _ = sleep(PERIODIC_TASKS_CHECK_INTERVAL) => (), // noop
+                _ = sleep(BROADCAST_TX_FROM_MEMPOOL_INTERVAL) => ()
```
Comment (avilagaston9) [inline crates/networking/p2p/rlpx/connection.rs:319]: I would set `PERIODIC_TASKS_CHECK_INTERVAL=5` and reuse `check_periodic_tasks()` , but it might be a matter of taste.

File: crates/storage/store/store.rs [hunk 6]
```diff
@@ -608,6 +619,20 @@ impl Store {
...
     }
 
+    pub fn get_transaction_by_hash_from_pool(
+        &self,
+        transaction_hash: H256,
+    ) -> Result<Option<Transaction>, StoreError> {
+        let tx = self
+            .mempool
+            .read()
+            .unwrap()
```
Comment (avilagaston9) [inline crates/storage/store/store.rs:629]:
```suggestion
            .map_err(|error| StoreError::Custom(error.to_string()))?
```

**Review by avilagaston9 — APPROVED** [review]
Just a few nits

File: crates/storage/store/store.rs (hunk 6 above)
Comment (LeanSerra) [reply crates/storage/store/store.rs]: Nice catch! Done in [remove unwrap](https://github.com/lambdaclass/ethrex/pull/1990/commits/4346480d54bb1a0fb71c5ce028efbe36bbcc9889)

File: crates/networking/p2p/rlpx/connection.rs (hunk 5 above)
Comment (LeanSerra) [reply crates/networking/p2p/rlpx/connection.rs:319]: I can make that change, but do you know if its possible that the change would cause issues if we are "spamming" our peers with `ping` commands every 5 seconds instead of 10?

Comment (LeanSerra) [reply crates/networking/p2p/rlpx/connection.rs]: Makes sense, I implemeted that here [move periodic broadcast logic to check_periodic_tasks](https://github.com/lambdaclass/ethrex/pull/1990/commits/b57d97db6b0cdff406e079b666cb69032be45133)

**Review by avilagaston9 — APPROVED** [review]
