### PR TITLE
fix(l1): peer scoring to avoid syncing hanging in holesky

### LINKED ISSUE #3020: Sync failed due to missing bodies takes as much as normal batchs
Investigating another issue I found that after a particular moment in the sync of Holesky I got lots of these. This was added in [this PR](https://github.com/lambdaclass/ethrex/pull/2658), I think the issue is directly related to Holesky's fork to prague (which match the time it started with 3.3m block numbers, but I want to be sure this was not an issue introduced for the whole network.

We need to make sure this just happens at the prague fork and if that's the case then we could be sure the issue is mostly related to peers sending invalid bodies. If it could be replicated (No bodies issue lasting more than 2 secs) consistently across the syncing then this is a performance issue. Here the logs

```
2025-05-27T14:15:01.307448Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1 secs 
2025-05-27T14:15:03.048326Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1 secs 
2025-05-27T14:15:08.028340Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1 secs 
2025-05-27T14:16:19.220912Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 2 secs 
2025-05-27T14:16:42.671106Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 2 secs 
2025-05-27T14:16:51.558054Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1 secs 
2025-05-27T14:17:02.306201Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1 secs 
2025-05-27T14:17:15.825659Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1 secs 
2025-05-27T14:17:26.969641Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1 secs 
2025-05-27T14:17:40.891566Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 3 secs 
2025-05-27T14:17:52.501127Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 2 secs 
2025-05-27T14:18:02.743733Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1 secs 
2025-05-27T14:18:17.758505Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 2 secs 
2025-05-27T14:18:27.616982Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 2 secs 
2025-05-27T14:18:41.108122Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 2 secs 
2025-05-27T14:18:51.482527Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1 secs 
2025-05-27T14:19:02.899660Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1 secs 
2025-05-31T00:23:50.711096Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1116 secs 
2025-05-31T00:48:40.228952Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 40 secs 
2025-05-31T01:06:50.019708Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 483 secs 
2025-05-31T01:53:18.166392Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 846 secs 
2025-05-31T02:38:02.333766Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 834 secs 
2025-05-31T03:27:16.855768Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 2240 secs 
2025-05-31T03:49:13.003032Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 501 secs 
2025-05-31T04:00:20.934316Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 667 secs 
2025-05-31T04:25:45.393050Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 755 secs 
2025-05-31T04:42:52.309863Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 260 secs 
2025-05-31T04:47:03.361273Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 241 secs 
2025-05-31T05:13:33.811158Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1579 secs 
2025-05-31T05:28:53.878723Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 717 secs 
2025-05-31T06:02:26.705056Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1577 secs 
2025-05-31T06:13:46.968035Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 666 secs 
2025-05-31T06:19:19.954752Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 329 secs 
2025-05-31T06:31:44.310145Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 739 secs 
2025-05-31T06:32:27.899423Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 38 secs 
2025-05-31T06:39:25.727916Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 408 secs 
2025-05-31T06:46:17.238332Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 377 secs 
2025-05-31T06:59:07.378682Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 376 secs 
2025-05-31T07:00:28.437334Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 76 secs 
2025-05-31T07:09:10.124511Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 511 secs 
2025-06-02T19:38:11.836563Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1 secs 
2025-06-02T19:38:38.721810Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 18 secs 
2025-06-02T19:39:09.508062Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 20 secs 
2025-06-02T19:41:05.036165Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1 secs 
2025-06-02T19:46:55.739605Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 342 secs 
2025-06-02T19:47:28.367134Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 26 secs 
2025-06-02T19:47:42.077553Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1 secs 
2025-06-02T19:47:54.502958Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 4 secs 
2025-06-02T19:48:13.031471Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 3 secs 
2025-06-02T19:48:40.932294Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 2 secs 
2025-06-02T19:48:49.472423Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 1 secs 
2025-06-02T19:49:19.752148Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 22 secs 
2025-06-02T19:51:03.058657Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 95 secs 
2025-06-02T20:01:36.421781Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 22 secs 
2025-06-02T20:10:28.869298Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 525 secs 
2025-06-02T20:16:08.243676Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 315 secs 
2025-06-02T20:16:20.295548Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 4 secs 
2025-06-02T20:19:32.199676Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 185 secs 
2025-06-02T20:20:13.682071Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 32 secs 
2025-06-02T20:27:36.938028Z  WARN ethrex_p2p::sync: Sync cycle failed due to No bodies were found for the given headers, time elapsed: 439 secs 
```

### PR DESCRIPTION
**Pull request by rodrigo-o**
**Motivation**

Syncing where being hanged in a loop, not being able to proceed at the bodies request stage

**Description**

The issue was related to an early return of an error when receiving no bodies from a peer (after the retries). This happen even if some peer was able to answer but we exhausted the retries with those who wont. We tried a couple of solutions:

- **Remove the error and just break with the accumulated bodies:** This proved to hurt the performance and just push the issue to the next iteration which also failed to accumulate the whole amount of bodies
- **Remove the peers that doesn't answer the bodies:** This proved to still fail when we end up with just one good active peer and for some reason it doesn't answer. In that case we removed it also and were unable to get more peers.
- **Remove the peer that doesn't answer and increase the timeouts:** It was possible that the issue with the good peer was related to the short timeout of 5 seconds, increasing this proved to be better thatn te previous solution but after a couple of houser the issue of having no peers still remained.

**Current solution:**

Now we implemented a initial version of a simple peer-scoring. This just adds a new score field to the peer data and use it to weight the peers when choosing them (instead of the previous random selection). In both headers and bodies request we penalize and reward peers given their responses. This could be further improved in other PRs (#3042) but it's enough for the current issue. After running the whole night 3 different times syncing from holesky's 3.6m there were no issues in sight! We also maintained the increased peer timeout from 5 to 15 secs.

Additionally I removed the marking of the sync head as invalid, something that shouldn't be needed in syncing (we are already marking the failing one, which could also be an issue but is tracked in #2767)

Closes #3020

### CODE REVIEW

File: crates/networking/p2p/sync.rs [hunk 1]
```diff
@@ -460,12 +464,8 @@ impl Syncer {
                     .set_latest_valid_ancestor(failed_block_hash, last_valid_hash)
                     .await?;
 
-                // TODO(#2127): Just marking the failing ancestor and the sync head is enough
-                // to fix the Missing Ancestors hive test, we want to look at a more robust
-                // solution in the future if needed.
-                store
-                    .set_latest_valid_ancestor(sync_head, last_valid_hash)
-                    .await?;
```
Comment (rodrigo-o) [inline crates/networking/p2p/sync.rs:468]: This is no longer the case, avoiding to set the sync head as invalid still pass the Missing Ancestors test. This is also related to: https://github.com/lambdaclass/ethrex/issues/2767 we might not want to set the canonical block as invalid (as we are doing above this lines) but failing instead

File: crates/networking/p2p/sync.rs [hunk 2]
```diff
@@ -460,12 +462,8 @@ impl Syncer {
...
+                // TODO(#2127): Just marking the failing ancestor is enough for the the Missing Ancestors hive test,
```
Comment (JereSalo) [inline crates/networking/p2p/sync.rs:461]: This comment was kept on purpose?

Comment (rodrigo-o) [reply crates/networking/p2p/sync.rs:461]: Yes, the comment referenced not just the line remove but the previous one too

File: crates/networking/p2p/kademlia.rs [hunk 3]
```diff
@@ -319,8 +348,28 @@ impl KademliaTable {
         }
     }
 
+    /// Reward a peer for successful response
+    pub fn reward_peer(&mut self, node_id: H256) {
```
Comment (Mechanix97) [inline crates/networking/p2p/kademlia.rs:352]: may be add some debug ?

Comment (Mechanix97) [reply crates/networking/p2p/kademlia.rs:352]: I saw that there are some warn below

Comment (Mechanix97) [reply crates/networking/p2p/kademlia.rs:352]: But they are only for penalizing. I think that would be nice to show in debug the peer score

**Review by mechanix97 — APPROVED** [review]

File: crates/networking/p2p/kademlia.rs (hunk 3 above)
Comment (rodrigo-o) [reply crates/networking/p2p/kademlia.rs:352]: Agree, I'll add it!

Comment (rodrigo-o) [reply crates/networking/p2p/kademlia.rs:352]: Done here: [Adding debug tracing for penalize and reward](https://github.com/lambdaclass/ethrex/pull/3042/commits/cfd5691e36a4f42b1ca01d7607d55a8c9b7ebc48)

**Review by fmoletta — COMMENTED** [review]
Please update the PR's name to match the new version!

**Comment by rodrigo-o** [comment]
> Please update the PR's name to match the new version! Mentioning the peer scoring change will make it a lot easier to pinpoint this PR in the future

Good catch, done!
