### PR TITLE
test(l1): fix EEST RLP tests

### LINKED ISSUE #3405: Fix EEST Consume RLP tests
Image
They should all pass

### PR DESCRIPTION
**Pull request by JereSalo**
**Motivation**

**Description**

- Execute `.rlp` files (each represent a block in execution-spec-tests) in the correct order
- Set the canonical block right after executing it, so that if one of the executed block fails then the canonical block is the previous of the failed block. Before we only set the canonical block if all blocks executed succeeded.

[Example Run](https://github.com/lambdaclass/ethrex/actions/runs/15984844429)

Closes #3405

### CODE REVIEW

File: cmd/ethrex/cli.rs [hunk 1]
```diff
@@ -396,15 +404,13 @@ pub async fn import_blocks(
             .add_block(block)
             .await
             .inspect_err(|_| warn!("Failed to add block {number} with hash {hash:#x}",))?;
-    }
 
-    _ = store
-        .mark_chain_as_canonical(&blocks)
-        .await
-        .inspect_err(|error| warn!("Failed to apply fork choice: {}", error));
+        // Set executed block as canonical
```
Comment (mpaulucci) [inline cmd/ethrex/cli.rs]: is this the behaviour in other clients too?

**Review by mpaulucci — APPROVED** [review]

File: cmd/ethrex/cli.rs (hunk 1 above)
Comment (JereSalo) [reply cmd/ethrex/cli.rs]: Good question.
I was looking at geth code and it seems like they import the chain for each .rlp file, and we instead read all the files first and store them in a list of blocks and then process those blocks as if they were only ONE chain.

So, maybe a cleaner approach to solve this problem is to process file by file.
To simplify it
```
for file in files_read {
    // code for importing chain, processing each block of the `.rlp` file
}
```
What we are currently doing is
```
let blocks = get_blocks(files_read); // Imagine this gets all blocks from the files in a directory
for block in blocks {
    // execute block and set as canonical.
}
```

So, if you do `import 1.rlp, 2.rlp, 3.rlp` in geth they will import each file chains separately one after another, whereas in ethrex we read the files, store all the blocks consecutively in one chain and we import the chain.
I prefer geth approach because it may be better than setting the canonical chain after every single block

Comment (JereSalo) [reply cmd/ethrex/cli.rs]: I finally made changes in these commits:
https://github.com/lambdaclass/ethrex/pull/3415/commits/bb5d80ce2bc2f9f7d924b56a526ed6fb7ce945c4
https://github.com/lambdaclass/ethrex/pull/3415/commits/7727e614236fb216369ee9574286114ae02849bb
Now instead of importing all blocks as if they were only one chain we import each chain separately. Each `.rlp` file is one chain that we import and we import them one after the other.

File: cmd/ethrex/cli.rs [hunk 2]
```diff
@@ -367,62 +367,74 @@ pub async fn import_blocks(
...
+    for blocks in chains {
+        let size = blocks.len();
+        // Execute block by block
+        for block in &blocks {
+            let hash = block.hash();
+            let number = block.header.number;
+            info!("Adding block {number} with hash {hash:#x}.");
+            // Check if the block is already in the blockchain, if it is do nothing, if not add it
+            let block_number = store.get_block_number(hash).await.map_err(|_e| {
+                ChainError::Custom(String::from(
```
Comment (mpaulucci) [inline cmd/ethrex/cli.rs:404]: nit: we could just ignore this error and just try to add the block
