### PR TITLE
fix(l1): fix high memory usage in `ethrex_replay`

### LINKED ISSUE #4089: `ethrex_replay`: improve memory usage on guest program
Using `ethrex-replay`, we found that some block executions that succeed when executing without any prover backend (like SP1) fail to execute with memory allocation errors when executing with SP1. Being the successful block execution proof generation our end goal, if a block execution fails, its proof generation will also fail. The typical logs are like this `stderr: memory allocation of 340 bytes failed`. 

This happens with lots of blocks (mainly mainnet ones), just try to execute some with the following command and you'll see. A Hoodi block that has this issue is 990075.

To execute the latest block of `NETWORK` (`hoodi`, `mainnet`, `sepolia`) with SP1 go to the branch of https://github.com/lambdaclass/ethrex/pull/3992 (`main` if it is merged), and run:
```
cargo run --release --package ethrex-replay --bin ethrex-replay --features sp1 -- execute block --rpc-url <RPC_URL> --network <NETWORK> 
```

To reproduce easily, try replaying mainnet's latest block.

### PR DESCRIPTION
**Pull request by JereSalo**
**Motivation**

Fix memory problems when executing with SP1 on replay with heavy blocks. The cause was that SP1 embedded allocator has a max of 1GB memory allocated and we were exceeding even 3GB. This improves memory usage of ethrex replay itself (independently of the zkvm used) and as a consequence we don't have these kind of errors anymore because memory usage is now drastically lower.

**Description**

Bytehound of a normal run for a [heavy mainnet block](https://etherscan.io/block/23242537). 
Pre Fix:
image

Post Fix:
image

From 3.2GB RAM to 42MB
~20% improvement in performance. From 10s to 8s.

Closes #4089

### CODE REVIEW

**Review by edg-l — APPROVED** [review]

File: crates/common/trie/trie.rs [hunk 1]
```diff
@@ -266,26 +266,29 @@ impl Trie {
...
         mut state_nodes: HashMap<NodeHash, NodeRLP>,
     ) -> Result<Self, TrieError> {
-        // TODO: Try to remove this clone.
-        let Some(root) = state_nodes.get(&root_hash).cloned() else {
-            let in_memory_trie = Box::new(InMemoryTrieDB::new(Arc::new(Mutex::new(state_nodes))));
-            return Ok(Trie::new(in_memory_trie));
-        };
+        let root_rlp = state_nodes
+            .remove(&root_hash)
+            .expect("Trie should have root hash");
```
Comment (LeanSerra) [inline crates/common/trie/trie.rs]: This function already returns a result, we should return an error

File: crates/common/trie/trie.rs [hunk 2]
```diff
@@ -298,8 +301,8 @@ impl Trie {
                         unreachable!()
                     };
 
-                    node.child = match storage.remove(&hash) {
-                        Some(rlp) => inner(storage, &rlp)?.into(),
+                    node.child = match all_nodes.remove(&hash) {
+                        Some(rlp) => inner(all_nodes, &hash, rlp.clone(), traversed_nodes)?.into(),
```
[the remark this answers is not in the document]
Comment (JereSalo) [reply crates/common/trie/trie.rs]: That's correct
https://github.com/lambdaclass/ethrex/pull/4254/commits/7f49ca0a30b29f05d0cf0114e988c386e30b4c64

**Review by tomip01 — APPROVED** [review]

File: crates/common/trie/trie.rs (hunk 1 above)
Comment (JereSalo) [reply crates/common/trie/trie.rs]: Yeah, my bad. Thank you very much.
https://github.com/lambdaclass/ethrex/pull/4254/commits/654a057f19cec0e6696c5e9e52c943aadac270ef

**Review by ilitteri — APPROVED** [review]
