### PR TITLE
fix(levm): `smod` non-compliance

### LINKED ISSUE #1291: [SECURITY] Non-Compliance : Incorrect Handling of SMOD Opcode in levm
Our team at [FuzzingLabs](https://github.com/FuzzingLabs) has identified a new non-compliance in the [op_smod](https://github.com/lambdaclass/ethrex/blob/main/crates/vm/levm/src/opcode_handlers/arithmetic.rs#L131) implementation. Specifically, the function fails to properly handle cases where the remainder (`remainder`) of the signed modulus operation is zero and the dividend is negative. This issue leads to the function incorrectly pushing `U256::MAX` onto the stack instead of the expected value, which should be `0`. This behavior deviates from the expected EVM behavior and could lead to unintended results during contract execution.

## Root cause

```rust
    // SMOD operation
    pub fn op_smod(
        &mut self,
        current_call_frame: &mut CallFrame,
    ) -> Result<OpcodeSuccess, VMError> {
        self.increase_consumed_gas(current_call_frame, gas_cost::SMOD)?;

        let dividend = current_call_frame.stack.pop()?;
        let divisor = current_call_frame.stack.pop()?;
        if divisor.is_zero() {
            current_call_frame.stack.push(U256::zero())?;
        } else {
            let normalized_dividend = abs(dividend);
            let normalized_divisor = abs(divisor);

            let mut remainder =
                normalized_dividend
                    .checked_rem(normalized_divisor)
                    .ok_or(VMError::Internal(
                        InternalError::ArithmeticOperationDividedByZero,
                    ))?; // Cannot be zero bc if above;

            // The remainder should have the same sign as the dividend
            if is_negative(dividend) {
                remainder = negate(remainder);
            }

            current_call_frame.stack.push(remainder)?;
        }

        Ok(OpcodeSuccess::Continue)
    }
```

The issue lies in the following section of the `op_smod` implementation:

```rust
if is_negative(dividend) {
    remainder = negate(remainder);
}

```

Here’s the step-by-step breakdown of the problem:

1. When the `dividend` is negative, the function checks if `is_negative(dividend)` is true.
2. Regardless of the value of `remainder`, the function applies the `negate` operation.
3. If `remainder` is `0`, the `negate` function incorrectly returns `U256::MAX` instead of `0`.

The `negate` function performs a two's complement operation:

```rust
fn negate(value: U256) -> U256 {
    let inverted = !value;
    inverted.saturating_add(U256::one())
}
```

For a value of `0`, the complement and addition result in `U256::MAX`.

## Step to reproduce

**Payload**

```rust
[0x60, 1, 0x60, 1, 0x19, 0x07]

PUSH1 1
PUSH1 1
NOT
SMOD
```

Add to [test](https://github.com/lambdaclass/ethrex/blob/main/crates/vm/levm/tests/edge_case_tests.rs):

```rust
#[test]
fn test_non_compliance_smod() {
    let mut vm = new_vm_with_bytecode(Bytes::copy_from_slice(&[0x60, 1, 0x60, 1, 0x19, 0x07]
    ))
    .unwrap();
    let mut current_call_frame = vm.call_frames.pop().unwrap();
    vm.execute(&mut current_call_frame);
    assert_eq!(current_call_frame.stack.stack[0], U256::zero());
}
```

## Backtrace

```rust
thread 'test_non_compliance_smod' panicked at crates/vm/levm/tests/edge_case_tests.rs:17:5:
assertion `left == right` failed
  left: 115792089237316195423570985008687907853269984665640564039457584007913129639935
 right: 0
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c/library/core/src/panicking.rs:76:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /home/mhoste/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:373:5
   4: edge_case_tests::test_non_compliance_smod
             at ./tests/edge_case_tests.rs:17:5
   5: edge_case_tests::test_non_compliance_smod::{{closure}}
             at ./tests/edge_case_tests.rs:11:30
   6: core::ops::function::FnOnce::call_once
             at /home/mhoste/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/8adb4b30f40e6fbd21dc1ba26c3301c7eeb6de3c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

failures:
    test_non_compliance_smod

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 21 filtered out; finished in 0.10s
```

### PR DESCRIPTION
**Pull request by ilitteri**
Resolves #1291

### CODE REVIEW

File: crates/vm/levm/src/opcode_handlers/arithmetic.rs [hunk 1]
```diff
@@ -134,28 +134,46 @@ impl VM {
...
-            if is_negative(dividend) {
-                remainder = negate(remainder);
+            unchecked_dividend
+        };
+
+        let unchecked_remainder = match dividend.checked_rem(divisor) {
+            Some(remainder) => remainder,
+            None => {
+                current_call_frame.stack.push(U256::zero())?;
+                return Ok(OpcodeSuccess::Continue);
```
Comment (JereSalo) [inline crates/vm/levm/src/opcode_handlers/arithmetic.rs:165]: This behavior is repeated, maybe we can remove the `if unchecked_divisor.is_zero() {` at the beginning of the function and leave this one instead.

**Review by JereSalo — APPROVED** [review]
I strongly suggest using the `negate` function. We have to change it though because it's current implementation is wrong:
It should be something like
```rust
/// Negates a number in two's complement
fn negate(value: U256) -> U256 {
    let inverted = !value;
    inverted.overflowing_add(U256::one()).0
}
```
And maybe even use the now deleted `abs` function. (That negates only if necessary)
I think both these changes could make the code much more reader-friendly.
Let me know what you think 😀

**Comment by ilitteri** [comment]
> I strongly suggest using the `negate` function. We have to change it though because it's current implementation is wrong: It should be something like
> 
> ```rust
> /// Negates a number in two's complement
> fn negate(value: U256) -> U256 {
>     let inverted = !value;
>     inverted.overflowing_add(U256::one()).0
> }
> ```
> 
> And maybe even use the now deleted `abs` function. (That negates only if necessary) I think both these changes could make the code much more reader-friendly. Let me know what you think 😀

I agree. Done in [1c20509](https://github.com/lambdaclass/ethrex/pull/1305/commits/1c2050901b1c09de1d1626750d3541c30af8c21d) and [34da961](https://github.com/lambdaclass/ethrex/pull/1305/commits/34da96149dceb70ea0a713c2d1f856426d6f3e4c)
