### PR TITLE
fix(l1): metrics exporter dashboard total peer count panel

### LINKED ISSUE #3468: Metrics Exporter Dashboard Panels shows no peers
The ethereum metrics exporter dashboard panel for total peers shows no peers when syncing.

### PR DESCRIPTION
**Pull request by cdiielsi**
**Motivation**

Ethereum Metrics Exporter dashboard is showing no peers when running a sync, as described in the issue #3104.

**Description**

This pr fixes the rpc call handler for net_peerCount as described [here](https://ethereum.org/en/developers/docs/apis/json-rpc/#net_peercount).

It also introduces a new function for `PeerHandler` to access the connected peers so the rpc call handler can get the amount.

Here you can see how the panel looks like now:
Screenshot 2025-07-03 at 13 29 57

To run this you can go to tooling/sync and run make start_hoodi_metrics_docker, then go to http://localhost:3001/ to see the panels.

Closes #3468

### CODE REVIEW

File: crates/networking/p2p/peer_handler.rs [hunk 1]
```diff
@@ -826,6 +826,15 @@ impl PeerHandler {
...
 
+    pub async fn read_total_peers(&self) -> Vec<PeerData> {
+        self.peer_table
+            .lock()
+            .await
+            .iter_peers()
+            .cloned()
+            .collect::<Vec<_>>()
+    }
+
```
Comment (fmoletta) [inline crates/networking/p2p/peer_handler.rs]: Cloning all peers if we only want to count them seems overkill, maybe this could be `count_total_peers` instead and just return the total count?

Comment (cdiielsi) [reply crates/networking/p2p/peer_handler.rs]: Done!

File: crates/networking/p2p/peer_handler.rs [hunk 2]
```diff
@@ -826,6 +826,15 @@ impl PeerHandler {
         )
     }
 
+    pub async fn count_total_peers(&self) -> usize {
+        self.peer_table
+            .lock()
+            .await
+            .iter_peers()
+            .collect::<Vec<_>>()
+            .len()
```
Comment (fmoletta) [inline crates/networking/p2p/peer_handler.rs]:
```suggestion
            .count()
```

**Review by santiago-MV — APPROVED** [review]
LGTM!
