### PR TITLE
chore(l1): fix IPv6 listener

### LINKED ISSUE #4232: Add support for Ipv6 P2P connections
During snap sync with hoodi, sending the FindNode messages to our peers fails due to the error `MessageSendFailure(Os { code: 97, kind: Uncategorized, message: "Address family not supported by protocol" })`. This is likely due to IPv6 usage in `ethrex_p2p::discv4::side_car:`

### PR DESCRIPTION
**Pull request by fedacking**
**Motivation**

We had issues when handling discovery with IPv6 connections, because we used a TCPv4 stream. With a TCPv6 stream, it should handle both IPv4 and IPv6 connections

**Description**

- Removed superflous parameter for p2p address
- Fixed the listener to support ipv6 port
- Made the default port ipv6
- Changed documentation and makefile to new format

Closes #4232

### CODE REVIEW

File: cmd/ethrex/initializers.rs [hunk 1]
```diff
@@ -290,17 +290,14 @@ pub fn get_signer(data_dir: &str) -> SecretKey {
...
 
-    // TODO: If hhtp.addr is 0.0.0.0 we get the local ip as the one of the node, otherwise we use the provided one.
-    // This is fine for now, but we might need to support more options in the future.
-    let p2p_node_ip = if udp_socket_addr.ip() == Ipv4Addr::new(0, 0, 0, 0) {
-        local_ip().expect("Failed to get local ip")
-    } else {
-        udp_socket_addr.ip()
+    let p2p_node_ip = match local_ip() {
+        Ok(ip) => ip,
+        Err(_) => local_ipv6().expect("Failed to get local ip v6"),
```
Comment (pablodeymo) [inline cmd/ethrex/initializers.rs]: it's better to use `unwrap_or_else` instead this match

Comment (gianbelinche) [reply cmd/ethrex/initializers.rs]: Done

**Review by Oppen — APPROVED** [review]

File: cmd/ethrex/initializers.rs (hunk 1 above)
Comment (Oppen) [reply cmd/ethrex/initializers.rs]: At initialization time I'd prefer for the program to crash if it can't go on. If it does that at a higher level then it's OK.

Comment (gianbelinche) [reply cmd/ethrex/initializers.rs]: If neither ipv4 nor ipv6 is available it will crash in that expect.
If we only have ipv6 we still want to use it

File: cmd/ethrex/initializers.rs [hunk 2]
```diff
@@ -290,18 +290,13 @@ pub fn get_signer(data_dir: &str) -> SecretKey {
...
 
-    // TODO: If hhtp.addr is 0.0.0.0 we get the local ip as the one of the node, otherwise we use the provided one.
-    // This is fine for now, but we might need to support more options in the future.
-    let p2p_node_ip = if udp_socket_addr.ip() == Ipv4Addr::new(0, 0, 0, 0) {
-        local_ip().expect("Failed to get local ip")
-    } else {
-        udp_socket_addr.ip()
-    };
+    let p2p_node_ip =
+        local_ip().unwrap_or_else(|_| local_ipv6().expect("Failed to get local ip v6"));
```
Comment (iovoid) [inline cmd/ethrex/initializers.rs]: This error message could be better

Comment (gianbelinche) [reply cmd/ethrex/initializers.rs]: Done

**Review by jrchatruc — APPROVED** [review]
