### PR TITLE
fix(l1): full-sync with both consensus and execution node

### LINKED ISSUE #2066: L1: fix full-sync with both consensus and execution node
When performing a full-sync with the consensus node (instead of a checkpoint-sync) it can happen that we receive a `forkChoiceUpdate` with a low block_number `~14` and our sync process starts downloading `MAX_BLOCK_BODIES_TO_REQUEST=128`. After processing all downloaded blocks, our canonical head ends up more advanced than the consensus one, resulting in invalid responses to the `forkChoiceUpdate`.

This can be fixed with something similar to what is done in [apply_fork_choice]( https://github.com/lambdaclass/ethrex/blob/1084c97447a4838dc389e56972e6d8cda09565e9/crates/blockchain/fork_choice.rs#L116) and updating the latest block number`store.update_latest_block_number();` after processing the downloaded blocks.

### PR DESCRIPTION
**Pull request by avilagaston9**
**Motivation**

Currently, during full-sync, we download, execute and store blocks as canonical in chunks of `MAX_BLOCK_BODIES_TO_REQUEST=128`. However, we do not verify whether we are ahead of the consensus head, which results in invalid `forkChoice` responses.

**Description**

- Filters the downloaded headers to request only the needed bodies to peers.

Closes #2066

### CODE REVIEW

File: crates/networking/p2p/sync.rs [hunk 1]
```diff
@@ -265,7 +265,7 @@ impl SyncManager {
             store.add_block_headers(block_hashes.clone(), block_headers)?;
 
             if self.sync_mode == SyncMode::Full {
-                self.download_and_run_blocks(&mut block_hashes, store.clone())
+                self.download_and_run_blocks(&mut block_hashes, store.clone(), sync_head)
```
Comment (mpaulucci) [inline crates/networking/p2p/sync.rs:268]: maybe, instead of passing `sync_head `, you should filter `block_hashes` so that every block after `sync_head` is filtered out. Does this make sense?

Comment (avilagaston9) [reply crates/networking/p2p/sync.rs:268]: Yes! Actually, my approach for some reason wasn't working. This is simpler and it is working in the server. I will update the PR later

Comment (avilagaston9) [reply crates/networking/p2p/sync.rs]: Updated!

File: crates/networking/p2p/sync.rs [hunk 2]
```diff
@@ -265,6 +265,14 @@ impl SyncManager {
...
 
             if self.sync_mode == SyncMode::Full {
+                if sync_head_found {
+                    // Filter out everything after the sync_head
+                    block_hashes = block_hashes
+                        .iter()
+                        .take_while(|&hash| *hash != sync_head)
+                        .cloned()
+                        .collect();
+                }
```
Comment (MarcosNicolau) [inline crates/networking/p2p/sync.rs:275]: This logic should be on both sync modes: snap and full.

Comment (avilagaston9) [reply crates/networking/p2p/sync.rs]: Updated in [973719d](https://github.com/lambdaclass/ethrex/pull/2081/commits/973719daf85e202d930e691025c2b6d076e0a17d)!

**Review by mpaulucci — APPROVED** [review]

**Review by MarcosNicolau — APPROVED** [review]
